import { getChatGPTUser } from "../../chatgpt-auth";
import { maintenanceResponse } from "../../maintenance";
import { deleteStoredModelConfig, getStoredModelConfig, saveStoredModelConfig } from "../../../db/model-config";
import { deleteStoredImageGenerationConfig, getStoredImageGenerationConfig, saveStoredImageGenerationConfig } from "../../../db/image-generation-config";
import { deleteStoredVideoGenerationConfig, getStoredVideoGenerationConfig, saveStoredVideoGenerationConfig } from "../../../db/video-generation-config";
import { deleteModelService, getModelService, listModelServices, saveModelService, type ModelServiceKind } from "../../../db/model-services";
import { MODEL_PROVIDERS, normalizeBaseUrl, providerById } from "../../model-providers";
import { IMAGE_GENERATION_PROVIDERS, imageGenerationProviderById, normalizeImageBaseUrl } from "../../image-generation-providers";
import { VIDEO_GENERATION_PROVIDERS, isTrustedVideoProviderUrl, normalizeVideoBaseUrl, videoGenerationProviderById } from "../../video-generation-providers";
import { apiReply, enforceRateLimit, isSafePublicHttps, matchesTrustedProviderHost, readJsonBody, rejectCrossSiteMutation, RequestValidationError, safeModelId } from "../../api-security";

export const dynamic="force-dynamic";const reply=apiReply;
type Body={action?:"save"|"activate"|"delete";id?:string;kind?:ModelServiceKind;label?:string;providerId?:string;apiBaseUrl?:string;model?:string;apiKey?:string;apiSecret?:string};
function providerFor(kind:ModelServiceKind,id:string){return kind==="language"?MODEL_PROVIDERS.find(item=>item.id===id):kind==="image"?IMAGE_GENERATION_PROVIDERS.find(item=>item.id===id):VIDEO_GENERATION_PROVIDERS.find(item=>item.id===id)}
function baseUrlFor(kind:ModelServiceKind,value:string){return kind==="language"?normalizeBaseUrl(value):kind==="image"?normalizeImageBaseUrl(value):normalizeVideoBaseUrl(value)}
function validEndpoint(kind:ModelServiceKind,providerId:string,value:string){const provider=providerFor(kind,providerId);if(!provider||!isSafePublicHttps(value))return false;if(kind==="video")return isTrustedVideoProviderUrl(value,videoGenerationProviderById(providerId));if(kind==="language")return matchesTrustedProviderHost(value,providerId==="custom"?"":providerById(providerId).baseUrl);return matchesTrustedProviderHost(value,imageGenerationProviderById(providerId).baseUrl)}
async function activate(userId:string,connection:NonNullable<Awaited<ReturnType<typeof getModelService>>>){if(connection.kind==="language")return saveStoredModelConfig(userId,{providerId:connection.providerId,apiBaseUrl:connection.apiBaseUrl,model:connection.model,apiKey:connection.apiKey});if(connection.kind==="image")return saveStoredImageGenerationConfig(userId,{providerId:connection.providerId,apiBaseUrl:connection.apiBaseUrl,model:connection.model,apiKey:connection.apiKey});return saveStoredVideoGenerationConfig(userId,{providerId:connection.providerId,apiBaseUrl:connection.apiBaseUrl,model:connection.model,apiKey:connection.apiKey,apiSecret:connection.apiSecret||undefined})}
async function importLegacy(userId:string){const current=await listModelServices(userId);const legacy=await Promise.all([getStoredModelConfig(userId),getStoredImageGenerationConfig(userId),getStoredVideoGenerationConfig(userId)]);for(const [index,item] of legacy.entries()){if(!item)continue;const kind=(index===0?"language":index===1?"image":"video") as ModelServiceKind;if(current.some(connection=>connection.kind===kind&&connection.providerId===item.providerId&&connection.apiBaseUrl===item.apiBaseUrl&&connection.model===item.model))continue;await saveModelService(userId,{kind,label:`${providerFor(kind,item.providerId)?.name||item.providerId} · ${item.model}`,providerId:item.providerId,apiBaseUrl:item.apiBaseUrl,model:item.model,apiKey:item.apiKey,apiSecret:"apiSecret" in item?item.apiSecret||undefined:undefined})}}

export async function GET(){const user=await getChatGPTUser();const maintenance=maintenanceResponse(user);if(maintenance)return maintenance;if(!user)return reply({error:"请先登录。",code:"AUTH-1001"},401);const limited=await enforceRateLimit(user.userId,"model-services-read",120,3600);if(limited)return limited;await importLegacy(user.userId);return reply({connections:await listModelServices(user.userId)})}
export async function POST(request:Request){
  const user=await getChatGPTUser();const maintenance=maintenanceResponse(user);if(maintenance)return maintenance;if(!user)return reply({error:"请先登录后管理模型服务。",code:"AUTH-1001"},401);const crossSite=rejectCrossSiteMutation(request);if(crossSite)return crossSite;const limited=await enforceRateLimit(user.userId,"model-services-write",60,3600);if(limited)return limited;
  let body:Body;try{body=await readJsonBody(request,65_536)}catch(error){return error instanceof RequestValidationError?reply({error:error.message,code:"REQ-3001"},error.status):reply({error:"连接信息格式不正确。",code:"REQ-3001"},400)}const action=body.action||"save";
  if(action==="delete"){if(!body.id)return reply({error:"缺少连接编号。",code:"REQ-3001"},400);const connection=await getModelService(user.userId,body.id);if(!connection)return reply({error:"模型连接不存在。",code:"CFG-2006"},404);if(connection.kind==="language"){const active=await getStoredModelConfig(user.userId);if(active?.providerId===connection.providerId&&active.model===connection.model&&active.apiBaseUrl===connection.apiBaseUrl)await deleteStoredModelConfig(user.userId)}else if(connection.kind==="image"){const active=await getStoredImageGenerationConfig(user.userId);if(active?.providerId===connection.providerId&&active.model===connection.model&&active.apiBaseUrl===connection.apiBaseUrl)await deleteStoredImageGenerationConfig(user.userId)}else{const active=await getStoredVideoGenerationConfig(user.userId);if(active?.providerId===connection.providerId&&active.model===connection.model&&active.apiBaseUrl===connection.apiBaseUrl)await deleteStoredVideoGenerationConfig(user.userId)}await deleteModelService(user.userId,body.id);return reply({deleted:true,connections:await listModelServices(user.userId)})}
  if(action==="activate"){if(!body.id)return reply({error:"缺少连接编号。",code:"REQ-3001"},400);const connection=await getModelService(user.userId,body.id);if(!connection)return reply({error:"模型连接不存在。",code:"CFG-2006"},404);const config=await activate(user.userId,connection);return reply({connection:{...connection,apiKey:undefined,apiSecret:undefined},config})}
  const kind=body.kind;const providerId=body.providerId?.trim()||"";if(kind!=="language"&&kind!=="image"&&kind!=="video")return reply({error:"请选择模型能力类型。",code:"CFG-2001"},400);const provider=providerFor(kind,providerId);if(!provider)return reply({error:"不支持的模型服务商。",code:"CFG-2001"},400);const apiBaseUrl=baseUrlFor(kind,body.apiBaseUrl||provider.baseUrl);const model=body.model?.trim()||"";if(!safeModelId(model)||!validEndpoint(kind,providerId,apiBaseUrl))return reply({error:"模型或接口地址无效。",code:"CFG-2004"},400);const apiKey=body.apiKey?.trim()||undefined;if(apiKey&&apiKey.length<12)return reply({error:"API Key 不完整。",code:"CFG-2002"},400);const existing=body.id?await getModelService(user.userId,body.id):null;if(kind==="video"&&videoGenerationProviderById(providerId).auth==="access-secret"&&!(body.apiSecret?.trim())&&!existing?.apiSecret)return reply({error:"该服务需要同时填写 Access Key 与 Secret Key。",code:"CFG-2002"},400);
  try{const connection=await saveModelService(user.userId,{id:body.id,kind,label:body.label?.trim().slice(0,80)||`${provider.name} · ${model}`,providerId,apiBaseUrl,model,apiKey,apiSecret:body.apiSecret?.trim()||undefined});const full=await getModelService(user.userId,connection.id);const config=await activate(user.userId,full!);return reply({connection,config,connections:await listModelServices(user.userId)})}catch(error){if(error instanceof Error&&error.message==="API_KEY_REQUIRED")return reply({error:"新增连接或切换服务商时必须填写 API Key。",code:"CFG-2002"},400);return reply({error:"模型连接暂时无法保存。",code:"CFG-2005"},500)}
}
