export type FrameError={code:string;title:string;message:string;detail?:string};

export const FRAME_ERROR_CATALOG=[
  {code:"AUTH-1001",title:"需要登录",match:/登录|sign.?in|unauthor/i},
  {code:"AUTH-1002",title:"登录状态已失效",match:/session|身份|认证.*失效/i},
  {code:"AUTH-1003",title:"当前账户没有访问权限",match:/没有权限|无权访问|access denied/i},
  {code:"AUTH-1004",title:"站点正在维护",match:/维护模式|maintenance/i},
  {code:"CFG-2001",title:"尚未连接模型服务",match:/未配置|请选择模型|missing.*config/i},
  {code:"CFG-2002",title:"模型凭证无效",match:/api.?key|secret.?key|鉴权|unauthor|forbidden/i},
  {code:"CFG-2003",title:"模型当前不可用",match:/模型.*不可用|model.*(invalid|not found|unsupported)/i},
  {code:"CFG-2004",title:"接口地址无效",match:/接口地址|base.?url|不安全/i},
  {code:"CFG-2005",title:"连接信息保存失败",match:/配置.*保存|连接.*保存|save.*config/i},
  {code:"CFG-2006",title:"模型连接不存在",match:/连接不存在|connection.*not found/i},
  {code:"CFG-2007",title:"服务地址与厂商不匹配",match:/域名.*不匹配|host.*mismatch/i},
  {code:"CFG-2008",title:"模型能力与工作台不匹配",match:/能力.*不匹配|workflow.*unsupported/i},
  {code:"REQ-3001",title:"请求内容有误",match:/格式不正确|请求.*无效|invalid request/i},
  {code:"REQ-3002",title:"文件或内容过大",match:/过大|too large|size limit/i},
  {code:"REQ-3003",title:"请求过于频繁",match:/频繁|rate.?limit|too many/i},
  {code:"REQ-3004",title:"缺少必填内容",match:/请先填写|必填|missing required/i},
  {code:"REQ-3005",title:"文件类型不受支持",match:/文件类型|unsupported file/i},
  {code:"REQ-3006",title:"参考素材数量超出限制",match:/参考.*数量|reference.*limit/i},
  {code:"REQ-3007",title:"请求已取消",match:/已取消|aborted|cancelled/i},
  {code:"GEN-4001",title:"生成任务失败",match:/生成失败|generation failed/i},
  {code:"GEN-4002",title:"内容未通过安全检查",match:/安全过滤|审核未通过|content.*filter/i},
  {code:"GEN-4003",title:"模型响应超时",match:/超时|timeout/i},
  {code:"GEN-4004",title:"服务账户额度不足",match:/余额不足|insufficient.*(balance|credit|quota)/i},
  {code:"GEN-4005",title:"生成结果暂不可读取",match:/没有返回|结果.*无法|result.*missing/i},
  {code:"GEN-4006",title:"任务仍在服务商队列",match:/仍在.*队列|still.*queue/i},
  {code:"GEN-4007",title:"服务商响应格式异常",match:/响应格式|invalid.*response/i},
  {code:"IMG-4101",title:"参考图片不符合要求",match:/参考图|首帧|尾帧|reference image/i},
  {code:"IMG-4102",title:"图片读取或上传失败",match:/图片.*(读取|上传)|image.*upload/i},
  {code:"IMG-4103",title:"图片生成失败",match:/图片.*生成失败|image generation/i},
  {code:"IMG-4104",title:"图片任务查询失败",match:/图片任务.*查询|image task.*poll/i},
  {code:"IMG-4105",title:"图片下载失败",match:/图片.*下载失败|image download/i},
  {code:"VID-4201",title:"视频任务创建失败",match:/视频任务.*(创建|提交).*失败/i},
  {code:"VID-4202",title:"视频服务暂时不可用",match:/视频服务|video provider/i},
  {code:"VID-4203",title:"视频结果暂不可读取",match:/视频文件|video result/i},
  {code:"VID-4204",title:"视频下载失败",match:/下载.*失败|download.*failed/i},
  {code:"VID-4205",title:"视频任务查询失败",match:/视频任务.*查询|video task.*poll/i},
  {code:"VID-4206",title:"视频任务已过期",match:/任务.*过期|task.*expired/i},
  {code:"VID-4207",title:"视频参数不受模型支持",match:/视频参数|duration.*unsupported|aspect.*unsupported/i},
  {code:"VID-4208",title:"视频素材上传失败",match:/视频素材.*上传|video asset.*upload/i},
  {code:"VID-4209",title:"服务商未返回可播放地址",match:/可播放地址|playable.*url/i},
  {code:"COMFY-4301",title:"ComfyUI 服务未连接",match:/comfy.*(连接|backend|offline)/i},
  {code:"COMFY-4302",title:"ComfyUI 工作流导入失败",match:/comfy.*导入|workflow.*import/i},
  {code:"COMFY-4303",title:"ComfyUI 节点缺失",match:/节点.*缺失|missing.*node/i},
  {code:"COMFY-4304",title:"ComfyUI 模型缺失",match:/comfy.*模型.*缺失|missing.*checkpoint/i},
  {code:"COMFY-4305",title:"ComfyUI 执行失败",match:/comfy.*执行|prompt.*execution/i},
  {code:"DATA-4401",title:"账户配置同步失败",match:/账户配置.*同步|sync.*config/i},
  {code:"DATA-4402",title:"生成历史保存失败",match:/历史.*保存|save.*history/i},
  {code:"SYS-5001",title:"网络连接失败",match:/网络|network|failed to fetch/i},
  {code:"SYS-5002",title:"服务器暂时不可用",match:/服务器|server|internal error/i},
  {code:"SYS-5003",title:"发生未知错误",match:/未知错误|unknown error/i},
  {code:"SYS-5004",title:"浏览器不支持此功能",match:/浏览器.*不支持|not supported.*browser/i},
  {code:"SYS-5005",title:"本地存储不可用",match:/localstorage|本地存储/i},
  {code:"SYS-5006",title:"页面资源加载失败",match:/资源.*加载|chunk.*load|asset.*failed/i},
  {code:"SYS-5007",title:"服务暂时拥堵",match:/拥堵|overloaded|service busy/i},
] as const;

export function classifyFrameError(message:string,providedCode?:string):FrameError{const matched=providedCode?FRAME_ERROR_CATALOG.find(item=>item.code===providedCode):FRAME_ERROR_CATALOG.find(item=>item.match.test(message));return{code:matched?.code||providedCode||"SYS-5003",title:matched?.title||"发生未知错误",message:message||"操作没有完成，请稍后重试。"}}

export function reportFrameError(message:string,code?:string){if(typeof window!=="undefined")window.dispatchEvent(new CustomEvent("frame:error",{detail:{message,code}}))}
