"use client";

import { forwardRef, useEffect, useImperativeHandle, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { JOINT_NAMES, neutralPose, posePresets, type JointMap, type Point, type PoseGender, type PosePreset } from "./pose-presets";

export type RigView="front"|"left"|"right"|"back"|"top";
export type DragAxis="screen"|"x"|"y"|"z";
export type CharacterFacing="front"|"left"|"right"|"back";

export type PoseRigHandle={
  capture:()=>string;reset:()=>void;mirror:()=>void;applyPreset:(preset:PosePreset)=>void;
  applyJointMap:(pose:JointMap)=>void;setRealistic:(enabled:boolean)=>void;
  addPerson:(gender:PoseGender)=>void;removePerson:()=>void;selectPerson:(index:number)=>void;setBodyType:(gender:PoseGender)=>void;
  setView:(view:RigView)=>void;setDragAxis:(axis:DragAxis)=>void;setFacing:(facing:CharacterFacing)=>void;
};

type RigCharacter={
  gender:PoseGender;group:THREE.Group;joints:Record<string,THREE.Mesh>;hitTargets:THREE.Mesh[];bones:THREE.Mesh[];
  head:THREE.Mesh;neckBody:THREE.Mesh;torsoUpper:THREE.Mesh;torsoLower:THREE.Mesh;pelvisBody:THREE.Mesh;hands:THREE.Mesh[];feet:THREE.Mesh[];surfaces:THREE.Mesh[];
};

const mannequinPalette={
  male:{surface:0xaed5f2,joint:0xd8efff,accent:0x4f9bd1,emissive:0x143d5a},
  female:{surface:0xefb7c7,joint:0xffdbe5,accent:0xd66b91,emissive:0x5a1832},
} as const;

const bonePairs:[string,string][]=[
  ["head","neck"],["neck","chest"],["chest","pelvis"],
  ["neck","shoulderL"],["shoulderL","elbowL"],["elbowL","wristL"],
  ["neck","shoulderR"],["shoulderR","elbowR"],["elbowR","wristR"],
  ["pelvis","hipL"],["hipL","kneeL"],["kneeL","ankleL"],
  ["pelvis","hipR"],["hipR","kneeR"],["kneeR","ankleR"],
];
const parentByJoint:Record<string,string>={head:"neck",neck:"chest",chest:"pelvis",shoulderL:"neck",elbowL:"shoulderL",wristL:"elbowL",shoulderR:"neck",elbowR:"shoulderR",wristR:"elbowR",hipL:"pelvis",kneeL:"hipL",ankleL:"kneeL",hipR:"pelvis",kneeR:"hipR",ankleR:"kneeR"};
const childrenByJoint=Object.entries(parentByJoint).reduce<Record<string,string[]>>((result,[child,parent])=>{(result[parent]??=[]).push(child);return result},{});
const chainEnds:Record<string,[string,string,number]>={wristL:["shoulderL","elbowL",158],wristR:["shoulderR","elbowR",158],ankleL:["hipL","kneeL",152],ankleR:["hipR","kneeR",152]};
const chainSwingLimits:Record<string,number>={wristL:172,wristR:172,ankleL:135,ankleR:135};
const middleJoints:Record<string,[string,number]>={elbowL:["wristL",158],elbowR:["wristR",158],kneeL:["ankleL",152],kneeR:["ankleR",152]};
const coneLimits:Record<string,number>={head:55,neck:42,chest:34,shoulderL:24,shoulderR:24,hipL:20,hipR:20,elbowL:165,elbowR:165,kneeL:132,kneeR:132};
const up=new THREE.Vector3(0,1,0);

function clonePose(pose:JointMap){return Object.fromEntries(Object.entries(pose).map(([key,value])=>[key,[...value] as Point])) as JointMap}
function restPose(gender:PoseGender){
  const result=clonePose(neutralPose);const shoulderScale=gender==="male"?1.12:.94;const hipScale=gender==="male"?.9:1.08;
  for(const name of JOINT_NAMES){if(/shoulder|elbow|wrist/.test(name))result[name][0]*=shoulderScale;if(/hip|knee|ankle/.test(name))result[name][0]*=hipScale}
  return result;
}

const PoseRig=forwardRef<PoseRigHandle,{ariaLabel:string;realistic:boolean;onPoseChange?:(pose:JointMap)=>void;onPeopleChange?:(people:PoseGender[],active:number)=>void}>(({ariaLabel,realistic,onPoseChange,onPeopleChange},ref)=>{
  const mountRef=useRef<HTMLDivElement>(null);const realisticRef=useRef(realistic);const onPoseChangeRef=useRef(onPoseChange);const onPeopleChangeRef=useRef(onPeopleChange);
  const apiRef=useRef<PoseRigHandle>({capture:()=>"",reset:()=>{},mirror:()=>{},applyPreset:()=>{},applyJointMap:()=>{},setRealistic:()=>{},addPerson:()=>{},removePerson:()=>{},selectPerson:()=>{},setBodyType:()=>{},setView:()=>{},setDragAxis:()=>{},setFacing:()=>{}});
  useEffect(()=>{realisticRef.current=realistic},[realistic]);useEffect(()=>{onPoseChangeRef.current=onPoseChange},[onPoseChange]);useEffect(()=>{onPeopleChangeRef.current=onPeopleChange},[onPeopleChange]);
  useImperativeHandle(ref,()=>({capture:()=>apiRef.current.capture(),reset:()=>apiRef.current.reset(),mirror:()=>apiRef.current.mirror(),applyPreset:value=>apiRef.current.applyPreset(value),applyJointMap:value=>apiRef.current.applyJointMap(value),setRealistic:value=>apiRef.current.setRealistic(value),addPerson:value=>apiRef.current.addPerson(value),removePerson:()=>apiRef.current.removePerson(),selectPerson:value=>apiRef.current.selectPerson(value),setBodyType:value=>apiRef.current.setBodyType(value),setView:value=>apiRef.current.setView(value),setDragAxis:value=>apiRef.current.setDragAxis(value),setFacing:value=>apiRef.current.setFacing(value)}),[]);

  useEffect(()=>{
    const mount=mountRef.current;if(!mount)return;
    const scene=new THREE.Scene();scene.background=new THREE.Color(0x10100f);scene.fog=new THREE.FogExp2(0x10100f,.038);
    const camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,.7,10.6);
    const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;mount.appendChild(renderer.domElement);
    const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,.35,0);controls.minDistance=6;controls.maxDistance=19;controls.enablePan=false;
    scene.add(new THREE.HemisphereLight(0xffffff,0x30231e,2.5));const key=new THREE.DirectionalLight(0xfff4e9,4.2);key.position.set(4,7,5);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0xff6434,2.1);rim.position.set(-5,3,-4);scene.add(rim);
    const grid=new THREE.GridHelper(15,30,0x6b3b2d,0x262624);grid.position.y=-2.34;scene.add(grid);const floor=new THREE.Mesh(new THREE.CircleGeometry(5.4,80),new THREE.MeshStandardMaterial({color:0x171615,roughness:.85,metalness:.05}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.35;floor.receiveShadow=true;scene.add(floor);

    const characters:RigCharacter[]=[];let activeIndex=0,currentView:RigView="front",dragAxis:DragAxis="screen";
    const surfaceMaterial=(gender:PoseGender)=>new THREE.MeshPhysicalMaterial({color:mannequinPalette[gender].surface,roughness:.58,metalness:0,clearcoat:.18,clearcoatRoughness:.72});
    const handleMaterial=(gender:PoseGender)=>new THREE.MeshStandardMaterial({color:mannequinPalette[gender].joint,emissive:mannequinPalette[gender].emissive,emissiveIntensity:.2,roughness:.34,metalness:.04,transparent:true,opacity:.3,depthWrite:false,depthTest:false});
    const hitMaterial=()=>new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,colorWrite:false});
    const setCylinder=(mesh:THREE.Mesh,a:THREE.Vector3,b:THREE.Vector3,radiusScale=1)=>{const delta=new THREE.Vector3().subVectors(b,a);mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.scale.set(radiusScale,Math.max(.01,delta.length()),radiusScale);mesh.quaternion.setFromUnitVectors(up,delta.clone().normalize())};
    const activeRig=()=>characters[activeIndex];
    const notifyPeople=()=>onPeopleChangeRef.current?.(characters.map(item=>item.gender),activeIndex);
    const paintJoint=(rig:RigCharacter,mesh:THREE.Mesh,state:"idle"|"hover"|"selected"="idle")=>{const material=mesh.material as THREE.MeshStandardMaterial,palette=mannequinPalette[rig.gender],active=characters[activeIndex]===rig;material.color.set(state==="idle"?palette.joint:0xffffff);material.emissive.set(state==="idle"?palette.emissive:palette.accent);material.emissiveIntensity=state==="selected"?1.35:state==="hover"?.92:.2;material.opacity=state==="selected"?1:state==="hover"?.96:active?.34:.14;mesh.scale.setScalar(state==="selected"?1.65:state==="hover"?1.45:1)};
    const refreshAppearance=(rig:RigCharacter)=>{const palette=mannequinPalette[rig.gender];rig.surfaces.forEach(mesh=>(mesh.material as THREE.MeshStandardMaterial).color.set(palette.surface));Object.values(rig.joints).forEach(mesh=>paintJoint(rig,mesh))};
    const setActive=(index:number)=>{if(index<0||index>=characters.length)return;activeIndex=index;characters.forEach(refreshAppearance);notifyPeople();reportPose()};
    const restFor=(rig:RigCharacter)=>restPose(rig.gender);
    const boneLength=(rig:RigCharacter,from:string,to:string)=>new THREE.Vector3(...restFor(rig)[to as keyof JointMap]).distanceTo(new THREE.Vector3(...restFor(rig)[from as keyof JointMap]));
    const reportPose=()=>{const rig=activeRig();if(!rig)return;onPoseChangeRef.current?.(Object.fromEntries(Object.entries(rig.joints).map(([name,mesh])=>[name,[mesh.position.x,mesh.position.y,mesh.position.z] as Point])) as JointMap)};
    const updateVisuals=(rig:RigCharacter)=>{
      const widthScale=rig.gender==="male"?1.08:.94;
      rig.bones.forEach(mesh=>{const from=mesh.userData.from as string,to=mesh.userData.to as string,a=rig.joints[from].position,b=rig.joints[to].position;const limb=/shoulder|elbow|wrist|hip|knee|ankle/.test(from+to);setCylinder(mesh,a,b,limb?widthScale:1)});
      const headAxis=rig.joints.head.position.clone().sub(rig.joints.neck.position),torsoAxis=rig.joints.chest.position.clone().sub(rig.joints.pelvis.position);if(headAxis.lengthSq()<1e-8)headAxis.set(0,1,0);if(torsoAxis.lengthSq()<1e-8)torsoAxis.set(0,1,0);headAxis.normalize();torsoAxis.normalize();rig.head.position.copy(rig.joints.head.position).addScaledVector(headAxis,.04);rig.head.scale.set(rig.gender==="male"?1.04:.96,1.16,1);rig.head.quaternion.setFromUnitVectors(up,headAxis);
      setCylinder(rig.neckBody,rig.joints.neck.position,rig.joints.head.position,.96);
      setCylinder(rig.torsoUpper,rig.joints.chest.position,rig.joints.neck.position,rig.gender==="male"?1.1:.94);
      setCylinder(rig.torsoLower,rig.joints.pelvis.position,rig.joints.chest.position,rig.gender==="male"?1.03:.91);
      rig.pelvisBody.position.copy(rig.joints.pelvis.position).add(rig.joints.hipL.position).add(rig.joints.hipR.position).multiplyScalar(1/3);rig.pelvisBody.scale.set(rig.gender==="male"?.98:1.12,rig.gender==="male"?.62:.68,.78);rig.pelvisBody.quaternion.setFromUnitVectors(up,torsoAxis);
      ["wristL","wristR"].forEach((name,index)=>{const side=name.endsWith("L")?"L":"R",elbow=rig.joints[`elbow${side}`].position,wrist=rig.joints[name].position,direction=wrist.clone().sub(elbow).normalize();rig.hands[index].position.copy(wrist).addScaledVector(direction,.1);rig.hands[index].quaternion.setFromUnitVectors(up,direction)});
      ["ankleL","ankleR"].forEach((name,index)=>{const ankle=rig.joints[name].position,knee=rig.joints[`knee${name.endsWith("L")?"L":"R"}`].position,legUp=knee.clone().sub(ankle).normalize(),bodyForward=bodyBasis(rig).forward,forward=bodyForward.addScaledVector(legUp,-bodyForward.dot(legUp));if(forward.lengthSq()<1e-8)forward.set(0,0,1);forward.normalize();rig.feet[index].position.copy(ankle).addScaledVector(forward,.14).addScaledVector(legUp,-.07);rig.feet[index].quaternion.setFromUnitVectors(up,forward)});
      rig.hitTargets.forEach(target=>target.position.copy(rig.joints[target.userData.joint].position));
    };
    const applyView=(view:RigView)=>{currentView=view;const distance=characters.length===1?10.6:12.2+characters.length*.8;const positions:Record<RigView,[number,number,number]>={front:[0,.7,distance],back:[0,.7,-distance],left:[-distance,.7,0],right:[distance,.7,0],top:[0,distance,.15]};camera.position.set(...positions[view]);camera.up.set(0,view==="top"?0:1,view==="top"?-1:0);controls.target.set(0,.3,0);controls.update()};
    const layout=()=>{const spacing=2.65;characters.forEach((rig,index)=>rig.group.position.x=(index-(characters.length-1)/2)*spacing);controls.maxDistance=21;applyView(currentView);notifyPeople()};
    const createCharacter=(gender:PoseGender)=>{
      const group=new THREE.Group();scene.add(group);const joints:Record<string,THREE.Mesh>={},hitTargets:THREE.Mesh[]=[],pose=restPose(gender),rigIndex=characters.length;
      for(const name of JOINT_NAMES){const radius=name==="head"?.13:/shoulder|hip/.test(name)?.12:/elbow|knee/.test(name)?.115:.095,mesh=new THREE.Mesh(new THREE.SphereGeometry(radius,22,18),handleMaterial(gender));mesh.position.set(...pose[name]);mesh.userData.joint=name;mesh.userData.rig=rigIndex;mesh.renderOrder=9;group.add(mesh);joints[name]=mesh;const hitRadius=name==="head"?.34:/chest|pelvis/.test(name)?.26:/shoulder|hip/.test(name)?.24:.21,hit=new THREE.Mesh(new THREE.SphereGeometry(hitRadius,12,10),hitMaterial());hit.position.copy(mesh.position);hit.userData.joint=name;hit.userData.rig=rigIndex;hit.renderOrder=10;group.add(hit);hitTargets.push(hit)}
      const bones=bonePairs.filter(([from,to])=>![["head","neck"],["neck","chest"],["chest","pelvis"]].some(pair=>pair[0]===from&&pair[1]===to)).map(([from,to])=>{const upperLeg=/hip.*knee/.test(from+to),lowerLeg=/knee.*ankle/.test(from+to),upperArm=/shoulder.*elbow/.test(from+to),lowerArm=/elbow.*wrist/.test(from+to),top=upperLeg?.2:lowerLeg?.155:upperArm?.145:lowerArm?.115:.12,bottom=upperLeg?.165:lowerLeg?.115:upperArm?.118:lowerArm?.085:.1,mesh=new THREE.Mesh(new THREE.CylinderGeometry(top,bottom,1,24,1),surfaceMaterial(gender));mesh.userData.from=from;mesh.userData.to=to;mesh.castShadow=true;group.add(mesh);return mesh});
      const head=new THREE.Mesh(new THREE.SphereGeometry(.34,34,26),surfaceMaterial(gender));head.castShadow=true;group.add(head);
      const neckBody=new THREE.Mesh(new THREE.CylinderGeometry(.14,.15,1,24),surfaceMaterial(gender));neckBody.castShadow=true;group.add(neckBody);
      const torsoUpper=new THREE.Mesh(new THREE.CylinderGeometry(.28,.48,1,30),surfaceMaterial(gender));torsoUpper.castShadow=true;group.add(torsoUpper);
      const torsoLower=new THREE.Mesh(new THREE.CylinderGeometry(.37,.3,1,30),surfaceMaterial(gender));torsoLower.castShadow=true;group.add(torsoLower);
      const pelvisBody=new THREE.Mesh(new THREE.SphereGeometry(.43,30,22),surfaceMaterial(gender));pelvisBody.castShadow=true;group.add(pelvisBody);
      const hands=[0,1].map(()=>{const mesh=new THREE.Mesh(new THREE.CapsuleGeometry(.09,.2,6,16),surfaceMaterial(gender));mesh.scale.set(.82,1,.68);mesh.castShadow=true;group.add(mesh);return mesh});
      const feet=[0,1].map(()=>{const mesh=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.3,6,18),surfaceMaterial(gender));mesh.scale.set(1.05,1,.78);mesh.castShadow=true;group.add(mesh);return mesh});
      const surfaces=[...bones,head,neckBody,torsoUpper,torsoLower,pelvisBody,...hands,...feet];
      const rig:RigCharacter={gender,group,joints,hitTargets,bones,head,neckBody,torsoUpper,torsoLower,pelvisBody,hands,feet,surfaces};characters.push(rig);updateVisuals(rig);layout();setActive(characters.length-1);return rig;
    };
    const bodyBasis=(rig:RigCharacter)=>{const vertical=rig.joints.neck.position.clone().sub(rig.joints.pelvis.position),lateral=rig.joints.shoulderR.position.clone().sub(rig.joints.shoulderL.position);if(vertical.lengthSq()<1e-8)vertical.set(0,1,0);if(lateral.lengthSq()<1e-8)lateral.set(1,0,0);vertical.normalize();lateral.normalize();let forward=lateral.clone().cross(vertical);if(forward.lengthSq()<1e-8)forward=Math.abs(vertical.z)<.9?new THREE.Vector3(0,0,1):new THREE.Vector3(1,0,0);forward.normalize();lateral.copy(vertical).cross(forward).normalize();return{vertical,lateral,forward}};
    const mapBodyDirection=(rig:RigCharacter,canonical:THREE.Vector3)=>{const basis=bodyBasis(rig);return basis.lateral.multiplyScalar(canonical.x).addScaledVector(basis.vertical,canonical.y).addScaledVector(basis.forward,canonical.z).normalize()};
    const preferredDirection=(rig:RigCharacter,name:string)=>{const rest=restFor(rig),parent=parentByJoint[name],canonical=new THREE.Vector3(...rest[name as keyof JointMap]).sub(new THREE.Vector3(...rest[parent as keyof JointMap])).normalize();return mapBodyDirection(rig,canonical)};
    const preferredSpanDirection=(rig:RigCharacter,from:string,to:string)=>{const rest=restFor(rig),canonical=new THREE.Vector3(...rest[to as keyof JointMap]).sub(new THREE.Vector3(...rest[from as keyof JointMap])).normalize();return mapBodyDirection(rig,canonical)};
    const limitDirection=(direction:THREE.Vector3,preferred:THREE.Vector3,maxDegrees:number)=>{const next=direction.clone().normalize(),base=preferred.clone().normalize(),max=THREE.MathUtils.degToRad(maxDegrees);if(base.angleTo(next)<=max)return next;let axis=base.clone().cross(next);if(axis.lengthSq()<1e-8)axis=base.clone().cross(Math.abs(base.y)<.9?new THREE.Vector3(0,1,0):new THREE.Vector3(1,0,0));return base.applyAxisAngle(axis.normalize(),max).normalize()};
    const project=(rig:RigCharacter,name:string,target:THREE.Vector3,limited=false)=>{const parent=parentByJoint[name],origin=rig.joints[parent].position;let direction=target.clone().sub(origin);if(direction.lengthSq()<1e-8)direction=preferredDirection(rig,name);if(limited&&coneLimits[name])direction=limitDirection(direction,preferredDirection(rig,name),coneLimits[name]);return origin.clone().add(direction.normalize().multiplyScalar(boneLength(rig,parent,name)))};
    const solveTwoBone=(rig:RigCharacter,rootName:string,middleName:string,endName:string,target:THREE.Vector3,maxBend:number,middleGuide?:THREE.Vector3)=>{const root=rig.joints[rootName].position,middle=rig.joints[middleName].position,upper=boneLength(rig,rootName,middleName),lower=boneLength(rig,middleName,endName);const axis=target.clone().sub(root);if(axis.lengthSq()<1e-8)axis.set(0,-1,0);axis.normalize();const minReach=Math.sqrt(Math.max(.0001,upper*upper+lower*lower+2*upper*lower*Math.cos(THREE.MathUtils.degToRad(maxBend))));const distance=THREE.MathUtils.clamp(target.distanceTo(root),minReach,upper+lower-.004);const end=root.clone().addScaledVector(axis,distance);let bend=(middleGuide||middle).clone().sub(root).addScaledVector(axis,-middle.clone().sub(root).dot(axis));if(bend.lengthSq()<1e-8){bend=axis.clone().cross(new THREE.Vector3(0,0,1));if(bend.lengthSq()<1e-8)bend=axis.clone().cross(new THREE.Vector3(0,1,0))}bend.normalize();const along=(upper*upper-lower*lower+distance*distance)/(2*distance),height=Math.sqrt(Math.max(0,upper*upper-along*along));rig.joints[middleName].position.copy(root).addScaledVector(axis,along).addScaledVector(bend,height);rig.joints[endName].position.copy(end)};
    const conformToTargets=(rig:RigCharacter,targets:Record<string,THREE.Vector3>,allowFullTorso=false)=>{rig.joints.pelvis.position.copy(targets.pelvis);for(const name of ["chest","neck","head","shoulderL","shoulderR","hipL","hipR"])rig.joints[name].position.copy(project(rig,name,targets[name],!allowFullTorso&&(name==="chest"||name==="neck"||name==="head")));solveTwoBone(rig,"shoulderL","elbowL","wristL",targets.wristL,158,targets.elbowL);solveTwoBone(rig,"shoulderR","elbowR","wristR",targets.wristR,158,targets.elbowR);solveTwoBone(rig,"hipL","kneeL","ankleL",targets.ankleL,152,targets.kneeL);solveTwoBone(rig,"hipR","kneeR","ankleR",targets.ankleR,152,targets.kneeR);updateVisuals(rig);reportPose()};
    const currentTargets=(rig:RigCharacter)=>Object.fromEntries(Object.entries(rig.joints).map(([name,mesh])=>[name,mesh.position.clone()])) as Record<string,THREE.Vector3>;
    const applyPose=(rig:RigCharacter,preset:PosePreset)=>{const pose=restPose(rig.gender);Object.entries(posePresets[preset]).forEach(([name,point])=>{if(point)pose[name as keyof JointMap]=[...point] as Point});const targets=Object.fromEntries(Object.entries(pose).map(([name,point])=>[name,new THREE.Vector3(...point)]));conformToTargets(rig,targets,/supine|sideLying|prone/.test(preset))};
    const moveDescendants=(rig:RigCharacter,name:string,delta:THREE.Vector3)=>{for(const child of childrenByJoint[name]||[]){rig.joints[child].position.add(delta);moveDescendants(rig,child,delta)}};
    const realisticDrag=(rig:RigCharacter,name:string,target:THREE.Vector3)=>{if(name==="pelvis"){const ankleL=rig.joints.ankleL.position.clone(),ankleR=rig.joints.ankleR.position.clone(),kneeL=rig.joints.kneeL.position.clone(),kneeR=rig.joints.kneeR.position.clone(),next=new THREE.Vector3(THREE.MathUtils.clamp(target.x,-1.6,1.6),THREE.MathUtils.clamp(target.y,-1.82,1.55),THREE.MathUtils.clamp(target.z,-1.4,1.4)),delta=next.clone().sub(rig.joints.pelvis.position);for(const joint of ["pelvis","chest","neck","head","shoulderL","elbowL","wristL","shoulderR","elbowR","wristR","hipL","hipR"])rig.joints[joint].position.add(delta);solveTwoBone(rig,"hipL","kneeL","ankleL",ankleL,152,kneeL);solveTwoBone(rig,"hipR","kneeR","ankleR",ankleR,152,kneeR);return}const chain=chainEnds[name];if(chain){const root=rig.joints[chain[0]].position,direction=target.clone().sub(root),distance=direction.length();if(distance>1e-8)target=root.clone().add(limitDirection(direction,preferredSpanDirection(rig,chain[0],name),chainSwingLimits[name]).multiplyScalar(distance));solveTwoBone(rig,chain[0],chain[1],name,target,chain[2]);return}const middle=middleJoints[name];if(middle){const previous=rig.joints[name].position.clone(),next=project(rig,name,target,true);rig.joints[name].position.copy(next);rig.joints[middle[0]].position.add(next.clone().sub(previous));return}const previous=rig.joints[name].position.clone(),next=project(rig,name,target,true);rig.joints[name].position.copy(next);moveDescendants(rig,name,next.clone().sub(previous))};
    const applyJointMap=(pose:JointMap)=>{const rig=activeRig();if(!rig||!JOINT_NAMES.every(name=>Array.isArray(pose[name])&&pose[name].length===3&&pose[name].every(Number.isFinite)))return;const source=Object.fromEntries(JOINT_NAMES.map(name=>[name,new THREE.Vector3(...pose[name])])) as Record<string,THREE.Vector3>;const ys=Object.values(source).map(point=>point.y),height=Math.max(...ys)-Math.min(...ys);if(height<.45)return;const scale=THREE.MathUtils.clamp(4.75/height,.75,4.4),pelvis=source.pelvis.clone();const targets=Object.fromEntries(JOINT_NAMES.map(name=>[name,source[name].clone().sub(pelvis).multiplyScalar(scale)])) as Record<string,THREE.Vector3>;const footY=Math.min(targets.ankleL.y,targets.ankleR.y);Object.values(targets).forEach(point=>point.y+=-2.05-footY);conformToTargets(rig,targets,true)};
    const mirror=()=>{const rig=activeRig();if(!rig)return;const snapshot=currentTargets(rig);for(const [name,mesh] of Object.entries(rig.joints)){const paired=name.endsWith("L")?`${name.slice(0,-1)}R`:name.endsWith("R")?`${name.slice(0,-1)}L`:name,source=snapshot[paired]||snapshot[name];mesh.position.set(-source.x,source.y,source.z)}conformToTargets(rig,currentTargets(rig),true)};
    const disposeGroup=(group:THREE.Group)=>{group.traverse(object=>{if(object instanceof THREE.Mesh){object.geometry.dispose();const materials=Array.isArray(object.material)?object.material:[object.material];materials.forEach(material=>material.dispose())}});scene.remove(group)};
    createCharacter("female");

    const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),dragPlane=new THREE.Plane(),hitPoint=new THREE.Vector3(),dragStartPosition=new THREE.Vector3();let selected:THREE.Mesh|null=null,selectedRig:RigCharacter|null=null,hovered:THREE.Mesh|null=null,hoveredRig:RigCharacter|null=null,dragStartX=0,dragStartY=0;
    const setPointer=(event:globalThis.PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.x=((event.clientX-rect.left)/rect.width)*2-1;pointer.y=-((event.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera)};
    const hitJoint=()=>{const hit=raycaster.intersectObjects(characters.flatMap(rig=>rig.hitTargets),false)[0];if(!hit)return null;const rig=characters[hit.object.userData.rig as number],joint=rig?.joints[hit.object.userData.joint as string];return rig&&joint?{rig,joint}:null};
    const clearHover=()=>{if(hovered&&hoveredRig&&hovered!==selected)paintJoint(hoveredRig,hovered);hovered=null;hoveredRig=null};
    const onPointerDown=(event:globalThis.PointerEvent)=>{setPointer(event);const hit=hitJoint();if(!hit)return;clearHover();selected=hit.joint;selectedRig=hit.rig;const rigIndex=characters.indexOf(selectedRig);if(rigIndex<0)return;setActive(rigIndex);paintJoint(selectedRig,selected,"selected");dragStartX=event.clientX;dragStartY=event.clientY;dragStartPosition.copy(selected.position);controls.enabled=false;renderer.domElement.setPointerCapture(event.pointerId);const worldPoint=selected.getWorldPosition(new THREE.Vector3()),normal=camera.getWorldDirection(new THREE.Vector3());dragPlane.setFromNormalAndCoplanarPoint(normal,worldPoint);renderer.domElement.style.cursor="grabbing"};
    const onPointerMove=(event:globalThis.PointerEvent)=>{setPointer(event);if(!selected||!selectedRig){const hit=hitJoint();if(hit?.joint!==hovered){clearHover();if(hit){hovered=hit.joint;hoveredRig=hit.rig;paintJoint(hit.rig,hit.joint,"hover")}}renderer.domElement.style.cursor=hit?"pointer":"grab";return}let local:THREE.Vector3|null=null;if(dragAxis==="screen"){if(raycaster.ray.intersectPlane(dragPlane,hitPoint))local=selectedRig.group.worldToLocal(hitPoint.clone())}else{const sensitivity=camera.position.distanceTo(selected.getWorldPosition(new THREE.Vector3()))*.0022,dx=(event.clientX-dragStartX)*sensitivity,dy=(event.clientY-dragStartY)*sensitivity;local=dragStartPosition.clone();if(dragAxis==="x")local.x+=dx;if(dragAxis==="y")local.y-=dy;if(dragAxis==="z")local.z+=dx}if(local){const target=new THREE.Vector3(THREE.MathUtils.clamp(local.x,-3.4,3.4),THREE.MathUtils.clamp(local.y,-2.25,3.75),THREE.MathUtils.clamp(local.z,-3.4,3.4));if(realisticRef.current)realisticDrag(selectedRig,selected.userData.joint,target);else selected.position.copy(target);updateVisuals(selectedRig)}};
    const onPointerUp=(event:globalThis.PointerEvent)=>{if(!selected)return;if(selectedRig)paintJoint(selectedRig,selected);selected=null;selectedRig=null;controls.enabled=true;renderer.domElement.style.cursor="grab";if(renderer.domElement.hasPointerCapture(event.pointerId))renderer.domElement.releasePointerCapture(event.pointerId);reportPose()};
    const onPointerLeave=()=>{if(!selected){clearHover();renderer.domElement.style.cursor="grab"}};
    renderer.domElement.addEventListener("pointerdown",onPointerDown);renderer.domElement.addEventListener("pointermove",onPointerMove);renderer.domElement.addEventListener("pointerup",onPointerUp);renderer.domElement.addEventListener("pointercancel",onPointerUp);renderer.domElement.addEventListener("pointerleave",onPointerLeave);renderer.domElement.style.touchAction="none";renderer.domElement.style.cursor="grab";
    const resize=()=>{const width=Math.max(1,mount.clientWidth),height=Math.max(1,mount.clientHeight);renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix()};resize();const observer=new ResizeObserver(resize);observer.observe(mount);
    let frame=0,stageVisible=true,pageVisible=document.visibilityState!=="hidden";const intersectionObserver=new IntersectionObserver(entries=>{stageVisible=entries[0]?.isIntersecting??true},{rootMargin:"100px"});intersectionObserver.observe(mount);const onVisibility=()=>{pageVisible=document.visibilityState!=="hidden"};document.addEventListener("visibilitychange",onVisibility);const animate=()=>{frame=requestAnimationFrame(animate);if(!stageVisible||!pageVisible)return;controls.update();renderer.render(scene,camera)};animate();
    apiRef.current={capture:()=>{renderer.render(scene,camera);return renderer.domElement.toDataURL("image/png")},reset:()=>{const rig=activeRig();if(rig)applyPose(rig,"neutral")},applyPreset:preset=>{const rig=activeRig();if(rig)applyPose(rig,preset)},applyJointMap,setRealistic:enabled=>{realisticRef.current=enabled;if(enabled){const rig=activeRig();if(rig)conformToTargets(rig,currentTargets(rig))}},mirror,addPerson:gender=>{if(characters.length<3)createCharacter(gender)},removePerson:()=>{if(characters.length<=1)return;disposeGroup(characters[activeIndex].group);characters.splice(activeIndex,1);characters.forEach((rig,index)=>{Object.values(rig.joints).forEach(mesh=>mesh.userData.rig=index);rig.hitTargets.forEach(mesh=>mesh.userData.rig=index)});activeIndex=Math.min(activeIndex,characters.length-1);layout();setActive(activeIndex)},selectPerson:setActive,setBodyType:gender=>{const rig=activeRig();if(!rig||rig.gender===gender)return;rig.gender=gender;refreshAppearance(rig);applyPose(rig,"neutral");setActive(activeIndex)},setView:applyView,setDragAxis:axis=>{dragAxis=axis},setFacing:facing=>{const rig=activeRig();if(!rig)return;const rotations:Record<CharacterFacing,number>={front:0,left:Math.PI/2,right:-Math.PI/2,back:Math.PI};rig.group.rotation.y=rotations[facing];reportPose()}};
    return()=>{cancelAnimationFrame(frame);observer.disconnect();intersectionObserver.disconnect();document.removeEventListener("visibilitychange",onVisibility);renderer.domElement.removeEventListener("pointerdown",onPointerDown);renderer.domElement.removeEventListener("pointermove",onPointerMove);renderer.domElement.removeEventListener("pointerup",onPointerUp);renderer.domElement.removeEventListener("pointercancel",onPointerUp);renderer.domElement.removeEventListener("pointerleave",onPointerLeave);controls.dispose();characters.forEach(rig=>disposeGroup(rig.group));renderer.dispose();renderer.domElement.remove()};
  },[]);
  return <div ref={mountRef} className="pose-rig-canvas" role="img" aria-label={ariaLabel}/>;
});

PoseRig.displayName="PoseRig";
export default PoseRig;
