"use client";

import { Component, lazy, Suspense, useEffect, useRef, useState, type CSSProperties, type DragEvent, type PointerEvent, type ReactNode } from "react";
import { MODEL_PROVIDERS, detectModelBrand, providerById } from "./model-providers";
import { IMAGE_GENERATION_PROVIDERS, imageGenerationProviderById, imagePromptFamily } from "./image-generation-providers";
import { LANGUAGE_OPTIONS, optionLabel, preferredLocale, referenceRoleLabel, translate, type Locale } from "./i18n";
import type { CharacterFacing, DragAxis, PoseRigHandle, RigView } from "./PoseRig";
import { POSE_PRESET_LIBRARY, type JointMap, type PoseCategory, type PoseGender, type PosePreset } from "./pose-presets";
import ComfyConnectionSettings from "./ComfyConnectionSettings";
import WelcomeModuleVisual from "./WelcomeModuleVisual";

const PoseRig=lazy(()=>import("./PoseRig"));
const ComfyWorkflowStudio=lazy(()=>import("./ComfyWorkflowStudio"));

class PoseErrorBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{
  state={failed:false};
  static getDerivedStateFromError(){return{failed:true}}
  componentDidCatch(error:unknown){console.error("Pose rig failed to initialize",error)}
  render(){return this.state.failed?this.props.fallback:this.props.children}
}

type Shot = { id:number; time:string; shot:string; visual:string; camera:string; audio:string; prompt:string };
type Story = { title:string; logline:string; hook:string; direction:string; structure:[string,string][]; structureTimes?:string[]; visualAnalysis?:string };
type Theme = "light"|"dark"|"system";
type Backdrop = "none"|"globe"|"mind";
type WorkspaceMode = "home"|"story"|"image"|"generate"|"pose";
type ImageWorkflow = "text-to-image"|"image-to-image"|"multi-reference";
type User = { displayName:string; email:string; userId:string } | null;
type ImageInfo = { src:string; name:string; width:number; height:number; orientation:string; color:string; tone:string; size:string };
type PromptReference = ImageInfo & { id:string; role:string; note:string };
type ModelOption = { id:string; name:string; vision:boolean };
type AccountModelConfig = { providerId:string; apiBaseUrl:string; model:string; hasApiKey:boolean; updatedAt:string };
type AccountImageConfig = { providerId:string; apiBaseUrl:string; model:string; hasApiKey:boolean; updatedAt:string };
type GeneratedImage = { src:string; model:string; provider:string };
type PipelineSource = { stage:"story"|"prompt"|"pose"; title:string; detail:string; shotId?:number };
const emptyStory:Story={title:"",logline:"",hook:"",direction:"",structure:[]};

function sameApiEndpoint(a:string,b:string){return a.trim().replace(/\/+$/,"").toLowerCase()===b.trim().replace(/\/+$/,"").toLowerCase()}

function moveModuleCard(event:PointerEvent<HTMLButtonElement>){if(event.pointerType==="touch")return;const card=event.currentTarget;const rect=card.getBoundingClientRect();const x=(event.clientX-rect.left)/rect.width-.5;const y=(event.clientY-rect.top)/rect.height-.5;card.style.setProperty("--card-rx",`${(-y*3.2).toFixed(2)}deg`);card.style.setProperty("--card-ry",`${(x*4.2).toFixed(2)}deg`);card.style.setProperty("--visual-x",`${(x*9).toFixed(1)}px`);card.style.setProperty("--visual-y",`${(y*7).toFixed(1)}px`)}
function resetModuleCard(event:PointerEvent<HTMLButtonElement>){const card=event.currentTarget;card.style.setProperty("--card-rx","0deg");card.style.setProperty("--card-ry","0deg");card.style.setProperty("--visual-x","0px");card.style.setProperty("--visual-y","0px")}

const genres = ["悬疑惊悚", "科幻未来", "治愈情感", "古风奇幻", "都市反转", "搞笑脑洞"];
const styles = ["电影写实", "日系动漫", "3D 动画", "赛博朋克", "水墨国风", "复古胶片"];
const platforms = ["抖音 / TikTok", "小红书", "B站", "YouTube Shorts", "横屏短片"];
const models = ["通用视频模型", "Seedance 2.0", "Sora 2", "Veo 3.1", "Kling 3.0", "Runway Gen-4.5"];
const imageModels = ["ChatGPT Image", "Midjourney", "Seedream", "Flux", "Runway Gen-4 Image"];
const imagePurposes = ["电影关键帧", "角色设定图", "场景概念图", "封面海报", "产品视觉"];
const imageAspects = ["16:9 横屏", "9:16 竖屏", "1:1 方形", "4:3 经典", "21:9 超宽"];
const imageStyles = [...styles, "商业摄影", "概念艺术", "极简海报"];
const imageWorkflows:ImageWorkflow[]=["text-to-image","image-to-image","multi-reference"];
const referenceRoles=["subject","character","scene","style","composition","prop","color"];
const poseCategories:PoseCategory[]=["standing","action","seated","stretch","lying"];
const poseCategoryKeys:Record<PoseCategory,string>={standing:"poseCategoryStanding",action:"poseCategoryAction",seated:"poseCategorySeated",stretch:"poseCategoryStretch",lying:"poseCategoryLying"};
const rigViews:RigView[]=["front","left","right","back","top"];
const rigFacings:CharacterFacing[]=["front","left","right","back"];
const rigDragAxes:DragAxis[]=["screen","x","y","z"];
const rigViewKeys:Record<RigView,string>={front:"poseViewFront",left:"poseViewLeft",right:"poseViewRight",back:"poseViewBack",top:"poseViewTop"};
const rigFacingKeys:Record<CharacterFacing,string>={front:"poseFacingFront",left:"poseFacingLeft",right:"poseFacingRight",back:"poseFacingBack"};
const rigAxisKeys:Record<DragAxis,string>={screen:"poseAxisScreen",x:"poseAxisX",y:"poseAxisY",z:"poseAxisZ"};
const sampleImageConcepts:Record<Locale,string>={"zh-CN":"一名女孩站在雨夜便利店门口，掌心的古董怀表正在倒转，玻璃倒影中出现失踪多年的亲人。","zh-TW":"一名女孩站在雨夜便利商店門口，掌心的古董懷錶正在倒轉，玻璃倒影中出現失蹤多年的親人。",ja:"雨の夜、コンビニの入口に立つ少女。手のひらのアンティーク懐中時計が逆回転し、ガラスの反射には長年行方不明の家族が現れる。",en:"A girl stands outside a convenience store on a rainy night. An antique pocket watch reverses in her palm, while the glass reflection reveals a relative missing for years."};

function inspectImageFile(file:File){return new Promise<ImageInfo>((resolve,reject)=>{if(!file.type.startsWith("image/")){reject(new Error("IMAGE_TYPE"));return}if(file.size>10*1024*1024){reject(new Error("IMAGE_SIZE"));return}const reader=new FileReader();reader.onerror=()=>reject(new Error("IMAGE_READ"));reader.onload=()=>{const originalSrc=String(reader.result);const img=new Image();img.onerror=()=>reject(new Error("IMAGE_READ"));img.onload=()=>{const sample=document.createElement("canvas");sample.width=40;sample.height=40;const sampleContext=sample.getContext("2d");if(!sampleContext){reject(new Error("IMAGE_READ"));return}sampleContext.drawImage(img,0,0,40,40);const px=sampleContext.getImageData(0,0,40,40).data;let red=0,green=0,blue=0,count=0;for(let i=0;i<px.length;i+=16){red+=px[i];green+=px[i+1];blue+=px[i+2];count++}red=Math.round(red/count);green=Math.round(green/count);blue=Math.round(blue/count);const brightness=Math.round(.299*red+.587*green+.114*blue);const orientation=img.width>img.height*1.15?"landscape":img.height>img.width*1.15?"portrait":"square";const scale=Math.min(1,1600/Math.max(img.width,img.height));const optimized=document.createElement("canvas");optimized.width=Math.max(1,Math.round(img.width*scale));optimized.height=Math.max(1,Math.round(img.height*scale));const outputContext=optimized.getContext("2d");if(!outputContext){reject(new Error("IMAGE_READ"));return}outputContext.drawImage(img,0,0,optimized.width,optimized.height);const src=optimized.toDataURL("image/jpeg",.84)||originalSrc;resolve({src,name:file.name,width:img.width,height:img.height,orientation,color:`RGB(${red}, ${green}, ${blue})`,tone:brightness>175?"high-key":brightness<80?"low-key":"balanced",size:`${(file.size/1024/1024).toFixed(1)}MB`})};img.src=originalSrc};reader.readAsDataURL(file)})}

function BackdropVisual({mode}:{mode:Backdrop}){
  if(mode==="globe") return <div className="scene backdrop-scene orbital-backdrop" aria-hidden="true">
    <div className="orbital-aurora"/><div className="orbital-scan"/>
    {Array.from({length:24},(_,index)=><i className="orbital-star" key={index} style={{"--star-x":`${7+(index*37)%89}%`,"--star-y":`${5+(index*53)%88}%`,"--star-delay":`${-index*.31}s`} as CSSProperties}/>)}
    <div className="orbital-globe">
      <span className="globe-core"/><i className="globe-meridian meridian-one"/><i className="globe-meridian meridian-two"/><i className="globe-meridian meridian-three"/><i className="globe-latitude latitude-one"/><i className="globe-latitude latitude-two"/><i className="globe-latitude latitude-three"/>
      <span className="orbital-ring ring-alpha"><i/></span><span className="orbital-ring ring-beta"><i/></span><span className="orbital-ring ring-gamma"><i/></span>
    </div>
    <div className="orbit-readout"><span>ORBITAL STORY MAP</span><b>LIVE POSITION</b><em>35.68° N / 139.76° E</em></div>
    <div className="scene-label">WORLD BUILDING FIELD · SYNCHRONIZED</div>
  </div>;
  if(mode==="mind"){
    const neuralNodes=[
      ["11%","24%","-.4s"],["22%","13%","-1.2s"],["35%","27%","-2s"],["46%","9%","-2.8s"],["61%","18%","-3.6s"],["75%","10%","-4.4s"],["88%","27%","-5.2s"],
      ["16%","48%","-1.8s"],["31%","43%","-2.6s"],["69%","39%","-3.4s"],["84%","51%","-4.2s"],["95%","43%","-5s"],
      ["8%","71%","-3s"],["24%","78%","-3.8s"],["39%","66%","-4.6s"],["53%","84%","-5.4s"],["66%","69%","-6.2s"],["80%","82%","-7s"],["93%","68%","-7.8s"]
    ];
    const neuralLinks=["-164deg","-143deg","-121deg","-98deg","-73deg","-48deg","-25deg","-8deg","17deg","38deg","61deg","83deg","107deg","132deg","154deg","178deg"];
    return <div className="scene backdrop-scene neural-backdrop" aria-hidden="true">
      <div className="neural-aura"/><div className="neural-ripple ripple-one"/><div className="neural-ripple ripple-two"/><div className="neural-ripple ripple-three"/>
      <div className="neural-field">
        {neuralLinks.map((angle,index)=><span className="neural-link" key={angle} style={{"--link-angle":angle,"--link-length":`${25+(index%5)*7}vw`,"--link-delay":`${-index*.41}s`} as CSSProperties}><i/></span>)}
        {neuralNodes.map(([x,y,delay],index)=><i className="neural-node" key={`${x}-${y}`} style={{"--node-x":x,"--node-y":y,"--node-delay":delay,"--node-size":`${index%4===0?13:index%3===0?9:6}px`} as CSSProperties}/>) }
        <div className="neural-core"><i/><span>IDEA</span><b>∞</b></div>
        <span className="neural-tag tag-character">CHARACTER</span><span className="neural-tag tag-conflict">CONFLICT</span><span className="neural-tag tag-emotion">EMOTION</span><span className="neural-tag tag-world">WORLD</span><span className="neural-tag tag-turn">TURN</span>
      </div>
      <div className="scene-label">NARRATIVE NEURAL FIELD · 19 ACTIVE THOUGHTS</div>
    </div>;
  }
  return <div className="scene backdrop-scene clean-backdrop" aria-hidden="true">
    <div className="clean-spotlight"><i/><i/></div><div className="clean-perspective"><i/><i/><i/><i/></div><div className="clean-crosshair"><i/><i/></div>
    <div className="clean-word"><span>FRAME</span><b>FOCUS</b><em>PURE CREATION SPACE</em></div>
    <div className="scene-label">CLEAN CANVAS · DISTRACTION FREE</div>
  </div>;
}

function IdeaField(){
  const branches=[
    {w:"24vw",r:"-52deg",d:"-.4s"},{w:"27vw",r:"-12deg",d:"-2.1s"},{w:"25vw",r:"27deg",d:"-3.8s"},
    {w:"23vw",r:"83deg",d:"-1.2s"},{w:"24vw",r:"137deg",d:"-4.5s"},{w:"31vw",r:"178deg",d:"-2.9s"},
    {w:"27vw",r:"-145deg",d:"-5.2s"},{w:"25vw",r:"-83deg",d:"-1.8s"},{w:"36vw",r:"39deg",d:"-4.1s"},
  ];
  const thoughts=[
    {x:"69%",y:"23%",d:"-.7s"},{x:"82%",y:"37%",d:"-2.8s"},{x:"78%",y:"62%",d:"-4.2s"},
    {x:"58%",y:"78%",d:"-1.5s"},{x:"37%",y:"70%",d:"-3.4s"},{x:"25%",y:"48%",d:"-5s"},
    {x:"33%",y:"25%",d:"-2.2s"},{x:"60%",y:"13%",d:"-4.7s"},{x:"88%",y:"77%",d:"-3.1s"},
  ];
  return <div className="idea-field" aria-hidden="true">
    <div className="idea-radar ring-one"/><div className="idea-radar ring-two"/><div className="idea-radar ring-three"/>
    <div className="idea-origin"><i/></div>
    {branches.map((item,index)=><span className={`idea-branch branch-${index+1}`} key={`branch-${index}`} style={{"--branch-width":item.w,"--branch-angle":item.r,"--branch-delay":item.d} as CSSProperties}><i/><b/></span>)}
    {thoughts.map((item,index)=><span className="thought-node" key={`thought-${index}`} style={{"--node-x":item.x,"--node-y":item.y,"--node-delay":item.d} as CSSProperties}><i/></span>)}
    {Array.from({length:18},(_,index)=><i className="idea-particle" key={`particle-${index}`} style={{"--particle-index":String(index),"--particle-delay":`${-index*.73}s`} as CSSProperties}/>) }
  </div>;
}

export default function Studio({user}:{user:User}){
  const [workspaceMode,setWorkspaceMode]=useState<WorkspaceMode>("home");
  const [workspaceChanging,setWorkspaceChanging]=useState(false);
  const [locale,setLocaleState]=useState<Locale>("zh-CN"); const [languageOpen,setLanguageOpen]=useState(false); const [localeChanging,setLocaleChanging]=useState(false);
  const [activeTab,setActiveTab]=useState<"story"|"shots">("story"); const [idea,setIdea]=useState(""); const [genre,setGenre]=useState(genres[0]); const [style,setStyle]=useState(styles[0]); const [platform,setPlatform]=useState(platforms[0]); const [duration,setDuration]=useState(30); const [model,setModel]=useState(models[0]); const [lock,setLock]=useState(true);
  const [story,setStory]=useState<Story>(emptyStory); const [shots,setShots]=useState<Shot[]>([]); const [generating,setGenerating]=useState(false); const [copied,setCopied]=useState(""); const [notice,setNotice]=useState(""); const [version,setVersion]=useState(0); const [mentorLoading,setMentorLoading]=useState(false); const [mentorSuggestion,setMentorSuggestion]=useState<{hook:string;suggestion:string}|null>(null);
  const [theme,setThemeState]=useState<Theme>("system"); const [themeOpen,setThemeOpen]=useState(false); const [backdrop,setBackdropState]=useState<Backdrop>("none"); const [brandOpen,setBrandOpen]=useState(false); const [profileOpen,setProfileOpen]=useState(false); const [settingsOpen,setSettingsOpen]=useState(false);
  const [image,setImage]=useState<ImageInfo|null>(null); const [imageNotes,setImageNotes]=useState(""); const [uploadError,setUploadError]=useState(""); const fileRef=useRef<HTMLInputElement>(null); const imageFileRef=useRef<HTMLInputElement>(null);
  const [imageConcept,setImageConcept]=useState(sampleImageConcepts["zh-CN"]); const [imagePurpose]=useState(imagePurposes[0]); const [imageStyle,setImageStyle]=useState(imageStyles[0]); const [imageModel]=useState(imageModels[0]); const [imageAspect,setImageAspect]=useState(imageAspects[0]); const [imagePrompt,setImagePrompt]=useState(""); const [imagePromptCore,setImagePromptCore]=useState(""); const [imageGenerating,setImageGenerating]=useState(false); const [imageRendering,setImageRendering]=useState(false); const [imageRenderStatus,setImageRenderStatus]=useState(""); const [generatedImage,setGeneratedImage]=useState<GeneratedImage|null>(null); const [imageWorkflow,setImageWorkflow]=useState<ImageWorkflow>("text-to-image"); const [promptReferences,setPromptReferences]=useState<PromptReference[]>([]); const [imageBriefNotes,setImageBriefNotes]=useState(""); const [referenceError,setReferenceError]=useState(""); const [pipelineSource,setPipelineSource]=useState<PipelineSource|null>(null); const [pipelinePromptReferences]=useState<PromptReference[]>([]); const [pipelineRenderPrompt,setPipelineRenderPrompt]=useState("");
  const [comfySeedPrompt,setComfySeedPrompt]=useState(""); const [comfySeedVersion,setComfySeedVersion]=useState(0);
  const [poseConcept,setPoseConcept]=useState("一名敏捷的未来城市信使，全身角色设计，服装结构清晰，严格匹配骨骼姿态。" ); const [poseStyle,setPoseStyle]=useState(imageStyles[0]); const [poseAspect,setPoseAspect]=useState(imageAspects[1]); const [poseReference,setPoseReference]=useState<PromptReference|null>(null); const [poseResult,setPoseResult]=useState<GeneratedImage|null>(null); const [posePrompt,setPosePrompt]=useState(""); const [poseGenerating,setPoseGenerating]=useState(false); const [poseStatus,setPoseStatus]=useState(""); const [poseRealistic,setPoseRealistic]=useState(true); const [activePosePreset,setActivePosePreset]=useState<PosePreset|"custom">("neutral"); const poseRigRef=useRef<PoseRigHandle>(null); const poseFileRef=useRef<HTMLInputElement>(null);
  const [poseMotionReference,setPoseMotionReference]=useState<ImageInfo|null>(null); const [poseEstimating,setPoseEstimating]=useState(false); const [poseMotionStatus,setPoseMotionStatus]=useState(""); const [poseMotionAnalysis,setPoseMotionAnalysis]=useState(""); const [poseGender,setPoseGender]=useState<PoseGender>("female"); const [poseCategory,setPoseCategory]=useState<PoseCategory>("standing"); const [posePeople,setPosePeople]=useState<PoseGender[]>(["female"]); const [activePosePerson,setActivePosePerson]=useState(0); const [poseView,setPoseView]=useState<RigView>("front"); const [poseFacing,setPoseFacing]=useState<CharacterFacing>("front"); const [poseDragAxis,setPoseDragAxis]=useState<DragAxis>("screen"); const poseMotionFileRef=useRef<HTMLInputElement>(null);
  const [providerId,setProviderId]=useState("openrouter"); const [apiBaseUrl,setApiBaseUrl]=useState(providerById("openrouter").baseUrl); const [apiKey,setApiKey]=useState(""); const [generationModel,setGenerationModel]=useState(""); const [availableModels,setAvailableModels]=useState<ModelOption[]>([]); const [modelSearch,setModelSearch]=useState(""); const [detectingModels,setDetectingModels]=useState(false); const [configStatus,setConfigStatus]=useState("正在读取账户配置…"); const [showApiKey,setShowApiKey]=useState(false); const [accountConfig,setAccountConfig]=useState<AccountModelConfig|null>(null);
  const [imageProviderId,setImageProviderId]=useState("runway"); const [imageApiBaseUrl,setImageApiBaseUrl]=useState(imageGenerationProviderById("runway").baseUrl); const [imageApiKey,setImageApiKey]=useState(""); const [imageGenerationModel,setImageGenerationModel]=useState(imageGenerationProviderById("runway").models[0].id); const [showImageApiKey,setShowImageApiKey]=useState(false); const [imageConfigStatus,setImageConfigStatus]=useState("正在读取图片引擎…"); const [accountImageConfig,setAccountImageConfig]=useState<AccountImageConfig|null>(null);
  const savedKeyMatches=Boolean(accountConfig?.hasApiKey&&accountConfig.providerId===providerId&&sameApiEndpoint(accountConfig.apiBaseUrl,apiBaseUrl));
  const savedImageKeyMatches=Boolean(accountImageConfig?.hasApiKey&&accountImageConfig.providerId===imageProviderId&&sameApiEndpoint(accountImageConfig.apiBaseUrl,imageApiBaseUrl));
  const t=(key:string,values:Record<string,string|number>={})=>translate(locale,key,values);
  const comfyCard=locale==="zh-CN"?{desc:"直接使用官方 ComfyUI 完整画布、真实节点、模型、Manager 与扩展。",enter:"进入真实 ComfyUI",sendStory:"将故事主视觉送入 ComfyUI",sendShot:"将本镜送入 ComfyUI"}:locale==="zh-TW"?{desc:"直接使用官方 ComfyUI 完整畫布、真實節點、模型、Manager 與擴充。",enter:"進入真正 ComfyUI",sendStory:"將故事主視覺送入 ComfyUI",sendShot:"將本鏡送入 ComfyUI"}:locale==="ja"?{desc:"公式 ComfyUI のキャンバス、ノード、モデル、Manager、拡張をそのまま使用します。",enter:"ComfyUI を開く",sendStory:"メインビジュアルを ComfyUI へ",sendShot:"このショットを ComfyUI へ"}:{desc:"Use the official ComfyUI canvas, real nodes, models, Manager, and extensions.",enter:"Open real ComfyUI",sendStory:"Send key visual to ComfyUI",sendShot:"Send this shot to ComfyUI"};

  useEffect(()=>{ const saved=(localStorage.getItem("frame-theme") as Theme|null)||"system"; setThemeState(saved); const media=window.matchMedia("(prefers-color-scheme: dark)"); const apply=()=>{document.documentElement.dataset.theme=saved==="system"?(media.matches?"dark":"light"):saved}; apply(); media.addEventListener("change",apply); return()=>media.removeEventListener("change",apply); },[]);
  useEffect(()=>{ const saved=(localStorage.getItem("frame-backdrop") as Backdrop|null)||"none"; setBackdropState(saved); },[]);
  useEffect(()=>{const saved=localStorage.getItem("frame-locale");const next=preferredLocale(saved||navigator.language);setLocaleState(next);setImageConcept(current=>Object.values(sampleImageConcepts).includes(current)?sampleImageConcepts[next]:current);document.documentElement.lang=next},[]);
  useEffect(()=>{setPoseRealistic(localStorage.getItem("frame-pose-realistic")!=="false")},[]);
  useEffect(()=>{let cancelled=false;const activeLocale=preferredLocale(localStorage.getItem("frame-locale")||navigator.language);async function restoreAccountConfig(){const savedProvider=localStorage.getItem("frame-provider")||"openrouter";const preset=providerById(savedProvider);const savedBase=localStorage.getItem("frame-api-base")||preset.baseUrl;const savedModel=localStorage.getItem("frame-generation-model")||"";setProviderId(savedProvider);setApiBaseUrl(savedBase);setGenerationModel(savedModel);if(!user){setConfigStatus(translate(activeLocale,"loginSync"));return}setConfigStatus(translate(activeLocale,"restoring"));try{const response=await fetch("/api/model-config",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(translate(activeLocale,"readFailed"));if(cancelled)return;if(data.config){applyAccountConfig(data.config);setConfigStatus(translate(activeLocale,"restored"));clearLegacyKeys();return}const legacyKey=sessionStorage.getItem(`frame-api-key:${savedProvider}`)||sessionStorage.getItem("frame-api-key");if(legacyKey&&savedModel){const migrated=await fetch("/api/model-config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerId:savedProvider,apiBaseUrl:savedBase,model:savedModel,apiKey:legacyKey})});const migratedData=await migrated.json();if(!migrated.ok)throw new Error(translate(activeLocale,"saveFailed"));if(cancelled)return;applyAccountConfig(migratedData.config);clearLegacyKeys();setConfigStatus(translate(activeLocale,"migrated"));return}setConfigStatus(translate(activeLocale,"noAccountConfig"))}catch(error){if(!cancelled)setConfigStatus(error instanceof Error?error.message:translate(activeLocale,"readFailed"))} }restoreAccountConfig();return()=>{cancelled=true}},[user]);
  useEffect(()=>{let cancelled=false;const activeLocale=preferredLocale(localStorage.getItem("frame-locale")||navigator.language);async function restoreImageConfig(){if(!user){setImageConfigStatus(translate(activeLocale,"imageEngineMissing"));return}try{const response=await fetch("/api/image-config",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(translate(activeLocale,"imageConfigFailed"));if(cancelled)return;if(data.config){applyAccountImageConfig(data.config);setImageConfigStatus(translate(activeLocale,"imageEngineSaved"))}else setImageConfigStatus(translate(activeLocale,"imageEngineMissing"))}catch(error){if(!cancelled)setImageConfigStatus(error instanceof Error?error.message:translate(activeLocale,"imageConfigFailed"))}}restoreImageConfig();return()=>{cancelled=true}},[user]);
  useEffect(()=>{const onKeyDown=(event:KeyboardEvent)=>{if(event.key==="Escape"){setThemeOpen(false);setLanguageOpen(false);setBrandOpen(false);setProfileOpen(false);setSettingsOpen(false);return}if(!event.altKey||event.ctrlKey||event.metaKey)return;const target=event.target as HTMLElement|null;if(target?.matches("input, textarea, select, [contenteditable='true']"))return;const next=({"1":"story","2":"image","3":"generate","4":"pose"} as const)[event.key as "1"|"2"|"3"|"4"];if(next){event.preventDefault();const doc=document as Document&{startViewTransition?:(callback:()=>void)=>unknown};if(!window.matchMedia("(prefers-reduced-motion: reduce)").matches&&doc.startViewTransition)doc.startViewTransition(()=>setWorkspaceMode(next));else setWorkspaceMode(next)}};window.addEventListener("keydown",onKeyDown);return()=>window.removeEventListener("keydown",onKeyDown)},[]);
  useEffect(()=>{const onPointerDown=(event:globalThis.PointerEvent)=>{const target=event.target as Element|null;if(target?.closest("[data-topbar-popover]"))return;setThemeOpen(false);setLanguageOpen(false);setBrandOpen(false);setProfileOpen(false)};document.addEventListener("pointerdown",onPointerDown,true);return()=>document.removeEventListener("pointerdown",onPointerDown,true)},[]);
  function clearLegacyKeys(){sessionStorage.removeItem("frame-api-key");Object.keys(sessionStorage).filter(key=>key.startsWith("frame-api-key:")).forEach(key=>sessionStorage.removeItem(key))}
  function applyAccountConfig(config:AccountModelConfig){setAccountConfig(config);setProviderId(config.providerId);setApiBaseUrl(config.apiBaseUrl);setGenerationModel(config.model);setApiKey("");localStorage.setItem("frame-provider",config.providerId);localStorage.setItem("frame-api-base",config.apiBaseUrl);localStorage.setItem("frame-generation-model",config.model)}
  function applyAccountImageConfig(config:AccountImageConfig){setAccountImageConfig(config);setImageProviderId(config.providerId);setImageApiBaseUrl(config.apiBaseUrl);setImageGenerationModel(config.model);setImageApiKey("")}
  function setTheme(value:Theme){setThemeState(value);localStorage.setItem("frame-theme",value);const dark=value==="dark"||(value==="system"&&matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.dataset.theme=dark?"dark":"light";setThemeOpen(false)}
  function setBackdrop(value:Backdrop){setBackdropState(value);localStorage.setItem("frame-backdrop",value);setBrandOpen(false)}
  function setLocale(value:Locale){setLocaleChanging(true);setLocaleState(value);setImageConcept(current=>Object.values(sampleImageConcepts).includes(current)?sampleImageConcepts[value]:current);localStorage.setItem("frame-locale",value);document.documentElement.lang=value;setLanguageOpen(false);setConfigStatus(savedKeyMatches?translate(value,"restored"):translate(value,"noAccountConfig"));window.setTimeout(()=>setLocaleChanging(false),520)}
  function trackLight(e:PointerEvent<HTMLElement>){if(e.pointerType!=="mouse"||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;e.currentTarget.style.setProperty("--mx",`${e.clientX}px`);e.currentTarget.style.setProperty("--my",`${e.clientY}px`);e.currentTarget.style.setProperty("--parallax-x",`${(e.clientX-window.innerWidth/2)*.018}px`);e.currentTarget.style.setProperty("--parallax-y",`${(e.clientY-window.innerHeight/2)*.014}px`)}
  function switchWorkspace(next:WorkspaceMode){if(next===workspaceMode||workspaceChanging)return;const reduce=window.matchMedia("(prefers-reduced-motion: reduce)").matches;const transitionDocument=document as Document&{startViewTransition?:(callback:()=>void)=>{finished:Promise<void>}};if(!reduce&&transitionDocument.startViewTransition){const transition=transitionDocument.startViewTransition(()=>setWorkspaceMode(next));void transition.finished.finally(()=>setWorkspaceChanging(false));return}if(reduce){setWorkspaceMode(next);return}setWorkspaceChanging(true);window.setTimeout(()=>{setWorkspaceMode(next);window.requestAnimationFrame(()=>setWorkspaceChanging(false))},150)}
  function chooseProvider(id:string){const preset=providerById(id);const restored=accountConfig?.providerId===id;setProviderId(id);setApiBaseUrl(restored?accountConfig.apiBaseUrl:preset.baseUrl);setApiKey("");setAvailableModels([]);setGenerationModel(restored?accountConfig.model:"");setConfigStatus(restored?t("foundKey"):t("notVerified",{provider:preset.name}))}
  async function readProviderModels(){if(!apiKey.trim()&&!savedKeyMatches){setConfigStatus(t("needKey"));return}if(!apiBaseUrl.trim()){setConfigStatus(t("apiBaseRequired"));return}setDetectingModels(true);setConfigStatus(savedKeyMatches&&!apiKey.trim()?t("readingAccountKey"):t("validatingKey"));try{const response=await fetch("/api/models",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerId,baseUrl:apiBaseUrl,apiKey:apiKey.trim()})});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("readFailed"));setAvailableModels(data.models||[]);const preferred=(data.models||[]).find((x:ModelOption)=>x.vision)||(data.models||[])[0];if(preferred)setGenerationModel((current:string)=>(data.models||[]).some((x:ModelOption)=>x.id===current)?current:preferred.id);if(data.provider?.id&&providerId==="custom"&&apiKey.trim())setProviderId(data.provider.id);setConfigStatus(t("recognized",{provider:data.provider?.name||t("modelService"),count:(data.models||[]).length}))}catch(error){setAvailableModels([]);setConfigStatus(error instanceof Error?error.message:t("readFailed"))}finally{setDetectingModels(false)}}
  async function saveModelConfig(){if(!generationModel.trim()){setConfigStatus(t("needModel"));return}if(!apiKey.trim()&&!savedKeyMatches){setConfigStatus(t("firstSaveKey"));return}setConfigStatus(t("savingSecure"));try{const response=await fetch("/api/model-config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerId,apiBaseUrl:apiBaseUrl.trim(),model:generationModel.trim(),apiKey:apiKey.trim()||undefined})});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("saveFailed"));applyAccountConfig(data.config);clearLegacyKeys();setConfigStatus(t("savedCloud"));setSettingsOpen(false)}catch(error){setConfigStatus(error instanceof Error?error.message:t("saveFailed"))}}
  async function clearModelConfig(){setConfigStatus(t("deleting"));try{const response=await fetch("/api/model-config",{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("deleteFailed"));clearLegacyKeys();localStorage.removeItem("frame-provider");localStorage.removeItem("frame-api-base");localStorage.removeItem("frame-generation-model");setAccountConfig(null);setProviderId("openrouter");setApiBaseUrl(providerById("openrouter").baseUrl);setApiKey("");setAvailableModels([]);setGenerationModel("");setConfigStatus(t("deletedCloud"))}catch(error){setConfigStatus(error instanceof Error?error.message:t("deleteFailed"))}}
  function chooseImageProvider(id:string){const provider=imageGenerationProviderById(id);const restored=accountImageConfig?.providerId===id;setImageProviderId(id);setImageApiBaseUrl(restored?accountImageConfig.apiBaseUrl:provider.baseUrl);setImageGenerationModel(restored?accountImageConfig.model:provider.models[0]?.id||"");setImageApiKey("");setImageConfigStatus(restored?t("imageEngineSaved"):provider.hint)}
  async function saveImageConfig(){if(!imageGenerationModel.trim()){setImageConfigStatus(t("needModel"));return}if(!imageApiKey.trim()&&!savedImageKeyMatches){setImageConfigStatus(t("firstSaveKey"));return}setImageConfigStatus(t("savingSecure"));try{const response=await fetch("/api/image-config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerId:imageProviderId,apiBaseUrl:imageApiBaseUrl.trim(),model:imageGenerationModel.trim(),apiKey:imageApiKey.trim()||undefined})});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("imageConfigFailed"));applyAccountImageConfig(data.config);setImageConfigStatus(t("imageConfigSaved"))}catch(error){setImageConfigStatus(error instanceof Error?error.message:t("imageConfigFailed"))}}
  async function clearImageConfig(){setImageConfigStatus(t("deleting"));try{const response=await fetch("/api/image-config",{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("deleteFailed"));const provider=imageGenerationProviderById("runway");setAccountImageConfig(null);setImageProviderId(provider.id);setImageApiBaseUrl(provider.baseUrl);setImageGenerationModel(provider.models[0].id);setImageApiKey("");setImageConfigStatus(t("imageConfigDeleted"))}catch(error){setImageConfigStatus(error instanceof Error?error.message:t("deleteFailed"))}}
  function activeProviderConfig(){return{providerId,baseUrl:apiBaseUrl.trim(),apiKey:apiKey.trim(),model:generationModel.trim()}}
  async function generate(){
    if(!idea.trim())return;
    if((!apiKey.trim()&&!savedKeyMatches)||!generationModel.trim()){setNotice(t("configRequired"));setSettingsOpen(true);setProfileOpen(false);return}
    setGenerating(true);setNotice(t("generatingStory"));
    try{
      const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"story",locale,idea:idea.trim(),genre,style,duration,platform,videoModel:model,lockCharacters:lock,referenceNotes:imageNotes.trim(),referenceImage:image?.src||null,providerConfig:activeProviderConfig()})});
      const data=await response.json();
      if(!response.ok)throw new Error(data?.error||t("generationFailed"));
      setStory(data.story);setShots(data.shots);setVersion(v=>v+1);setNotice(t("creationComplete"));setActiveTab("story");
    }catch(error){setNotice(error instanceof Error?error.message:t("generationFailed"));}
    finally{setGenerating(false)}
  }
  async function copy(text:string,label:string){await navigator.clipboard.writeText(text);setCopied(label);setTimeout(()=>setCopied(""),1400)}
  function copyAll(){copy(shots.map(s=>`SHOT ${String(s.id).padStart(2,"0")}\n${s.prompt}`).join("\n\n──────────\n\n"),"all")}
  function exportText(){const content=`${story.title}\n\n${t("coreIdea")}: ${idea}\n${t("promptFormat")}: ${optionLabel(locale,model)}\n${t("visualReference")}: ${image?`${image.name} / ${image.orientation} / ${image.color}`:"—"}\n\n${shots.map(s=>`SHOT ${s.id}｜${s.time}｜${s.shot}\n${t("visualStyle")}: ${s.visual}\n${t("camera")}: ${s.camera}\n${t("sound")}: ${s.audio}\n${t("promptSuffix")}:\n${s.prompt}`).join("\n\n")}`;const blob=new Blob([content],{type:"text/plain;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${story.title.replace(/[《》]/g,"")}-${t("shotScript")}.txt`;a.click();URL.revokeObjectURL(a.href)}
  async function askIdeaMentor(){if((!apiKey.trim()&&!savedKeyMatches)||!generationModel.trim()){setNotice(t("configRequired"));setSettingsOpen(true);return}setMentorLoading(true);setMentorSuggestion(null);setNotice(t("mentorThinking"));try{const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"idea-mentor",locale,idea:idea.trim(),providerConfig:activeProviderConfig()})});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("mentorFailed"));setMentorSuggestion({hook:data.hook,suggestion:data.suggestion});setNotice(t("mentorReady"))}catch(error){setNotice(error instanceof Error?error.message:t("mentorFailed"))}finally{setMentorLoading(false)}}
  function useMentorSuggestion(){if(!mentorSuggestion)return;setIdea(current=>current.trim()?`${current.trim()}\n\n${mentorSuggestion.hook}`:mentorSuggestion.hook);setMentorSuggestion(null);setNotice(t("mentorApplied"))}
  async function generateImagePrompt(renderImage=false){
    const workflow:ImageWorkflow=renderImage?imageWorkflow:"text-to-image";
    const concept=workflow==="text-to-image"?imageConcept.trim():imageBriefNotes.trim()||(workflow==="image-to-image"?t("workflowImageDesc"):t("workflowMultiDesc"));
    if(!concept)return;
    if((!apiKey.trim()&&!savedKeyMatches)||!generationModel.trim()){setImagePrompt(t("configRequired"));setSettingsOpen(true);setProfileOpen(false);return}
    if(renderImage&&!accountImageConfig){setImageConfigStatus(t("imageEngineMissing"));setSettingsOpen(true);setProfileOpen(false);return}
    const references=renderImage?(workflow==="text-to-image"?[]:workflow==="image-to-image"?promptReferences.slice(0,1):promptReferences.slice(0,6)):pipelinePromptReferences.slice(0,1);
    if(workflow==="image-to-image"&&references.length!==1){setReferenceError(t("singleReferenceRequired"));return}
    if(workflow==="multi-reference"&&references.length<2){setReferenceError(t("multiReferenceRequired"));return}
    setImageGenerating(true);setImagePrompt("");setImagePromptCore("");setGeneratedImage(null);setImageRenderStatus("");
    try{
      const promptTarget=renderImage&&accountImageConfig?imagePromptFamily(accountImageConfig.model):imageModel;
      const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"image-prompt",locale,imageWorkflow:workflow,concept,purpose:imagePurpose,style:imageStyle,aspect:imageAspect,imageModel:promptTarget,referenceNotes:renderImage?imageBriefNotes.trim():pipelineSource?.detail||"",referenceImages:references.map(item=>({data:item.src,name:item.name,role:item.role,note:item.note.trim()})),providerConfig:activeProviderConfig()})});
      const data=await response.json();
      if(!response.ok)throw new Error(data?.error||"图片提示词生成失败。");
      setImagePromptCore(data.prompt);
      setImagePrompt(`${data.prompt}${data.negativePrompt?`\n\nNEGATIVE / ${t("negative")}\n${data.negativePrompt}`:""}${data.visualAnalysis?`\n\nVISUAL REFERENCE ANALYSIS / ${t("analysis")}\n${data.visualAnalysis}`:""}`);
      if(renderImage)try{await renderGeneratedImage(data.prompt,references,workflow)}catch(error){setImageRenderStatus(error instanceof Error?error.message:t("imageGenerationFailed"))}
    }catch(error){setImagePrompt(error instanceof Error?error.message:t("generationFailed"))}
    finally{setImageGenerating(false)}
  }
  async function requestGeneratedImage(prompt:string,workflow:ImageWorkflow,aspect:string,references:PromptReference[],onStatus:(value:string)=>void){
    if(!accountImageConfig)throw new Error(t("imageEngineMissing"));
    const response=await fetch("/api/generate-image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,workflow,aspect,references:references.map(item=>({data:item.src,role:item.role,note:item.note.trim()}))})});
    let data=await response.json();if(!response.ok)throw new Error(data?.error||t("imageGenerationFailed"));
    if(data.status==="pending"){
      onStatus(t("imageTaskQueued"));
      const query=data.taskId?`taskId=${encodeURIComponent(data.taskId)}`:`pollToken=${encodeURIComponent(data.pollToken)}`;
      for(let attempt=0;attempt<90&&data.status==="pending";attempt++){
        await new Promise(resolve=>window.setTimeout(resolve,1600));
        const progress=await fetch(`/api/generate-image?${query}`,{cache:"no-store"});data=await progress.json();if(!progress.ok)throw new Error(data?.error||t("imageGenerationFailed"));
      }
    }
    if(data.status!=="succeeded"||!data.imageUrl)throw new Error(data?.error||t("imageGenerationFailed"));
    return{src:data.imageUrl,model:data.model||accountImageConfig.model,provider:data.provider||imageGenerationProviderById(accountImageConfig.providerId).name} as GeneratedImage;
  }
  async function renderGeneratedImage(prompt:string,references:PromptReference[],workflow:ImageWorkflow=imageWorkflow){
    setImageRendering(true);setGeneratedImage(null);setImageRenderStatus(t("renderingImage"));
    try{const result=await requestGeneratedImage(prompt,workflow,imageAspect,references,setImageRenderStatus);setGeneratedImage(result);setImageRenderStatus(t("imageReady"))}finally{setImageRendering(false)}
  }
  async function rerenderImage(){if(!imagePromptCore||imageRendering)return;const references=imageWorkflow==="text-to-image"?[]:imageWorkflow==="image-to-image"?promptReferences.slice(0,1):promptReferences.slice(0,6);try{await renderGeneratedImage(imagePromptCore,references)}catch(error){setImageRenderStatus(error instanceof Error?error.message:t("imageGenerationFailed"))}}
  async function downloadImageResult(result:GeneratedImage|null,prefix="FRAME"){if(!result)return;const response=await fetch(result.src);const blob=await response.blob();const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${prefix}-${result.model.replace(/[^a-zA-Z0-9_-]+/g,"-")}-${Date.now()}.png`;link.click();URL.revokeObjectURL(link.href)}
  async function downloadGeneratedImage(){await downloadImageResult(generatedImage)}
  function prepareStoryForComfy(shot?:Shot){if(!story.title)return;const prompt=shot?.prompt||`${story.title}\n${story.logline}\n${story.direction}`;setComfySeedPrompt(prompt.slice(0,12000));setComfySeedVersion(value=>value+1);setPipelineSource({stage:"story",title:shot?t("pipelineShotSource",{count:shot.id}):t("pipelineStorySource"),detail:shot?shot.visual:story.logline,shotId:shot?.id});switchWorkspace("image")}
  async function renderPipelineImage(){if(!pipelineRenderPrompt.trim())return;if(!accountImageConfig){setImageConfigStatus(t("imageEngineMissing"));setSettingsOpen(true);return}const references=imageWorkflow==="text-to-image"?[]:imageWorkflow==="image-to-image"?promptReferences.slice(0,1):promptReferences.slice(0,6);setImagePromptCore(pipelineRenderPrompt);setImagePrompt(pipelineRenderPrompt);try{await renderGeneratedImage(pipelineRenderPrompt,references,imageWorkflow)}catch(error){setImageRenderStatus(error instanceof Error?error.message:t("imageGenerationFailed"))}}
  function sendPoseToRender(){const capture=poseRigRef.current?.capture();if(!capture){setPoseStatus(t("poseCaptureFailed"));return}const guideInstruction=posePeople.length>1?t("multiPoseGuideNote",{count:posePeople.length}):t("poseGuideNote");const poseGuide:PromptReference={src:capture,name:"FRAME-3D-POSE.png",width:0,height:0,orientation:"portrait",color:"pose guide",tone:"neutral",size:"generated",id:"pose-rig-pipeline",role:"composition",note:guideInstruction};const references=poseReference?[poseGuide,poseReference]:[poseGuide];setPromptReferences(references);setImageWorkflow(references.length>1?"multi-reference":"image-to-image");setImageConcept(poseConcept.trim()||t("poseDefaultPrompt"));setImageBriefNotes(guideInstruction);setImageStyle(poseStyle);setImageAspect(poseAspect);setImagePrompt("");setImagePromptCore("");setPipelineRenderPrompt("");setGeneratedImage(null);setPipelineSource({stage:"pose",title:t("pipelinePoseSource"),detail:t("pipelinePoseDetail")});switchWorkspace("generate")}
  async function readPoseReference(file:File){setPoseStatus("");try{const info=await inspectImageFile(file);setPoseReference({...info,id:crypto.randomUUID(),role:"character",note:t("poseReferenceHint")});setPoseStatus(t("poseReferenceLoaded"))}catch(error){setPoseStatus(error instanceof Error&&error.message==="IMAGE_SIZE"?t("imageTooLarge"):t("chooseImage"))}}
  async function readPoseMotionReference(file:File){setPoseMotionStatus("");setPoseMotionAnalysis("");try{setPoseMotionReference(await inspectImageFile(file));setPoseMotionStatus(t("poseMotionLoaded"))}catch(error){setPoseMotionStatus(error instanceof Error&&error.message==="IMAGE_SIZE"?t("imageTooLarge"):t("chooseImage"))}}
  async function estimatePoseFromImage(){if(!poseMotionReference){setPoseMotionStatus(t("poseMotionRequired"));return}if((!apiKey.trim()&&!savedKeyMatches)||!generationModel.trim()){setPoseMotionStatus(t("poseVisionModelRequired"));setSettingsOpen(true);return}setPoseEstimating(true);setPoseMotionStatus(t("poseEstimating"));setPoseMotionAnalysis("");try{const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"pose-estimation",locale,referenceImage:poseMotionReference.src,providerConfig:activeProviderConfig()})});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("poseEstimationFailed"));const confidence=Number(data.confidence)||0;if(confidence<.48){setPoseMotionAnalysis(`${data.summary||t("poseLowConfidence")} · ${Math.round(confidence*100)}%`);setPoseMotionStatus(t("poseLowConfidence"));return}poseRigRef.current?.applyJointMap(data.pose as JointMap);setActivePosePreset("custom");setPoseMotionAnalysis(`${data.summary||t("poseFromImageApplied")} · ${Math.round(confidence*100)}%`);setPoseMotionStatus(t("poseFromImageApplied"));setPoseStatus(t("poseFromImageApplied"))}catch(error){setPoseMotionStatus(error instanceof Error?error.message:t("poseEstimationFailed"))}finally{setPoseEstimating(false)}}
  function selectPosePreset(preset:PosePreset){poseRigRef.current?.applyPreset(preset);setActivePosePreset(preset);const definition=POSE_PRESET_LIBRARY.find(item=>item.id===preset);if(definition?.category==="lying"){poseRigRef.current?.setView("front");setPoseView("front")}setPoseStatus(t("posePresetApplied",{preset:definition?t(definition.labelKey):t("poseReset")}))}
  function mirrorCurrentPose(){poseRigRef.current?.mirror();setActivePosePreset("custom");setPoseStatus(t("poseMirrored"))}
  function resetCurrentPose(){poseRigRef.current?.reset();setActivePosePreset("neutral");setPoseStatus(t("poseReset"))}
  function addPosePerson(){if(posePeople.length>=3){setPoseStatus(t("posePeopleLimit"));return}poseRigRef.current?.addPerson(poseGender);setActivePosePreset("neutral");setPoseStatus(t("posePersonAdded"))}
  function removePosePerson(){if(posePeople.length<=1)return;poseRigRef.current?.removePerson();setActivePosePreset("neutral");setPoseStatus(t("posePersonRemoved"))}
  function selectPosePerson(index:number){poseRigRef.current?.selectPerson(index);setActivePosePreset("custom")}
  function changePoseBodyType(gender:PoseGender){setPoseGender(gender);poseRigRef.current?.setBodyType(gender);setActivePosePreset("neutral");setPoseStatus(t("poseBodyChanged"))}
  function changePoseView(view:RigView){setPoseView(view);poseRigRef.current?.setView(view);setPoseStatus(t("poseViewChanged"))}
  function changePoseFacing(facing:CharacterFacing){setPoseFacing(facing);poseRigRef.current?.setFacing(facing);setPoseStatus(t("poseFacingChanged"))}
  function changePoseDragAxis(axis:DragAxis){setPoseDragAxis(axis);poseRigRef.current?.setDragAxis(axis);setPoseStatus(t("poseAxisChanged"))}
  function togglePoseRealism(){const next=!poseRealistic;setPoseRealistic(next);localStorage.setItem("frame-pose-realistic",String(next));poseRigRef.current?.setRealistic(next);setActivePosePreset("custom");setPoseStatus(t(next?"realisticSkeletonEnabled":"freeSkeletonEnabled"))}
  async function generatePoseImage(){
    if(!accountImageConfig){setImageConfigStatus(t("imageEngineMissing"));setSettingsOpen(true);return}
    const capture=poseRigRef.current?.capture();if(!capture){setPoseStatus(t("poseCaptureFailed"));return}
    const guideInstruction=posePeople.length>1?t("multiPoseGuideNote",{count:posePeople.length}):t("poseGuideNote");
    const poseGuide:PromptReference={src:capture,name:"FRAME-3D-POSE.png",width:0,height:0,orientation:"portrait",color:"pose guide",tone:"neutral",size:"generated",id:"pose-rig",role:"composition",note:guideInstruction};
    const references=poseReference?[poseGuide,poseReference]:[poseGuide];
    const workflow:ImageWorkflow=references.length>1?"multi-reference":"image-to-image";
    const concept=poseConcept.trim()||t("poseDefaultPrompt");
    let prompt=`${concept}. ${optionLabel(locale,poseStyle)}. ${guideInstruction} Complete anatomy, hands and feet visible, coherent clothing, clean image.`;
    setPoseGenerating(true);setPoseResult(null);setPosePrompt("");setPoseStatus(t("generatingPose"));
    try{
      if(accountConfig&&generationModel.trim())try{const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"image-prompt",locale,imageWorkflow:workflow,concept,purpose:"角色设定图",style:poseStyle,aspect:poseAspect,imageModel:imagePromptFamily(accountImageConfig.model),referenceNotes:guideInstruction,referenceImages:references.map(item=>({data:item.src,name:item.name,role:item.role,note:item.note})),providerConfig:activeProviderConfig()})});const data=await response.json();if(response.ok&&data.prompt)prompt=data.prompt}catch{}
      setPosePrompt(prompt);const result=await requestGeneratedImage(prompt,workflow,poseAspect,references,setPoseStatus);setPoseResult(result);setPoseStatus(t("poseReady"));
    }catch(error){setPoseStatus(error instanceof Error?error.message:t("imageGenerationFailed"))}finally{setPoseGenerating(false)}
  }
  async function readImage(file:File){setUploadError("");try{setImage(await inspectImageFile(file));setNotice(t("imageRead"))}catch(error){setUploadError(error instanceof Error&&error.message==="IMAGE_SIZE"?t("imageTooLarge"):t("chooseImage"))}}
  function onDrop(e:DragEvent<HTMLDivElement>){e.preventDefault();const file=e.dataTransfer.files[0];if(file)readImage(file)}
  function changeImageWorkflow(value:ImageWorkflow){setImageWorkflow(value);setImagePrompt("");setImagePromptCore("");setPipelineRenderPrompt("");setGeneratedImage(null);setImageRenderStatus("");setReferenceError("")}
  async function addPromptReferenceFiles(files:File[]){setReferenceError("");const limit=imageWorkflow==="image-to-image"?1:6;const incoming=imageWorkflow==="image-to-image"?files.slice(0,1):files.slice(0,Math.max(0,limit-promptReferences.length));if(!incoming.length){setReferenceError(t("referenceLimit"));return}const next:PromptReference[]=[];for(const file of incoming){try{const info=await inspectImageFile(file);const index=(imageWorkflow==="image-to-image"?0:promptReferences.length+next.length);next.push({...info,id:crypto.randomUUID(),role:imageWorkflow==="image-to-image"?"source":referenceRoles[Math.min(index,referenceRoles.length-1)],note:""})}catch(error){setReferenceError(error instanceof Error&&error.message==="IMAGE_SIZE"?t("imageTooLarge"):t("chooseImage"))}}if(next.length)setPromptReferences(current=>imageWorkflow==="image-to-image"?next.slice(0,1):[...current,...next].slice(0,6))}
  function onPromptReferenceDrop(e:DragEvent<HTMLDivElement>){e.preventDefault();void addPromptReferenceFiles(Array.from(e.dataTransfer.files))}
  function updatePromptReference(id:string,field:"role"|"note",value:string){setPromptReferences(current=>current.map(item=>item.id===id?{...item,[field]:value}:item))}
  function removePromptReference(id:string){setPromptReferences(current=>current.filter(item=>item.id!==id));setImagePrompt("")}
  const imageWorkflowReady=imageWorkflow==="text-to-image"||(imageWorkflow==="image-to-image"&&promptReferences.length>=1)||(imageWorkflow==="multi-reference"&&promptReferences.length>=2);
  const activeReferenceCount=imageWorkflow==="image-to-image"?Math.min(1,promptReferences.length):promptReferences.length;
  const referenceCounter=imageWorkflow==="image-to-image"?`${activeReferenceCount} / 1`:t("referenceCount",{count:activeReferenceCount});
  const initials=(user?.displayName||user?.email||t("guest")).slice(0,1).toUpperCase(); const themeLabel={light:t("day"),dark:t("night"),system:t("followSystem")}[theme]; const activeLanguage=LANGUAGE_OPTIONS.find(item=>item.id===locale)||LANGUAGE_OPTIONS[0]; const topbarPopoverOpen=brandOpen||languageOpen||themeOpen||profileOpen;
  const modelBrand=detectModelBrand(generationModel,providerId); const filteredModels=availableModels.filter(item=>`${item.name} ${item.id}`.toLowerCase().includes(modelSearch.toLowerCase())).slice(0,160);
  const selectedImageProvider=imageGenerationProviderById(imageProviderId); const renderImageModel=accountImageConfig?imagePromptFamily(accountImageConfig.model):imageModel;

  return <main id="studio-content" tabIndex={-1} onPointerMove={trackLight} className={`backdrop-${backdrop} locale-${locale} ${localeChanging?"locale-changing":""} ${workspaceChanging?"workspace-changing":""}`}>
    <a className="skip-link" href="#studio-content">{t("creationHome")}</a>
    <BackdropVisual mode={backdrop}/><div className="ambient ambient-one"/><div className="ambient ambient-two"/><div className="noise"/>
    <header className="topbar">
      <div className="brand-area" data-topbar-popover><button className="brand" onClick={()=>{setBrandOpen(v=>!v);setThemeOpen(false);setLanguageOpen(false);setProfileOpen(false)}} aria-expanded={brandOpen} aria-label={`FRAME ${t("background")}`}><span className="brand-symbol"><b>F</b><i/></span><span className="brand-word">FRAME</span><em>AI STORY STUDIO</em></button>{brandOpen&&<div className="brand-menu popover"><span className="popover-title">{t("background")}</span><button className={backdrop==="none"?"selected":""} onClick={()=>setBackdrop("none")}><i className="mini blank"/><span><b>{t("cleanCanvas")}</b><small>{t("focusCreate")}</small></span></button><button className={backdrop==="globe"?"selected":""} onClick={()=>setBackdrop("globe")}><i className="mini globe-mini"/><span><b>{t("orbital")}</b><small>{t("worldMode")}</small></span></button><button className={backdrop==="mind"?"selected":""} onClick={()=>setBackdrop("mind")}><i className="mini mind-mini"/><span><b>{t("neural")}</b><small>{t("ideaMode")}</small></span></button></div>}</div>
      <div className="top-actions">
        {workspaceMode!=="home"&&<nav className="studio-switcher" aria-label={t("creationHome")}><button className="module-home" onClick={()=>switchWorkspace("home")} title={t("creationHome")}>←</button>{([['story','01','STORY','enterStory'],['image','02','COMFY','enterImage'],['generate','03','RENDER','enterRender'],['pose','04','POSE','enterPose']] as const).map(([mode,index,label,title])=><button key={mode} className={workspaceMode===mode?"active":""} aria-pressed={workspaceMode===mode} onClick={()=>switchWorkspace(mode)} title={`${mode==="image"?comfyCard.enter:t(title)} · Alt+${index.slice(-1)}`}><i>{index}</i><span>{label}</span></button>)}</nav>}
        {generationModel&&<button className="active-model-pill" onClick={()=>setSettingsOpen(true)}>{modelBrand.logo?<img src={modelBrand.logo} alt=""/>:<i>{modelBrand.short}</i>}<span>{generationModel}</span></button>}
        <div className="language-wrap" data-topbar-popover><button className="utility-button language-button" onClick={()=>{setLanguageOpen(v=>!v);setThemeOpen(false);setBrandOpen(false);setProfileOpen(false)}} aria-label={t("language")} aria-expanded={languageOpen}><span className="language-icon">文</span><small>{activeLanguage.short}</small></button>{languageOpen&&<div className="language-menu popover"><span className="popover-title">{t("language")} / LANGUAGE</span>{LANGUAGE_OPTIONS.map(item=><button key={item.id} className={locale===item.id?"selected":""} onClick={()=>setLocale(item.id)}><i>{item.id==="en"?"A":item.id==="ja"?"あ":"文"}</i><span><b>{item.native}</b><small>{item.id}</small></span><em>{locale===item.id?"✓":""}</em></button>)}</div>}</div>
        <div className="theme-wrap" data-topbar-popover><button className="utility-button" onClick={()=>{setThemeOpen(v=>!v);setLanguageOpen(false);setBrandOpen(false);setProfileOpen(false)}} aria-label={t("siteTone")} aria-expanded={themeOpen}><span className="theme-icon">{theme==="dark"?"◐":theme==="light"?"☼":"◒"}</span><small>{themeLabel}</small></button>{themeOpen&&<div className="theme-menu popover"><span className="popover-title">{t("siteTone")}</span>{(["light","dark","system"] as Theme[]).map(x=><button key={x} className={theme===x?"selected":""} onClick={()=>setTheme(x)}><i>{x==="light"?"☼":x==="dark"?"◐":"◒"}</i><span>{x==="light"?t("day"):x==="dark"?t("night"):t("followSystem")}</span><b>✓</b></button>)}</div>}</div>
        <div className="profile-wrap" data-topbar-popover><button className="avatar" onClick={()=>{setProfileOpen(v=>!v);setThemeOpen(false);setLanguageOpen(false);setBrandOpen(false)}} aria-label={t("profile")} aria-expanded={profileOpen}>{initials}</button>{profileOpen&&<div className="profile-card popover"><div className="profile-head"><span className="profile-avatar">{initials}</span><div><b>{user?.displayName||t("guest")}</b><small>{user?.email||t("noLogin")}</small></div></div>{user?<><dl><div><dt>{t("accountStatus")}</dt><dd><i/>{t("signedIn")}</dd></div><div><dt>{t("identity")}</dt><dd>{user.userId.slice(0,8)}••••</dd></div><div><dt>{t("generationModel")}</dt><dd className="profile-model">{generationModel||t("unconfigured")}</dd></div><div><dt>{t("imageEngine")}</dt><dd className="profile-model">{accountImageConfig?.model||t("unconfigured")}</dd></div></dl><button className="profile-config-button" onClick={()=>{setSettingsOpen(true);setProfileOpen(false)}}><span>{t("modelSettings")}</span><b>MODEL / IMAGE / COMFY →</b></button><a href="/signout-with-chatgpt?return_to=/">{t("logout")}</a></>:<a href="/signin-with-chatgpt?return_to=/">{t("login")}</a>}</div>}</div>
      </div>
    </header>
    {topbarPopoverOpen&&<div className="popover-dismiss-layer" aria-hidden="true" onPointerDown={()=>{setThemeOpen(false);setLanguageOpen(false);setBrandOpen(false);setProfileOpen(false)}}/>}
    {settingsOpen&&<div className="settings-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSettingsOpen(false)}}><section className="model-settings" role="dialog" aria-modal="true" aria-label={t("modelSettings")}>
      <div className="settings-head"><div><span>PROFILE / AI MODEL ROUTER</span><h2>{t("connectModel")}</h2><p>{t("connectModelDesc")}</p></div><button onClick={()=>setSettingsOpen(false)} aria-label={t("close")}>×</button></div>
      <div className="settings-body">
        <div className="settings-section-title"><span>01</span><div><b>{t("selectProvider")}</b><small>{t("openRouterTip")}</small></div></div>
        <div className="provider-grid">{MODEL_PROVIDERS.map(provider=><button key={provider.id} className={providerId===provider.id?"selected":""} onClick={()=>chooseProvider(provider.id)}>{provider.logo?<img src={provider.logo} alt=""/>:<i>{provider.short}</i>}<span><b>{provider.name}</b><small>{locale==="zh-CN"?provider.hint:provider.protocol.toUpperCase()}</small></span>{providerId===provider.id&&<em>✓</em>}</button>)}</div>

        <div className="settings-section-title"><span>02</span><div><b>{t("connectApi")}</b><small>{t("encryptionTip")}</small></div></div>
        <div className="api-fields"><label><span>API BASE URL</span><input value={apiBaseUrl} onChange={e=>setApiBaseUrl(e.target.value)} placeholder="https://api.example.com/v1"/></label><label><span>API KEY {savedKeyMatches&&<b className="saved-key-mark">{t("accountSaved")}</b>}</span><div className="secret-input"><input type={showApiKey?"text":"password"} value={apiKey} onChange={e=>setApiKey(e.target.value)} autoComplete="new-password" placeholder={savedKeyMatches?t("savedKeyPlaceholder"):t("keyPlaceholder")}/><button onClick={()=>setShowApiKey(v=>!v)}>{showApiKey?t("hide"):t("show")}</button></div></label></div>
        <div className="model-detect-row"><button className="detect-models" onClick={readProviderModels} disabled={detectingModels}>{detectingModels?t("detecting"):t("detectModels")}</button><span aria-live="polite" className={savedKeyMatches||configStatus.startsWith("已")?"ok":""}><i/>{configStatus}</span></div>

        <div className="settings-section-title"><span>03</span><div><b>{t("selectModel")}</b><small>{t("brandTip")}</small></div></div>
        {availableModels.length?<><div className="model-search"><input value={modelSearch} onChange={e=>setModelSearch(e.target.value)} placeholder={t("searchModels",{count:availableModels.length})}/><span>{filteredModels.length} RESULTS</span></div><div className="model-list">{filteredModels.map(item=>{const brand=detectModelBrand(item.id,providerId);return <button key={item.id} className={generationModel===item.id?"selected":""} onClick={()=>setGenerationModel(item.id)}>{brand.logo?<img src={brand.logo} alt=""/>:<i>{brand.short}</i>}<span><b>{item.name}</b><small>{item.id}</small></span>{item.vision&&<em>VISION</em>}{generationModel===item.id&&<strong>✓</strong>}</button>})}</div></>:<label className="manual-model"><span>{t("manualModel")}</span><input value={generationModel} onChange={e=>setGenerationModel(e.target.value)} placeholder="anthropic/claude-sonnet-latest"/><small>{t("manualTip")}</small></label>}

        <div className="image-engine-settings">
          <div className="settings-section-title"><span>04</span><div><b>{t("imageEngine")}</b><small>{t("imageEngineDesc")}</small></div></div>
          <div className="provider-grid image-provider-grid">{IMAGE_GENERATION_PROVIDERS.map(provider=><button key={provider.id} className={imageProviderId===provider.id?"selected":""} onClick={()=>chooseImageProvider(provider.id)}>{provider.logo?<img src={provider.logo} alt=""/>:<i>{provider.short}</i>}<span><b>{provider.name}</b><small>{provider.hint}</small></span>{imageProviderId===provider.id&&<em>✓</em>}</button>)}</div>
          <div className="api-fields"><label><span>IMAGE API BASE URL</span><input value={imageApiBaseUrl} onChange={e=>setImageApiBaseUrl(e.target.value)} placeholder={selectedImageProvider.baseUrl}/></label><label><span>IMAGE API KEY {savedImageKeyMatches&&<b className="saved-key-mark">{t("accountSaved")}</b>}</span><div className="secret-input"><input type={showImageApiKey?"text":"password"} value={imageApiKey} onChange={e=>setImageApiKey(e.target.value)} autoComplete="new-password" placeholder={savedImageKeyMatches?t("savedKeyPlaceholder"):t("engineKeyPlaceholder")}/><button onClick={()=>setShowImageApiKey(value=>!value)}>{showImageApiKey?t("hide"):t("show")}</button></div></label></div>
          <label className="manual-model image-engine-model"><span>{t("imageEngineModel")}</span><input list="image-engine-models" value={imageGenerationModel} onChange={e=>setImageGenerationModel(e.target.value)} placeholder={selectedImageProvider.models[0]?.id}/><datalist id="image-engine-models">{selectedImageProvider.models.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</datalist><small>{selectedImageProvider.models.map(item=>item.name).join(" · ")}</small></label>
          <div className="image-config-actions"><span aria-live="polite" className={savedImageKeyMatches?"ok":""}><i/>{imageConfigStatus}</span><div><button className="clear-config" onClick={clearImageConfig}>{t("deleteImageEngine")}</button><button className="save-config" onClick={saveImageConfig}>{t("saveImageEngine")} <b>↗</b></button></div></div>
        </div>
        <ComfyConnectionSettings locale={locale} compact />
      </div>
      <div className="settings-footer"><div className="selected-engine">{modelBrand.logo?<img src={modelBrand.logo} alt=""/>:<i>{modelBrand.short}</i>}<span><small>{savedKeyMatches?t("accountConnected"):t("currentEngine")}</small><b>{generationModel||t("noModel")}</b></span></div><div><button className="clear-config" onClick={clearModelConfig}>{t("deleteConfig")}</button><button className="save-config" onClick={saveModelConfig}>{t("saveAccount")} <b>↗</b></button></div></div>
    </section></div>}
    {workspaceMode==="home"?<section className="welcome-screen">
      <IdeaField/>
      <div className="welcome-copy"><span className="eyebrow"><span/> FRAME CREATIVE OS</span><h1>{t("welcomeBack")}<br/><em>{(user?.displayName||t("creator")).split("@")[0]}</em><b className="welcome-period">。</b></h1><p>{t("welcomeDesc")}</p><div className="welcome-status"><i/><span>{t("ready")}</span><b>{t("formatCount",{video:models.length,image:imageModels.length})}</b></div></div>
      <div className="module-grid">
        <button className="module-card portal-card story-module" onPointerMove={moveModuleCard} onPointerLeave={resetModuleCard} onClick={()=>switchWorkspace("story")}><div className="module-card-head"><span className="module-index">01</span><small><i/>SEQUENCE READY</small></div><WelcomeModuleVisual type="story"/><div className="module-meta"><span>VIDEO NARRATIVE</span><h2>AI STORY<br/>STUDIO</h2><p>{t("storyModuleDesc")}</p><em>{t("enterStory")} <b>↗</b></em></div></button>
        <button className="module-card portal-card image-module" onPointerMove={moveModuleCard} onPointerLeave={resetModuleCard} onClick={()=>switchWorkspace("image")}><div className="module-card-head"><span className="module-index">02</span><small><i/>GRAPH ONLINE</small></div><WelcomeModuleVisual type="workflow"/><div className="module-meta"><span>NODE WORKFLOW</span><h2>COMFY WORKFLOW<br/>STUDIO</h2><p>{comfyCard.desc}</p><em>{comfyCard.enter} <b>↗</b></em></div></button>
        <button className="module-card portal-card render-module" onPointerMove={moveModuleCard} onPointerLeave={resetModuleCard} onClick={()=>switchWorkspace("generate")}><div className="module-card-head"><span className="module-index">03</span><small><i/>ENGINE READY</small></div><WelcomeModuleVisual type="render"/><div className="module-meta"><span>IMAGE GENERATION</span><h2>IMAGE RENDER<br/>STUDIO</h2><p>{t("renderModuleDesc")}</p><em>{t("enterRender")} <b>↗</b></em></div></button>
        <button className="module-card portal-card pose-module" onPointerMove={moveModuleCard} onPointerLeave={resetModuleCard} onClick={()=>switchWorkspace("pose")}><div className="module-card-head"><span className="module-index">04</span><small><i/>RIG ACTIVE</small></div><WelcomeModuleVisual type="pose"/><div className="module-meta"><span>CHARACTER POSE</span><h2>POSE RIG<br/>STUDIO</h2><p>{t("poseModuleDesc")}</p><em>{t("enterPose")} <b>↗</b></em></div></button>
      </div>
    </section>:workspaceMode==="image"?<Suspense fallback={<section className="comfy-loading"><i/><b>COMFY WORKFLOW STUDIO</b></section>}><ComfyWorkflowStudio locale={locale} seedPrompt={comfySeedPrompt} seedVersion={comfySeedVersion} pipelineTitle={pipelineSource?.stage==="story"?pipelineSource.title:""}/></Suspense>:workspaceMode==="generate"?<section className="image-studio render-studio">
      <aside className="image-control">
        <span className="eyebrow"><span/> IMAGE RENDER STUDIO</span><h1>{t("imageRenderStudio")}</h1><p className="intro">{t("renderIntro")}</p>
        {(pipelineSource?.stage==="prompt"||pipelineSource?.stage==="pose")&&<div className="pipeline-banner"><i>{pipelineSource.stage==="prompt"?"02 → 03":"04 → 03"}</i><span><b>{pipelineSource.title}</b><small>{pipelineSource.detail}</small></span><em>{pipelineRenderPrompt?t("pipelineReadyDirect"):t("pipelineConnected")}</em></div>}
        {pipelineRenderPrompt&&<label className="pipeline-ready-prompt"><span>{t("readyRenderPrompt")}</span><textarea value={pipelineRenderPrompt} onChange={e=>{setPipelineRenderPrompt(e.target.value);setImagePromptCore(e.target.value);setImagePrompt(e.target.value)}}/><small>{t("directRenderNoRewrite")}</small></label>}
        <label className="field-label">01 / {t("imageWorkflow")}</label><div className="image-workflow-switch">{imageWorkflows.map((value,index)=>{const label=value==="text-to-image"?t("workflowText"):value==="image-to-image"?t("workflowImage"):t("workflowMulti");const description=value==="text-to-image"?t("workflowTextDesc"):value==="image-to-image"?t("workflowImageDesc"):t("workflowMultiDesc");return <button key={value} className={imageWorkflow===value?"selected":""} onClick={()=>changeImageWorkflow(value)}><i>{index===0?"Aa":index===1?"01":"∞"}</i><span><b>{label}</b><small>{description}</small></span><em>0{index+1}</em></button>})}</div>
        {imageWorkflow==="text-to-image"&&<><label className="field-label">02 / {t("imageIdea")}</label><div className="textarea-wrap image-textarea"><textarea value={imageConcept} onChange={e=>setImageConcept(e.target.value)} maxLength={500}/><span>{imageConcept.length}/500</span></div></>}
        <div className="split-fields"><div><label className="field-label">03 / {t("visualStyle")}</label><select value={imageStyle} onChange={e=>setImageStyle(e.target.value)}>{imageStyles.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div><div><label className="field-label">04 / {t("aspect")}</label><select value={imageAspect} onChange={e=>setImageAspect(e.target.value)}>{imageAspects.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div></div>
        <label className="field-label"><span>05 / {imageWorkflow==="text-to-image"?t("workflowText"):imageWorkflow==="image-to-image"?t("sourceImage"):t("multiReferences")}</span>{imageWorkflow!=="text-to-image"&&<b>{referenceCounter}</b>}</label>
        {imageWorkflow==="text-to-image"?<div className="workflow-context-card"><i>Aa</i><span><b>{t("workflowText")}</b><small>{t("workflowTextDesc")}</small></span></div>:<div className="reference-manager"><div className="upload-zone compact-upload reference-upload" role="button" tabIndex={0} onClick={()=>imageFileRef.current?.click()} onKeyDown={e=>{if(e.key==="Enter")imageFileRef.current?.click()}} onDragOver={e=>e.preventDefault()} onDrop={onPromptReferenceDrop}><input ref={imageFileRef} type="file" multiple={imageWorkflow==="multi-reference"} accept="image/jpeg,image/png,image/webp" onChange={e=>{void addPromptReferenceFiles(Array.from(e.target.files||[]));e.currentTarget.value=""}}/><span className="upload-icon">＋</span><b>{imageWorkflow==="image-to-image"?t("addSource"):t("addMultiple")}</b><small>JPG / PNG / WebP · 10MB</small></div>{promptReferences.length>0&&<div className={`reference-grid ${imageWorkflow==="image-to-image"?"single":""}`}>{promptReferences.slice(0,imageWorkflow==="image-to-image"?1:6).map((item,index)=><article className="reference-card" key={item.id}><div className="reference-thumb"><img src={item.src} alt={`${t("referenceImage")} ${index+1}`}/><b>{String(index+1).padStart(2,"0")}</b><button onClick={()=>removePromptReference(item.id)} aria-label={t("close")}>×</button></div><div className="reference-card-body"><span>{item.name}</span>{imageWorkflow==="multi-reference"?<label><small>{t("referenceRole")}</small><select value={item.role} onChange={e=>updatePromptReference(item.id,"role",e.target.value)}>{referenceRoles.map(role=><option key={role} value={role}>{referenceRoleLabel(locale,role)}</option>)}</select></label>:<em>{referenceRoleLabel(locale,"source")}</em>}<input value={item.note} onChange={e=>updatePromptReference(item.id,"note",e.target.value)} placeholder={t("referenceNote")}/></div></article>)}</div>}<label className="reference-direction"><span>{t("globalDirection")}</span><textarea value={imageBriefNotes} onChange={e=>setImageBriefNotes(e.target.value)} placeholder={t("globalDirectionPlaceholder")} maxLength={400}/></label></div>}
        {referenceError&&<p className="upload-error">{referenceError}</p>}<div className="engine-connection"><span className={accountImageConfig?"connected":""}><i/>{accountImageConfig?`${imageGenerationProviderById(accountImageConfig.providerId).name} · ${accountImageConfig.model}`:t("imageEngineMissing")}</span><button onClick={()=>setSettingsOpen(true)}>{accountImageConfig?t("imageEngineSaved"):t("openImageSettings")}</button></div>
        <button className="generate" onClick={()=>pipelineRenderPrompt?renderPipelineImage():generateImagePrompt(true)} disabled={imageGenerating||imageRendering||(!pipelineRenderPrompt&&(!imageWorkflowReady||(imageWorkflow==="text-to-image"&&!imageConcept.trim())))}><span>{imageGenerating||imageRendering?t("renderingImage"):pipelineRenderPrompt?t("directRenderNow"):t("actualImageGeneration")}</span><b>{imageGenerating||imageRendering?"···":"↗"}</b></button><p className="hint">{imageRenderStatus||(pipelineRenderPrompt?t("directRenderNoRewrite"):t("renderDirectHint"))}</p>
      </aside>
      <section className="image-output"><div className="image-output-head"><div><span>OUTPUT / {renderImageModel.toUpperCase()}</span><h2>{imageWorkflow==="text-to-image"?t("workflowText"):imageWorkflow==="image-to-image"?t("workflowImage"):t("workflowMulti")} · {generatedImage?t("imageReady"):t("actualImageGeneration")}</h2></div><div className="image-output-actions">{imagePrompt&&<button className="export" onClick={()=>copy(imagePrompt,"renderPrompt")}>{copied==="renderPrompt"?t("copied"):t("copyPrompt")}</button>}{generatedImage&&<button className="export image-download" onClick={downloadGeneratedImage}>↓ {t("downloadImage")}</button>}</div></div>
        {imageWorkflow!=="text-to-image"&&promptReferences.length>0&&<div className="canvas-reference-strip"><span>{referenceCounter}</span>{promptReferences.slice(0,imageWorkflow==="image-to-image"?1:6).map((item,index)=><div key={item.id}><img src={item.src} alt=""/><b>{index+1}</b><small>{referenceRoleLabel(locale,item.role)}</small></div>)}</div>}<div className={`image-canvas ${imagePrompt&&!generatedImage?"has-prompt":""} ${generatedImage?"has-generated-image":""}`}>{generatedImage?<img className="generated-artwork" src={generatedImage.src} alt={imageConcept||t("actualImageGeneration")}/>:<><div className="canvas-grid"/><div className="canvas-center"><i>◈</i><b>{imagePrompt?"RENDER PROMPT READY":"WAITING FOR A FRAME"}</b><small>{imagePrompt?`${renderImageModel} · ${optionLabel(locale,imageAspect)}`:t("waitingFrame")}</small></div></>}<span className="canvas-corner c1"/><span className="canvas-corner c2"/><span className="canvas-corner c3"/><span className="canvas-corner c4"/>{imageRendering&&<div className="image-render-mask"><i/><b>{t("renderingImage")}</b><span>{imageRenderStatus}</span></div>}</div>{generatedImage&&<div className="generated-image-meta"><span><i/> {t("imageReady")}</span><b>{generatedImage.provider} · {generatedImage.model}</b><button onClick={rerenderImage} disabled={imageRendering}>↻ {t("directGenerate")}</button></div>}{imageRenderStatus&&!imageRendering&&!generatedImage&&<div className="image-render-error"><i>!</i><span>{imageRenderStatus}</span>{imagePromptCore&&<button onClick={rerenderImage}>↻</button>}</div>}{imagePrompt&&<div className="image-prompt-card"><span>MODEL-READY RENDER PROMPT</span><pre>{imagePrompt}</pre><div><b>{renderImageModel}</b><b>{optionLabel(locale,imageStyle)}</b><b>{optionLabel(locale,imageAspect)}</b></div></div>}
      </section>
    </section>:workspaceMode==="pose"?<section className="pose-studio">
      <aside className="pose-control"><span className="eyebrow"><span/> POSE RIG STUDIO</span><h1>{t("poseStudio")}</h1><p className="intro">{t("poseIntro")}</p><label className="field-label">01 / {t("posePrompt")}</label><div className="textarea-wrap image-textarea"><textarea value={poseConcept} onChange={e=>setPoseConcept(e.target.value)} placeholder={t("posePromptPlaceholder")} maxLength={500}/><span>{poseConcept.length}/500</span></div><div className="split-fields"><div><label className="field-label">02 / {t("visualStyle")}</label><select value={poseStyle} onChange={e=>setPoseStyle(e.target.value)}>{imageStyles.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div><div><label className="field-label">03 / {t("aspect")}</label><select value={poseAspect} onChange={e=>setPoseAspect(e.target.value)}>{imageAspects.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div></div><label className="field-label">04 / {t("poseReference")}</label>{poseReference?<div className="image-preview pose-reference-preview"><img src={poseReference.src} alt={t("poseReference")}/><div className="image-info"><b>{poseReference.name}</b><span>{t("poseReferenceLoaded")}</span></div><button onClick={()=>setPoseReference(null)} aria-label={t("close")}>×</button></div>:<div className="upload-zone compact-upload" role="button" tabIndex={0} onClick={()=>poseFileRef.current?.click()} onKeyDown={e=>{if(e.key==="Enter")poseFileRef.current?.click()}}><input ref={poseFileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void readPoseReference(file);e.currentTarget.value=""}}/><span className="upload-icon">＋</span><b>{t("addReference")}</b><small>{t("poseReferenceHint")}</small></div>}<div className="engine-connection"><span className={accountImageConfig?"connected":""}><i/>{accountImageConfig?`${imageGenerationProviderById(accountImageConfig.providerId).name} · ${accountImageConfig.model}`:t("imageEngineMissing")}</span><button onClick={()=>setSettingsOpen(true)}>{t("openImageSettings")}</button></div><button className="generate" onClick={generatePoseImage} disabled={poseGenerating}><span>{poseGenerating?t("generatingPose"):t("usePoseAndRender")}</span><b>{poseGenerating?"···":"↗"}</b></button><p className="hint">{poseStatus||t("poseGenerateHint")}</p></aside>
      <section className="pose-editor">
        <div className="pose-editor-head"><div><span>3D JOINT MANIPULATOR</span><h2>{t("poseEditor")}</h2></div><small>{t("orbitHint")}</small></div>
        <div className="pose-navigation"><div><span>CAMERA / {t("poseCameraView")}</span><section>{rigViews.map(view=><button key={view} className={poseView===view?"active":""} onClick={()=>changePoseView(view)}><i>{view==="front"?"↑":view==="back"?"↓":view==="left"?"←":view==="right"?"→":"⌄"}</i>{t(rigViewKeys[view])}</button>)}</section></div><div><span>BODY / {t("poseCharacterFacing")}</span><section>{rigFacings.map(facing=><button key={facing} className={poseFacing===facing?"active":""} onClick={()=>changePoseFacing(facing)}>{t(rigFacingKeys[facing])}</button>)}</section></div><div><span>DRAG / {t("poseDragMode")}</span><section>{rigDragAxes.map(axis=><button key={axis} className={poseDragAxis===axis?"active":""} onClick={()=>changePoseDragAxis(axis)}><i>{axis==="screen"?"◎":axis.toUpperCase()}</i>{t(rigAxisKeys[axis])}</button>)}</section></div></div>
        <div className="pose-photo-motion"><div className="pose-photo-copy"><i>AI POSE CAPTURE</i><b>{t("poseFromPhoto")}</b><small>{t("poseFromPhotoDesc")}</small></div><input ref={poseMotionFileRef} className="pose-motion-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void readPoseMotionReference(file);e.currentTarget.value=""}}/>{poseMotionReference?<div className="pose-motion-preview"><img src={poseMotionReference.src} alt={t("poseMotionReference")}/><span><b>{poseMotionReference.name}</b><small>{poseMotionStatus}</small></span><button onClick={()=>{setPoseMotionReference(null);setPoseMotionStatus("");setPoseMotionAnalysis("")}} aria-label={t("close")}>×</button></div>:<button className="pose-motion-upload" onClick={()=>poseMotionFileRef.current?.click()}><b>＋</b><span>{t("uploadPosePhoto")}</span></button>}<button className="pose-motion-analyze" onClick={estimatePoseFromImage} disabled={!poseMotionReference||poseEstimating}><span>{poseEstimating?t("poseEstimating"):t("matchPhotoPose")}</span><b>{poseEstimating?"···":"↗"}</b></button>{poseMotionAnalysis&&<p>{poseMotionAnalysis}</p>}{!poseMotionAnalysis&&poseMotionStatus&&<p>{poseMotionStatus}</p>}</div>
        <div className="pose-people-manager"><div><i>MULTI CHARACTER</i><b>{t("posePeople")}</b><small>{t("posePeopleDesc")}</small></div><div className="pose-people-list">{posePeople.map((gender,index)=><button key={`${gender}-${index}`} className={activePosePerson===index?"active":""} onClick={()=>selectPosePerson(index)}><i>{gender==="female"?"♀":"♂"}</i><span>{t("posePerson",{count:index+1})}</span></button>)}<button className="add-person" onClick={addPosePerson} disabled={posePeople.length>=3}>＋ {t("addPosePerson")}</button>{posePeople.length>1&&<button className="remove-person" onClick={removePosePerson}>− {t("removePosePerson")}</button>}</div></div>
        <div className={`pose-anatomy-mode ${poseRealistic?"enabled":"free"}`}><div><i>ANATOMY</i><b>{t("realisticSkeleton")}</b><small>{t(poseRealistic?"realisticSkeletonOn":"realisticSkeletonOff")}</small></div><button type="button" role="switch" aria-checked={poseRealistic} aria-label={`${t("realisticSkeleton")}: ${t(poseRealistic?"realisticSkeletonOn":"realisticSkeletonOff")}`} onClick={togglePoseRealism}><span/><em>{poseRealistic?"ON":"OFF"}</em></button></div>
        <div className="pose-preset-library"><div className="pose-library-head"><div><i>QUICK POSE LIBRARY</i><b>{t("posePresetLibrary")}</b></div><div className="pose-gender-switch">{(["female","male"] as PoseGender[]).map(gender=><button key={gender} className={poseGender===gender?"active":""} aria-pressed={poseGender===gender} onClick={()=>changePoseBodyType(gender)}><i>{gender==="female"?"♀":"♂"}</i>{t(gender==="female"?"poseGenderFemale":"poseGenderMale")}</button>)}</div></div><div className="pose-category-tabs">{poseCategories.map((category,index)=><button key={category} className={poseCategory===category?"active":""} aria-pressed={poseCategory===category} onClick={()=>setPoseCategory(category)}><i>0{index+1}</i>{t(poseCategoryKeys[category])}</button>)}</div><div className="pose-subpreset-grid">{POSE_PRESET_LIBRARY.filter(item=>item.gender===poseGender&&item.category===poseCategory).map(item=><button key={item.id} className={activePosePreset===item.id?"active":""} aria-pressed={activePosePreset===item.id} onClick={()=>selectPosePreset(item.id)}><i>{poseGender==="female"?"♀":"♂"} 0{item.index}</i><b>{t(item.labelKey)}</b><small>{t(poseCategoryKeys[item.category])}</small></button>)}</div><div className="pose-library-tools"><button onClick={mirrorCurrentPose}><i>↔</i>{t("mirrorPose")}</button><button onClick={resetCurrentPose}><i>↺</i>{t("resetPose")}</button><button className="pose-pipeline-send" onClick={sendPoseToRender}><i>04 → 03</i>{t("sendPoseToRender")}</button></div></div>
        <div className="pose-stage"><PoseErrorBoundary fallback={<div className="pose-loading pose-failed"><b>!</b><span>{t("poseCaptureFailed")}</span></div>}><Suspense fallback={<div className="pose-loading"><i/><span>{t("poseEditor")}</span></div>}><PoseRig ref={poseRigRef} ariaLabel={t("poseEditor")} realistic={poseRealistic} onPoseChange={()=>setActivePosePreset("custom")} onPeopleChange={(people,active)=>{setPosePeople(people);setActivePosePerson(active);setPoseGender(people[active]||"female")}}/></Suspense></PoseErrorBoundary><div className="pose-stage-label"><i/><span>{poseRealistic?"HUMAN MANNEQUIN · IK":"HUMAN MANNEQUIN · FREE"}</span></div><div className="pose-axis"><b>Y</b><span>X</span><em>Z</em></div></div>
      </section>
      <section className="pose-output"><div className="pose-output-head"><div><span>POSE-GUIDED OUTPUT</span><h2>{poseResult?t("poseReady"):t("poseResult")}</h2></div>{poseResult&&<button className="export" onClick={()=>downloadImageResult(poseResult,"FRAME-POSE")}>↓ {t("downloadImage")}</button>}</div><div className={`pose-result-frame ${poseResult?"ready":""}`}>{poseResult?<img src={poseResult.src} alt={poseConcept}/>:<div><i>◇</i><b>{t("poseWaiting")}</b><span>{t("poseWaitingDesc")}</span></div>}{poseGenerating&&<div className="image-render-mask"><i/><b>{t("generatingPose")}</b><span>{poseStatus}</span></div>}</div>{poseResult&&<div className="generated-image-meta"><span><i/> {t("poseReady")}</span><b>{poseResult.provider} · {poseResult.model}</b></div>}{posePrompt&&<div className="pose-prompt-card"><span>POSE-AWARE IMAGE PROMPT</span><p>{posePrompt}</p><button onClick={()=>copy(posePrompt,"posePrompt")}>{copied==="posePrompt"?t("copied"):t("copyPrompt")}</button></div>}</section>
    </section>:<section className="workspace">
      <aside className="control-panel"><div className="eyebrow"><span/> NEW PROJECT</div><h1>{t("turnIdea")}</h1><p className="intro">{t("storyIntro")}</p>
        <label className="field-label"><span>01 / {t("coreIdea")}</span><button className="text-action mentor-action" onClick={askIdeaMentor} disabled={mentorLoading}><span>{mentorLoading?t("mentorThinking"):t("ideaMentor")}</span><b aria-hidden="true">✦</b></button></label><div className="textarea-wrap"><textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder={t("coreIdeaPlaceholder")} maxLength={300} aria-label={t("coreIdea")}/><span>{idea.length}/300</span></div>{mentorSuggestion&&<div className="mentor-suggestion"><span><i>✦</i> {t("mentorSuggestion")}</span><b>{mentorSuggestion.hook}</b><p>{mentorSuggestion.suggestion}</p><div><button onClick={()=>setMentorSuggestion(null)}>{t("dismiss")}</button><button onClick={useMentorSuggestion}>{t("useSuggestion")} <i>↗</i></button></div></div>}
        <label className="field-label"><span>02 / {t("visualReference")}</span><b>{t("aiUnderstands")}</b></label>{image?<div className="image-preview"><img src={image.src} alt={t("visualReference")}/><div className="image-info"><b>{image.name}</b><span>{image.width}×{image.height} · {image.orientation} · {image.size}</span><span>{image.tone} · {image.color}</span></div><button onClick={()=>{setImage(null);setImageNotes("")}} aria-label={t("close")}>×</button></div>:<div className="upload-zone" role="button" tabIndex={0} onClick={()=>fileRef.current?.click()} onKeyDown={e=>{if(e.key==="Enter")fileRef.current?.click()}} onDragOver={e=>e.preventDefault()} onDrop={onDrop}><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)readImage(f)}}/><span className="upload-icon">＋</span><b>{t("dropImage")}</b><small>{t("maxImage")}</small></div>}{uploadError&&<p className="upload-error">{uploadError}</p>}{image&&<input className="reference-note" value={imageNotes} onChange={e=>setImageNotes(e.target.value)} placeholder={t("referenceNote")}/>}
        <div className="split-fields"><div><label className="field-label">03 / {t("genre")}</label><select value={genre} onChange={e=>setGenre(e.target.value)}>{genres.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div><div><label className="field-label">04 / {t("visualStyle")}</label><select value={style} onChange={e=>setStyle(e.target.value)}>{styles.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div></div>
        <label className="field-label">05 / {t("duration")} <b>{duration} {t("seconds")}</b></label><input className="range" type="range" min="15" max="60" step="15" value={duration} onChange={e=>setDuration(Number(e.target.value))}/><div className="ticks"><span>15s</span><span>30s</span><span>45s</span><span>60s</span></div>
        <div className="split-fields"><div><label className="field-label">06 / {t("platform")}</label><select value={platform} onChange={e=>setPlatform(e.target.value)}>{platforms.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div><div><label className="field-label">07 / {t("promptFormat")}</label><select value={model} onChange={e=>setModel(e.target.value)}>{models.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div></div>
        <label className="lock-option"><span><b>{t("consistency")}</b><small>{t("consistencyHint")}</small></span><input type="checkbox" checked={lock} onChange={e=>setLock(e.target.checked)}/><i/></label>
        <button className="generate" onClick={generate} disabled={generating||!idea.trim()}><span>{generating?t("generatingStory"):image?t("generateWithImage"):t("generateStory")}</span><b>{generating?"···":"↗"}</b></button><p className="hint">{t("realGeneration")}</p>
      </aside>
      <section className={`result-panel ${generating?"is-generating":""}`} key={version} aria-busy={generating}><div className="result-head"><div className="tabs"><button className={activeTab==="story"?"active":""} onClick={()=>setActiveTab("story")}>{t("outline")}</button><button className={activeTab==="shots"?"active":""} onClick={()=>setActiveTab("shots")}>{t("shotScript")} <small>{shots.length}</small></button></div><div className="result-actions"><span className="result-notice" aria-live="polite">{notice}</span><button className="export" onClick={copyAll}>{copied==="all"?t("copied"):t("copyAll")}</button><button className="export" onClick={exportText}>↓ {t("export")}</button></div></div>
        {generating&&<div className="generating-mask"><i/><b>{notice}</b><span>{t("organizing")}</span></div>}
        {version===0&&!generating&&<div className="result-empty-state"><div className="empty-orbit"><i/><i/><i/><b>F</b></div><span>FRAME / ORIGINAL GENERATION</span><h2>{t("awaitingTitle")}</h2><p>{t("awaitingDesc")}</p><em>{t("awaitingAction")} <b>↗</b></em></div>}
        <div className={version===0?"pre-generation-hidden":""}>
        {activeTab==="story"?<div className="story-view">{image&&<div className="reference-ribbon"><img src={image.src} alt={t("visualReference")}/><div><span>VISUAL REFERENCE CONNECTED</span><b>{image.name}</b></div><em>{image.orientation} · {image.tone} · {image.color}</em></div>}<div className="story-hero"><div><span className="tag">{optionLabel(locale,genre)}</span><span className="tag">{optionLabel(locale,style)}</span><span className="tag">{duration} {t("seconds")}</span><span className="tag">{optionLabel(locale,platform)}</span><span className="tag accent-tag">{optionLabel(locale,model)}</span></div><h2>{story.title}</h2><p>{story.logline}</p><div className="direction-card"><span>CREATIVE DIRECTION</span><p>{story.direction}</p></div>{story.visualAnalysis&&<div className="visual-analysis-card"><span>AI VISUAL REFERENCE ANALYSIS</span><p>{story.visualAnalysis}</p></div>}<button className="story-pipeline-send" onClick={()=>prepareStoryForComfy()}>{comfyCard.sendStory} <b>01 → 02</b></button></div><div className="hook-card"><span>{t("hook")} / HOOK</span><blockquote>“{story.hook}”</blockquote><button onClick={()=>copy(story.hook,"hook")}>{copied==="hook"?t("copied"):t("copy")}</button></div><div className="structure"><h3>{t("narrative")}</h3>{story.structure.map((item,i)=><article key={item[0]}><b>0{i+1}</b><div><h4>{item[0]}</h4><p>{item[1]}</p></div><span>{story.structureTimes?.[i]||`${Math.round(i*duration/story.structure.length)}—${Math.round((i+1)*duration/story.structure.length)}s`}</span></article>)}</div><button className="to-shots" onClick={()=>setActiveTab("shots")}>{t("viewShots")} <span>→</span></button></div>:<div className="shots-view"><div className="shot-title"><div><span className="eyebrow">SHOT LIST · {optionLabel(locale,genre).toUpperCase()} · {optionLabel(locale,style).toUpperCase()}</span><h2>{story.title} · {t("shotScript")}</h2></div><span>{t("totalShots",{count:shots.length,seconds:duration})}</span></div>{shots.map(shot=><article className="shot-card" key={shot.id}><div className="shot-no"><span>SHOT</span><b>{String(shot.id).padStart(2,"0")}</b><em>{shot.time}</em></div><div className="shot-content"><span className="shot-type">{shot.shot}</span><h3>{shot.visual}</h3><div className="shot-meta"><p><b>{t("camera")}</b>{shot.camera}</p><p><b>{t("sound")}</b>{shot.audio}</p></div><div className="prompt"><span>MODEL-READY VIDEO PROMPT · {model.toUpperCase()}</span><pre>{shot.prompt}</pre><button onClick={()=>copy(shot.prompt,`shot${shot.id}`)}>{copied===`shot${shot.id}`?t("copied"):t("copy")}</button><button className="shot-pipeline-send" onClick={()=>prepareStoryForComfy(shot)}>{comfyCard.sendShot} <b>01 → 02</b></button></div></div></article>)}</div>}
        </div>
      </section>
    </section>}
  </main>;
}
