"use client";

import { useEffect, useRef, useState, type CSSProperties, type DragEvent, type PointerEvent } from "react";

type Shot = { id:number; time:string; shot:string; visual:string; camera:string; audio:string; prompt:string };
type Story = { title:string; logline:string; hook:string; structure:[string,string][] };
type Theme = "light"|"dark"|"system";
type Backdrop = "none"|"globe"|"mind";
type User = { displayName:string; email:string; userId:string } | null;
type ImageInfo = { src:string; name:string; width:number; height:number; orientation:string; color:string; tone:string; size:string };

const genres = ["悬疑惊悚", "科幻未来", "治愈情感", "古风奇幻", "都市反转", "搞笑脑洞"];
const styles = ["电影写实", "日系动漫", "3D 动画", "赛博朋克", "水墨国风", "复古胶片"];
const platforms = ["抖音 / TikTok", "小红书", "B站", "YouTube Shorts", "横屏短片"];
const models = ["通用视频模型", "Sora", "Veo", "Kling", "Runway"];
const ideas = [
  "每天午夜，城市里会有一个人的影子突然消失，而只有一名失眠的摄影师能看见。",
  "一台废弃的自动售货机可以出售人生中被遗忘的五分钟，但每人只能购买一次。",
  "古代画师发现自己画下的山河会在第二天真实消失，于是决定画出一条不存在的归途。",
  "一只流浪猫每天把不同世界的钥匙放在女孩门口，直到最后一把刻着她的名字。",
  "未来世界禁止做梦，一名梦境修复师却在客户记忆里发现了童年时的自己。",
];
const sampleIdea = "一个女孩捡到能让时间倒流三分钟的怀表，却发现每使用一次，就会失去一段关于家人的记忆。";

const stylePrompts:Record<string,string> = {
  "电影写实":"cinematic photorealism, 35mm film texture, natural skin detail, motivated practical lighting",
  "日系动漫":"premium Japanese animated feature, expressive acting, detailed painted background, soft cinematic light",
  "3D 动画":"stylized high-end 3D animation, expressive features, global illumination, physically coherent render",
  "赛博朋克":"restrained cyberpunk cinema, neon reflections, deep shadows, volumetric atmosphere, wet surfaces",
  "水墨国风":"Chinese ink-wash visual language, poetic negative space, flowing brush texture, cinematic depth",
  "复古胶片":"vintage analog cinema, muted colors, halation, tactile grain, nostalgic practical lighting",
};

function subjectOf(text:string){ return text.trim().replace(/[。！？!?]/g,"").slice(0,30)||"一个意外改变命运的人"; }
function titleOf(text:string){ const clean=text.replace(/[，。！？、,.!?\s]/g,""); const clues=["时间","记忆","秘密","消失","重逢","梦","门","信","光","影子"]; const clue=clues.find(x=>clean.includes(x)); return `《${clue?`最后的${clue}`:clean.slice(0,7)||"未命名故事"}》`; }
function buildStory(idea:string,genre:string):Story{ const subject=subjectOf(idea); return { title:titleOf(idea), logline:`${subject}。在一场无法回头的选择中，主人公必须直面隐藏的代价，并在失去一切之前完成最后的决定。`, hook:`如果“${subject.slice(0,18)}”并不是偶然，而是一场早已安排好的交换呢？`, structure:[["开场钩子",`用反常瞬间直接呈现核心设定：${subject}。异常细节在前 3 秒被放大。`],["冲突升级",`主人公尝试改变现状，却发现每前进一步都会触发新的代价，${genre}氛围持续加深。`],["高潮反转","此前被忽略的细节突然串联：真正需要被拯救的并不是表面目标，而是主人公自己。"],["余韵收束",`主人公作出不可逆的选择。最后画面呼应“${subject.slice(0,12)}”，留下开放式问题。`]]}; }

function buildShots(idea:string,genre:string,style:string,duration:number,model:string,image:ImageInfo|null,imageNotes:string,lock:boolean):Shot[]{
  const count=Math.max(4,Math.min(8,Math.round(duration/7))); const subject=subjectOf(idea); const each=duration/count;
  const beats=[`异常细节首次出现，暗示“${subject}”，主人公尚未意识到危险。`,`主人公察觉异常并确认眼前发生的事，环境中的视线被引向核心线索。`,`行动开始。主人公穿过熟悉却突然陌生的空间，代价以可见变化出现。`,`新的线索揭露：最信任的人隐瞒了关键信息，故事目标发生偏转。`,`主人公逼近真相，空间与情绪同时收紧，最初细节再次出现但含义相反。`,`高潮选择到来。主人公触碰核心物件，在得到与失去之间停顿一秒。`,`选择完成，世界恢复平静，但某个重要的人或事已被彻底改变。`,`以安静的极近景结束，留下与“${subject.slice(0,12)}”有关的最后疑问。`];
  const cameras=["extreme close-up, slow controlled push-in, shallow depth of field","medium shot, lateral dolly followed by a deliberate push-in","handheld follow shot transitioning into a slow orbit","locked symmetrical two-shot followed by a sudden rack focus","low-angle tracking shot with foreground wipe transitions","wide shot rapidly resolving into an intimate close-up","high-angle shot slowly pulling away from the subject","extreme macro hold, brief overexposure, cut to black"];
  const audios=["环境声瞬间抽离，只保留被放大的细节声","低频氛围渐入；一句短促的疑问台词","急促脚步、呼吸与逐渐加快的节拍","音乐骤停；关键人物说出半句真相","低频持续上升，远处传来熟悉的声音","心跳声放大，关键动作发生时完全静音","主题旋律以残缺版本回归","清晰的物件声；片尾问题字幕出现"];
  const shotNames=["极特写","中景","跟拍","双人景","大全景","特写","远景","极特写"];
  return Array.from({length:count},(_,i)=>{ const start=Math.round(i*each),end=Math.round((i+1)*each),seconds=Math.max(2,end-start); const visual=beats[i]; const reference=image?`REFERENCE IMAGE: Use the attached image as the primary visual reference. Preserve its ${image.orientation} composition, ${image.tone} exposure and dominant ${image.color} palette.${imageNotes?` User reference note: ${imageNotes}.`:" Do not change identifiable visual anchors."}`:"REFERENCE: No image supplied; establish a coherent visual world from the story brief."; const continuity=lock?"CONTINUITY: Lock protagonist identity, face, hairstyle, wardrobe, props, scale and color palette across every shot.":"CONTINUITY: Maintain coherent geography and lighting progression across adjacent shots."; return { id:i+1,time:`00:${String(start).padStart(2,"0")}–00:${String(end).padStart(2,"0")}`,shot:shotNames[i],visual,camera:cameras[i],audio:audios[i],prompt:`[${model.toUpperCase()} · SHOT ${String(i+1).padStart(2,"0")} · ${seconds} SECONDS]\nSUBJECT & ACTION: ${visual}\nSTORY CONTEXT: ${subject}. Genre is ${genre}.\n${reference}\nCAMERA: ${cameras[i]}; 24fps; natural cinematic motion blur; intentional focus transition.\nLOOK & LIGHTING: ${stylePrompts[style]}; physically consistent shadows; controlled highlight roll-off.\n${continuity}\nCOMPOSITION: ${duration<=60?"vertical 9:16, mobile-first focal placement, safe center framing":"cinematic 16:9, layered depth and deliberate negative space"}.\nMOTION & PHYSICS: One clear action beat; stable anatomy and object geometry; believable weight, inertia and environmental response.\nAVOID: subtitles, captions, logos, watermarks, flicker, frame warping, duplicate limbs, face drift, random objects, abrupt exposure shifts, unmotivated camera movement.`}; });
}

function BackdropVisual({mode}:{mode:Backdrop}){
  if(mode==="globe") return <div className="scene globe-scene" aria-hidden="true"><div className="globe"><i className="orbit o1"/><i className="orbit o2"/><i className="orbit o3"/><i className="axis"/><span className="gdot d1"/><span className="gdot d2"/><span className="gdot d3"/></div><div className="scene-label">ORBITAL STORY MAP · LIVE</div></div>;
  if(mode==="mind") return <div className="scene mind-scene" aria-hidden="true"><div className="mind-shell"><div className="hemi left"/><div className="hemi right"/>{Array.from({length:14},(_,i)=><i className={`node n${i+1}`} key={i}/>)}{Array.from({length:10},(_,i)=><span className={`synapse s${i+1}`} key={i}/>)}</div><div className="scene-label">NARRATIVE NEURAL FIELD · THINKING</div></div>;
  return null;
}

export default function Studio({user}:{user:User}){
  const [activeTab,setActiveTab]=useState<"story"|"shots">("story"); const [idea,setIdea]=useState(sampleIdea); const [genre,setGenre]=useState(genres[0]); const [style,setStyle]=useState(styles[0]); const [platform,setPlatform]=useState(platforms[0]); const [duration,setDuration]=useState(30); const [model,setModel]=useState(models[0]); const [lock,setLock]=useState(true);
  const [story,setStory]=useState(()=>buildStory(sampleIdea,genres[0])); const [shots,setShots]=useState(()=>buildShots(sampleIdea,genres[0],styles[0],30,models[0],null,"",true)); const [generating,setGenerating]=useState(false); const [copied,setCopied]=useState(""); const [notice,setNotice]=useState("示例内容"); const [version,setVersion]=useState(0);
  const [theme,setThemeState]=useState<Theme>("system"); const [themeOpen,setThemeOpen]=useState(false); const [backdrop,setBackdropState]=useState<Backdrop>("none"); const [brandOpen,setBrandOpen]=useState(false); const [profileOpen,setProfileOpen]=useState(false);
  const [image,setImage]=useState<ImageInfo|null>(null); const [imageNotes,setImageNotes]=useState(""); const [uploadError,setUploadError]=useState(""); const fileRef=useRef<HTMLInputElement>(null);

  useEffect(()=>{ const saved=(localStorage.getItem("frame-theme") as Theme|null)||"system"; setThemeState(saved); const media=window.matchMedia("(prefers-color-scheme: dark)"); const apply=()=>{document.documentElement.dataset.theme=saved==="system"?(media.matches?"dark":"light"):saved}; apply(); media.addEventListener("change",apply); return()=>media.removeEventListener("change",apply); },[]);
  useEffect(()=>{ const saved=(localStorage.getItem("frame-backdrop") as Backdrop|null)||"none"; setBackdropState(saved); },[]);
  function setTheme(value:Theme){setThemeState(value);localStorage.setItem("frame-theme",value);const dark=value==="dark"||(value==="system"&&matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.dataset.theme=dark?"dark":"light";setThemeOpen(false)}
  function setBackdrop(value:Backdrop){setBackdropState(value);localStorage.setItem("frame-backdrop",value);setBrandOpen(false)}
  function trackLight(e:PointerEvent<HTMLElement>){e.currentTarget.style.setProperty("--mx",`${e.clientX}px`);e.currentTarget.style.setProperty("--my",`${e.clientY}px`)}
  function generate(){if(!idea.trim())return;setGenerating(true);setNotice(image?"正在融合图片参考…":"正在拆解创意…");setTimeout(()=>{setStory(buildStory(idea,genre));setShots(buildShots(idea,genre,style,duration,model,image,imageNotes,lock));setVersion(v=>v+1);setGenerating(false);setNotice(image?"已融合图片视觉特征":"已根据创意重新生成");setActiveTab("story")},1000)}
  async function copy(text:string,label:string){await navigator.clipboard.writeText(text);setCopied(label);setTimeout(()=>setCopied(""),1400)}
  function copyAll(){copy(shots.map(s=>`SHOT ${String(s.id).padStart(2,"0")}\n${s.prompt}`).join("\n\n──────────\n\n"),"all")}
  function exportText(){const content=`${story.title}\n\n核心创意：${idea}\n模型格式：${model}\n视觉参考：${image?`${image.name} / ${image.orientation} / ${image.color}`:"无"}\n\n${shots.map(s=>`镜头 ${s.id}｜${s.time}｜${s.shot}\n画面：${s.visual}\n运镜：${s.camera}\n声音：${s.audio}\n提示词：\n${s.prompt}`).join("\n\n")}`;const blob=new Blob([content],{type:"text/plain;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${story.title.replace(/[《》]/g,"")}-分镜脚本.txt`;a.click();URL.revokeObjectURL(a.href)}
  function inspire(){setIdea(ideas[Math.floor(Math.random()*ideas.length)]);setNotice("已放入一个随机灵感")}
  function readImage(file:File){setUploadError("");if(!file.type.startsWith("image/")){setUploadError("请选择 JPG、PNG 或 WebP 图片");return}if(file.size>10*1024*1024){setUploadError("图片不能超过 10MB");return}const reader=new FileReader();reader.onload=()=>{const src=String(reader.result);const img=new Image();img.onload=()=>{const canvas=document.createElement("canvas");canvas.width=40;canvas.height=40;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.drawImage(img,0,0,40,40);const px=ctx.getImageData(0,0,40,40).data;let r=0,g=0,b=0,n=0;for(let i=0;i<px.length;i+=16){r+=px[i];g+=px[i+1];b+=px[i+2];n++}r=Math.round(r/n);g=Math.round(g/n);b=Math.round(b/n);const brightness=Math.round(.299*r+.587*g+.114*b);const orientation=img.width>img.height*1.15?"landscape":img.height>img.width*1.15?"portrait":"square";setImage({src,name:file.name,width:img.width,height:img.height,orientation,color:`RGB(${r}, ${g}, ${b})`,tone:brightness>175?"high-key":brightness<80?"low-key":"balanced",size:`${(file.size/1024/1024).toFixed(1)}MB`});setNotice("图片视觉特征已读取")};img.src=src};reader.readAsDataURL(file)}
  function onDrop(e:DragEvent<HTMLDivElement>){e.preventDefault();const file=e.dataTransfer.files[0];if(file)readImage(file)}
  const initials=(user?.displayName||user?.email||"访客").slice(0,1).toUpperCase(); const themeLabel={light:"白天",dark:"黑夜",system:"跟随系统"}[theme];

  return <main onPointerMove={trackLight} className={`backdrop-${backdrop}`}>
    <BackdropVisual mode={backdrop}/><div className="ambient ambient-one"/><div className="ambient ambient-two"/><div className="noise"/>
    <header className="topbar">
      <div className="brand-area"><button className="brand" onClick={()=>{setBrandOpen(v=>!v);setThemeOpen(false);setProfileOpen(false)}} aria-expanded={brandOpen} aria-label="FRAME 背景模式"><span className="brand-symbol"><b>F</b><i/></span><span className="brand-word">FRAME</span><em>AI STORY STUDIO</em></button>{brandOpen&&<div className="brand-menu popover"><span className="popover-title">背景模式</span><button className={backdrop==="none"?"selected":""} onClick={()=>setBackdrop("none")}><i className="mini blank"/><span><b>纯净画布</b><small>专注创作</small></span></button><button className={backdrop==="globe"?"selected":""} onClick={()=>setBackdrop("globe")}><i className="mini globe-mini"/><span><b>轨道星球</b><small>世界观模式</small></span></button><button className={backdrop==="mind"?"selected":""} onClick={()=>setBackdrop("mind")}><i className="mini mind-mini"/><span><b>神经思维</b><small>灵感发散模式</small></span></button></div>}</div>
      <div className="top-actions"><button className="ghost">创作历史</button><div className="theme-wrap"><button className="utility-button" onClick={()=>{setThemeOpen(v=>!v);setBrandOpen(false);setProfileOpen(false)}} aria-label="切换网站主题"><span className="theme-icon">{theme==="dark"?"◐":theme==="light"?"☼":"◒"}</span><small>{themeLabel}</small></button>{themeOpen&&<div className="theme-menu popover"><span className="popover-title">网站格调</span>{(["light","dark","system"] as Theme[]).map(x=><button key={x} className={theme===x?"selected":""} onClick={()=>setTheme(x)}><i>{x==="light"?"☼":x==="dark"?"◐":"◒"}</i><span>{x==="light"?"白天":x==="dark"?"黑夜":"跟随系统"}</span><b>✓</b></button>)}</div>}</div><div className="profile-wrap"><button className="avatar" onClick={()=>{setProfileOpen(v=>!v);setThemeOpen(false);setBrandOpen(false)}} aria-label="查看用户资料">{initials}</button>{profileOpen&&<div className="profile-card popover"><div className="profile-head"><span className="profile-avatar">{initials}</span><div><b>{user?.displayName||"访客"}</b><small>{user?.email||"未检测到登录信息"}</small></div></div>{user?<><dl><div><dt>账户状态</dt><dd><i/>已通过 ChatGPT 登录</dd></div><div><dt>个人标识</dt><dd>{user.userId.slice(0,8)}••••</dd></div></dl><a href="/signout-with-chatgpt?return_to=/">退出登录</a></>:<a href="/signin-with-chatgpt?return_to=/">使用 ChatGPT 登录</a>}</div>}</div></div>
    </header>
    <section className="workspace">
      <aside className="control-panel"><div className="eyebrow"><span/> NEW PROJECT</div><h1>把一个灵感<br/>变成一支影片。</h1><p className="intro">从剧情结构到镜头提示词，为 AI 视频创作者打造的前期工作台。</p>
        <label className="field-label"><span>01 / 核心创意</span><button className="text-action" onClick={inspire}>✦ 随机灵感</button></label><div className="textarea-wrap"><textarea value={idea} onChange={e=>setIdea(e.target.value)} maxLength={300} aria-label="核心创意"/><span>{idea.length}/300</span></div>
        <label className="field-label"><span>02 / 视觉参考</span><b>本地处理 · 不上传</b></label>{image?<div className="image-preview"><img src={image.src} alt="用户上传的视觉参考"/><div className="image-info"><b>{image.name}</b><span>{image.width}×{image.height} · {image.orientation} · {image.size}</span><span>{image.tone} · {image.color}</span></div><button onClick={()=>{setImage(null);setImageNotes("")}} aria-label="移除图片">×</button></div>:<div className="upload-zone" role="button" tabIndex={0} onClick={()=>fileRef.current?.click()} onKeyDown={e=>{if(e.key==="Enter")fileRef.current?.click()}} onDragOver={e=>e.preventDefault()} onDrop={onDrop}><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)readImage(f)}}/><span className="upload-icon">＋</span><b>点击或拖入参考图片</b><small>JPG / PNG / WebP · 最大 10MB</small></div>}{uploadError&&<p className="upload-error">{uploadError}</p>}{image&&<input className="reference-note" value={imageNotes} onChange={e=>setImageNotes(e.target.value)} placeholder="补充图片中的人物、场景或需要保留的元素（推荐）"/>}
        <div className="split-fields"><div><label className="field-label">03 / 题材</label><select value={genre} onChange={e=>setGenre(e.target.value)}>{genres.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="field-label">04 / 视觉风格</label><select value={style} onChange={e=>setStyle(e.target.value)}>{styles.map(x=><option key={x}>{x}</option>)}</select></div></div>
        <label className="field-label">05 / 成片时长 <b>{duration} 秒</b></label><input className="range" type="range" min="15" max="60" step="15" value={duration} onChange={e=>setDuration(Number(e.target.value))}/><div className="ticks"><span>15s</span><span>30s</span><span>45s</span><span>60s</span></div>
        <div className="split-fields"><div><label className="field-label">06 / 发布平台</label><select value={platform} onChange={e=>setPlatform(e.target.value)}>{platforms.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="field-label">07 / 提示词格式</label><select value={model} onChange={e=>setModel(e.target.value)}>{models.map(x=><option key={x}>{x}</option>)}</select></div></div>
        <label className="lock-option"><span><b>角色一致性锁定</b><small>统一人物、服装、道具与色彩</small></span><input type="checkbox" checked={lock} onChange={e=>setLock(e.target.checked)}/><i/></label>
        <button className="generate" onClick={generate} disabled={generating||!idea.trim()}><span>{generating?"正在生成，请稍候…":image?"融合图片，生成剧情与分镜":"生成剧情与分镜"}</span><b>{generating?"···":"↗"}</b></button><p className="hint">图片仅在当前浏览器处理 · 内容可自由导出</p>
      </aside>
      <section className={`result-panel ${generating?"is-generating":""}`} key={version} aria-busy={generating}><div className="result-head"><div className="tabs"><button className={activeTab==="story"?"active":""} onClick={()=>setActiveTab("story")}>剧情大纲</button><button className={activeTab==="shots"?"active":""} onClick={()=>setActiveTab("shots")}>分镜脚本 <small>{shots.length}</small></button></div><div className="result-actions"><span className="result-notice">{notice}</span><button className="export" onClick={copyAll}>{copied==="all"?"已复制":"复制全部提示词"}</button><button className="export" onClick={exportText}>↓ 导出</button></div></div>
        {generating&&<div className="generating-mask"><i/><b>{notice}</b><span>正在组织剧情节奏、视觉参考、镜头运动与模型指令</span></div>}
        {activeTab==="story"?<div className="story-view">{image&&<div className="reference-ribbon"><img src={image.src} alt="视觉参考缩略图"/><div><span>VISUAL REFERENCE CONNECTED</span><b>{image.name}</b></div><em>{image.orientation} · {image.tone} · {image.color}</em></div>}<div className="story-hero"><div><span className="tag">{genre}</span><span className="tag">{duration} 秒</span><span className="tag">{platform}</span><span className="tag accent-tag">{model}</span></div><h2>{story.title}</h2><p>{story.logline}</p></div><div className="hook-card"><span>开场钩子 / HOOK</span><blockquote>“{story.hook}”</blockquote><button onClick={()=>copy(story.hook,"hook")}>{copied==="hook"?"已复制":"复制"}</button></div><div className="structure"><h3>叙事结构</h3>{story.structure.map((item,i)=><article key={item[0]}><b>0{i+1}</b><div><h4>{item[0]}</h4><p>{item[1]}</p></div><span>{`${Math.round(i*duration/4)}–${Math.round((i+1)*duration/4)}s`}</span></article>)}</div><button className="to-shots" onClick={()=>setActiveTab("shots")}>查看完整分镜脚本 <span>→</span></button></div>:<div className="shots-view"><div className="shot-title"><div><span className="eyebrow">SHOT LIST · {model.toUpperCase()}</span><h2>{story.title} · 分镜脚本</h2></div><span>共 {shots.length} 镜 · {duration} 秒</span></div>{shots.map(shot=><article className="shot-card" key={shot.id}><div className="shot-no"><span>SHOT</span><b>{String(shot.id).padStart(2,"0")}</b><em>{shot.time}</em></div><div className="shot-content"><span className="shot-type">{shot.shot}</span><h3>{shot.visual}</h3><div className="shot-meta"><p><b>运镜</b>{shot.camera}</p><p><b>声音</b>{shot.audio}</p></div><div className="prompt"><span>MODEL-READY VIDEO PROMPT</span><pre>{shot.prompt}</pre><button onClick={()=>copy(shot.prompt,`shot${shot.id}`)}>{copied===`shot${shot.id}`?"已复制":"复制"}</button></div></div></article>)}</div>}
      </section>
    </section>
  </main>;
}
