"use client";

import { Component, lazy, Suspense, useEffect, useRef, useState, type CSSProperties, type DragEvent, type PointerEvent, type ReactNode } from "react";
import { MODEL_PROVIDERS, detectModelBrand, providerById } from "./model-providers";
import { IMAGE_GENERATION_PROVIDERS, imageGenerationProviderById, imagePromptFamily } from "./image-generation-providers";
import { LANGUAGE_OPTIONS, optionLabel, preferredLocale, referenceRoleLabel, translate, type Locale } from "./i18n";
import type { PosePreset, PoseRigHandle } from "./PoseRig";

const PoseRig=lazy(()=>import("./PoseRig"));

class PoseErrorBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{
  state={failed:false};
  static getDerivedStateFromError(){return{failed:true}}
  componentDidCatch(error:unknown){console.error("Pose rig failed to initialize",error)}
  render(){return this.state.failed?this.props.fallback:this.props.children}
}

type Shot = { id:number; time:string; shot:string; visual:string; camera:string; audio:string; prompt:string };
type Story = { title:string; logline:string; hook:string; direction:string; structure:[string,string][]; structureTimes?:string[]; visualAnalysis?:string };
type Theme = "light"|"dark"|"system";
type Backdrop = "none"|"globe"|"mind";
type WorkspaceMode = "home"|"story"|"image"|"generate"|"pose";
type ImageWorkflow = "text-to-image"|"image-to-image"|"multi-reference";
type User = { displayName:string; email:string; userId:string } | null;
type ImageInfo = { src:string; name:string; width:number; height:number; orientation:string; color:string; tone:string; size:string };
type PromptReference = ImageInfo & { id:string; role:string; note:string };
type ModelOption = { id:string; name:string; vision:boolean };
type AccountModelConfig = { providerId:string; apiBaseUrl:string; model:string; hasApiKey:boolean; updatedAt:string };
type AccountImageConfig = { providerId:string; apiBaseUrl:string; model:string; hasApiKey:boolean; updatedAt:string };
type GeneratedImage = { src:string; model:string; provider:string };

function sameApiEndpoint(a:string,b:string){return a.trim().replace(/\/+$/,"").toLowerCase()===b.trim().replace(/\/+$/,"").toLowerCase()}

const genres = ["悬疑惊悚", "科幻未来", "治愈情感", "古风奇幻", "都市反转", "搞笑脑洞"];
const styles = ["电影写实", "日系动漫", "3D 动画", "赛博朋克", "水墨国风", "复古胶片"];
const platforms = ["抖音 / TikTok", "小红书", "B站", "YouTube Shorts", "横屏短片"];
const models = ["通用视频模型", "Seedance 2.0", "Sora 2", "Veo 3.1", "Kling 3.0", "Runway Gen-4.5"];
const imageModels = ["ChatGPT Image", "Midjourney", "Seedream", "Flux", "Runway Gen-4 Image"];
const imagePurposes = ["电影关键帧", "角色设定图", "场景概念图", "封面海报", "产品视觉"];
const imageAspects = ["16:9 横屏", "9:16 竖屏", "1:1 方形", "4:3 经典", "21:9 超宽"];
const imageStyles = [...styles, "商业摄影", "概念艺术", "极简海报"];
const imageWorkflows:ImageWorkflow[]=["text-to-image","image-to-image","multi-reference"];
const referenceRoles=["subject","character","scene","style","composition","prop","color"];
const ideas = [
  "每天午夜，城市里会有一个人的影子突然消失，而只有一名失眠的摄影师能看见。",
  "一台废弃的自动售货机可以出售人生中被遗忘的五分钟，但每人只能购买一次。",
  "古代画师发现自己画下的山河会在第二天真实消失，于是决定画出一条不存在的归途。",
  "一只流浪猫每天把不同世界的钥匙放在女孩门口，直到最后一把刻着她的名字。",
  "未来世界禁止做梦，一名梦境修复师却在客户记忆里发现了童年时的自己。",
];
const sampleIdeas:Record<Locale,string>={"zh-CN":"一个女孩捡到能让时间倒流三分钟的怀表，却发现每使用一次，就会失去一段关于家人的记忆。","zh-TW":"一個女孩撿到能讓時間倒流三分鐘的懷錶，卻發現每使用一次，就會失去一段關於家人的記憶。",ja:"少女は時間を3分巻き戻せる懐中時計を拾う。しかし使うたびに、家族との記憶を一つ失っていく。",en:"A girl finds a pocket watch that rewinds time by three minutes, but each use erases one memory of her family."};
const sampleImageConcepts:Record<Locale,string>={"zh-CN":"一名女孩站在雨夜便利店门口，掌心的古董怀表正在倒转，玻璃倒影中出现失踪多年的亲人。","zh-TW":"一名女孩站在雨夜便利商店門口，掌心的古董懷錶正在倒轉，玻璃倒影中出現失蹤多年的親人。",ja:"雨の夜、コンビニの入口に立つ少女。手のひらのアンティーク懐中時計が逆回転し、ガラスの反射には長年行方不明の家族が現れる。",en:"A girl stands outside a convenience store on a rainy night. An antique pocket watch reverses in her palm, while the glass reflection reveals a relative missing for years."};
const sampleIdea = sampleIdeas["zh-CN"];

function inspectImageFile(file:File){return new Promise<ImageInfo>((resolve,reject)=>{if(!file.type.startsWith("image/")){reject(new Error("IMAGE_TYPE"));return}if(file.size>10*1024*1024){reject(new Error("IMAGE_SIZE"));return}const reader=new FileReader();reader.onerror=()=>reject(new Error("IMAGE_READ"));reader.onload=()=>{const originalSrc=String(reader.result);const img=new Image();img.onerror=()=>reject(new Error("IMAGE_READ"));img.onload=()=>{const sample=document.createElement("canvas");sample.width=40;sample.height=40;const sampleContext=sample.getContext("2d");if(!sampleContext){reject(new Error("IMAGE_READ"));return}sampleContext.drawImage(img,0,0,40,40);const px=sampleContext.getImageData(0,0,40,40).data;let red=0,green=0,blue=0,count=0;for(let i=0;i<px.length;i+=16){red+=px[i];green+=px[i+1];blue+=px[i+2];count++}red=Math.round(red/count);green=Math.round(green/count);blue=Math.round(blue/count);const brightness=Math.round(.299*red+.587*green+.114*blue);const orientation=img.width>img.height*1.15?"landscape":img.height>img.width*1.15?"portrait":"square";const scale=Math.min(1,1600/Math.max(img.width,img.height));const optimized=document.createElement("canvas");optimized.width=Math.max(1,Math.round(img.width*scale));optimized.height=Math.max(1,Math.round(img.height*scale));const outputContext=optimized.getContext("2d");if(!outputContext){reject(new Error("IMAGE_READ"));return}outputContext.drawImage(img,0,0,optimized.width,optimized.height);const src=optimized.toDataURL("image/jpeg",.84)||originalSrc;resolve({src,name:file.name,width:img.width,height:img.height,orientation,color:`RGB(${red}, ${green}, ${blue})`,tone:brightness>175?"high-key":brightness<80?"low-key":"balanced",size:`${(file.size/1024/1024).toFixed(1)}MB`})};img.src=originalSrc};reader.readAsDataURL(file)})}

const genreProfiles:Record<string,{promise:string;pacing:string;logline:(s:string)=>string;hook:(s:string)=>string;structure:(s:string,a:string)=>[string,string][];beats:(s:string,a:string)=>string[];sound:string[]}> = {
  "悬疑惊悚":{promise:"不可靠信息、逐步逼近与最后一秒真相翻转",pacing:"克制铺垫 → 线索加速 → 骤停反转",logline:s=>`${s}，却发现每一次确认真相都会抹去另一条证据；当所有线索都指向自己，主人公必须在被发现之前完成最后一次验证。`,hook:s=>`镜头里出现了“${s.slice(0,16)}”不该存在的第二个版本——究竟哪一个才是真的？`,structure:(s,a)=>[["异常证据",`以${a}作为第一条不可能存在的证据；${s}被迫开始调查。`],["封闭追索","线索互相矛盾，熟悉的人开始说出完全不同的记忆，安全空间逐步缩小。"],["身份反转","主人公发现追踪自己的并非外部敌人，而是另一个正在阻止真相被揭开的自己。"],["未完余悸",`表面危机解除，但${a}在最后一帧再次发生变化，证明真相仍未结束。`]],beats:(s,a)=>[`黑暗中只显露${a}，其状态与现实规则明显冲突。`,`主人公围绕“${s}”检查现场，镜面或阴影里掠过无法确认的第二道人影。`,`一条证据突然消失，主人公回头时空间布局已悄然改变。`,`最可信的人否认刚才发生的一切，却无意说出只有目击者才知道的细节。`,`灯光与声音逐级收紧，${a}开始重复发出倒计时般的异常信号。`,`主人公逼近真相，发现所有监控画面中的嫌疑人都拥有自己的轮廓。`,`真相被揭开的一刻，追逐关系反转：主人公才是一直被保护起来的危险源。`,`危机似乎结束；最后极近景中，${a}再次自行变化。`],sound:["单一细节声被异常放大","低频持续音与远处刮擦声","脚步回声多出半拍","对话尾音突然被切断","耳鸣与倒计时叠加","完全静音后突发近距离声响","主题动机倒放","一个不应出现的呼吸声"]},
  "科幻未来":{promise:"明确科技规则、系统失控与关于人性的概念反转",pacing:"快速建立规则 → 规则出现漏洞 → 规模扩张",logline:s=>`${s}成为一项未来技术的唯一异常样本；当系统决定修正这个错误，主人公必须证明不完美才是人类最后的自由。`,hook:s=>`系统预测“${s.slice(0,17)}”将在三分钟后从现实中被自动删除。`,structure:(s,a)=>[["规则展示",`通过${a}展示未来系统的核心规则，并立刻出现一个不可能的错误值。`],["系统围堵","主人公利用漏洞逃离自动修正，城市基础设施与个人设备同时转为敌对。"],["尺度反转","所谓系统故障其实是人类意识觉醒的信号，主人公并非异常者而是第一个清醒者。"],["新规则诞生",`主人公拒绝恢复旧秩序，${a}从警告信号转变为面向全城的自由坐标。`]],beats:(s,a)=>[`未来界面围绕${a}完成身份扫描，结果跳出从未见过的错误代码。`,`主人公测试“${s}”的边界，周围智能设备同时暂停响应。`,`自动修正程序启动，城市路径、门禁与交通开始主动封锁主人公。`,`一段被删除的数据恢复，显示这场异常在多年以前就被系统预演。`,`环境规模突然扩大，${a}与城市核心网络产生同步脉冲。`,`主人公进入系统边界，在现实与数据空间的接缝处作出选择。`,`系统倒计时归零，但被删除的不是主人公，而是控制人类选择的规则。`,`新的晨光中，${a}向远处复制出无数自由坐标。`],sound:["洁净电子提示音与低频脉冲","系统女声播报异常值","机械锁闭声连续扩散","数据噪声中出现人类耳语","城市电网轰鸣逐层点亮","心跳与系统节拍同步","所有机器同时静音","新系统启动音变为温暖和弦"]},
  "治愈情感":{promise:"日常细节、关系误解与不煽情的温柔回收",pacing:"安静观察 → 情绪累积 → 轻柔释放",logline:s=>`${s}让两个早已疏远的人重新共享一段日常；他们没有改变过去，却终于学会用一个微小行动接住彼此。`,hook:s=>`主人公每天都会收到一份关于“${s.slice(0,16)}”的无名提醒，字迹却来自已经失去联系的人。`,structure:(s,a)=>[["日常缺口",`用${a}呈现主人公生活中缺失的那个人，不解释，只让细节留下空位。`],["笨拙靠近","两个人通过不直接说出口的行动重新建立联系，误解在生活琐事中缓慢松动。"],["善意回收","主人公发现对方一直在用自己的方式守护这段关系，过去的沉默并非遗忘。"],["温柔延续",`没有宏大告白；一个与${a}有关的小动作完成和解，生活继续向前。`]],beats:(s,a)=>[`清晨的普通空间里，${a}被放在一个长期空着的位置。`,`主人公因“${s}”收到一条笨拙却熟悉的提醒。`,`两人在同一空间错开行动，只通过物件位置变化感知彼此。`,`一个旧习惯被重新看见，主人公第一次意识到对方从未真正离开。`,`天气或光线慢慢转暖，${a}成为他们共享记忆的安静载体。`,`主人公不再追问原因，只完成对方曾经没有做到的小事。`,`两人短暂同框，没有拥抱，只交换一个终于放松的眼神。`,`日常重新开始，${a}仍在原位，却不再意味着失去。`],sound:["清晨环境声与轻微器物声","克制的钢琴单音","衣料与脚步的生活细响","旧录音或熟悉旋律短暂出现","窗外风声逐渐变暖","音乐停下，保留真实呼吸","主题旋律第一次完整出现","环境声平静延续"]},
  "古风奇幻":{promise:"东方禁忌、因果誓约与带诗意的宿命选择",pacing:"异象降临 → 禁忌开启 → 因果兑现",logline:s=>`${s}触犯了一条被遗忘的古老禁忌；为偿还跨越百年的因果，主人公必须在天命落下之前改写一段不该被记住的誓约。`,hook:s=>`古籍记载：“${s.slice(0,16)}”出现之日，画中人将向画外之人索回姓名。`,structure:(s,a)=>[["异象启卷",`以${a}引出违反自然规律的东方异象，古老禁忌被重新唤醒。`],["入局寻因","主人公循符印、旧梦与残缺传说追索前缘，每解开一层就更接近命定代价。"],["因果倒置","所谓诅咒其实是主人公前世亲手订下的保护誓约，敌人与守护者身份互换。"],["留白成诗",`主人公以失去一部分自我换回自由；${a}化作新的自然意象，留下未尽余韵。`]],beats:(s,a)=>[`风停云止，${a}以墨迹、符光或水纹形式显现，天地出现异象。`,`主人公触碰与“${s}”有关的旧物，短暂看见百年前的残影。`,`禁忌被触发，庭院、山门或长街沿不可能的方向延展。`,`守门人说出半段誓约，揭示主人公与异象早有因果。`,`月色或天光转冷，${a}化成引路符号通向被封存的境界。`,`主人公在阵法或天象中心重读完整誓约，决定承担代价。`,`因果反转：被视为妖异的存在一直在替主人公承受天命。`,`尘埃落定，${a}融入山水，只留一笔未干的墨痕。`],sound:["风铃、远钟与骤停的虫鸣","古琴泛音和纸页摩擦","木结构低鸣与符火爆裂","空旷人声带长混响","鼓点与呼吸逐渐同步","所有乐器停下只剩誓词","弦乐与钟声展开","风声携一声遥远铃响"]},
  "都市反转":{promise:"真实社会身份、利益错位与可回看的信息型反转",pacing:"现实切入 → 信息叠加 → 快速翻盘",logline:s=>`${s}意外撬开一场精心包装的都市骗局；主人公以为自己在揭穿别人，最后才发现自己正是整个计划最关键的伪装。`,hook:s=>`同一条关于“${s.slice(0,17)}”的消息，在每个人手机上显示的主角都不一样。`,structure:(s,a)=>[["现实错位",`从写实都市日常切入，${a}暴露身份或信息上的微小矛盾。`],["利益加压","工作、关系与公共舆论同时施压，主人公只能在碎片化信息中判断谁在说谎。"],["叙事翻盘","观众以为的受害者其实在控制信息，而看似被利用的主人公才是主动设局的人。"],["现实回刺",`结局落回普通生活；${a}出现在下一位陌生人身上，暗示这套机制仍在运转。`]],beats:(s,a)=>[`通勤、办公或商业空间中，${a}显示一条只对主人公可见的矛盾信息。`,`主人公围绕“${s}”向不同人物求证，得到三个互不相容的版本。`,`社交消息快速扩散，主人公身份在公共叙事中被悄然改写。`,`关键证人看似提供帮助，却用一个称呼暴露自己参与了布局。`,`主人公被逼入没有退路的公开场合，${a}成为唯一可翻盘的证据。`,`所有人等待主人公失控时，主人公主动公开一段早已准备好的信息。`,`反转揭晓：此前的慌乱与被动都是为了让幕后者自行暴露。`,`人群散去，${a}在另一部手机或另一名陌生人手中再次出现。`],sound:["城市环境声与消息提示音","多段语音消息交叠","节拍随信息刷新加速","环境声骤降突出一句口误","人群噪声与低频鼓点叠加","发送键声后完全静音","提示音组成反转节奏","远处再次响起同一提示音"]},
  "搞笑脑洞":{promise:"一本正经的荒诞规则、连续升级与最后一个反逻辑笑点",pacing:"快速设梗 → 三次升级 → 意外包袱",logline:s=>`${s}把一件小事升级成全城危机；主人公试图用正常逻辑解决问题，却发现唯一有效的方法是比这个世界更不讲道理。`,hook:s=>`官方紧急通知：从今天起，“${s.slice(0,16)}”属于违法行为——但执法人员自己也不知道为什么。`,structure:(s,a)=>[["荒诞规则",`用严肃口吻宣布与${a}有关的离谱规则，所有人只有主人公觉得不对劲。`],["三次升级","每次正常解决都会制造更大的问题，从个人尴尬升级到城市级混乱。"],["反逻辑破局","主人公放弃讲道理，用比规则更荒诞的行动让系统陷入自我矛盾。"],["回马包袱",`危机解除后，${a}给出一个更小、更生活化却更好笑的最后代价。`]],beats:(s,a)=>[`以新闻播报般严肃的画面宣布${a}触发了一条极其离谱的新规定。`,`主人公尝试正常处理“${s}”，结果第一个解决办法立即制造双倍麻烦。`,`路人一本正经加入错误行动，混乱以可视化方式迅速扩散。`,`权威人物登场解释规则，却发现自己正好违反了规则的每一条。`,`${a}变成所有人争抢或躲避的核心，场面升级到荒诞的大规模行动。`,`主人公突然停止解决问题，反而把规则执行到极致。`,`系统因无法处理自我矛盾而崩溃，所有人若无其事恢复正常。`,`主人公准备离开时，${a}弹出一条更小气的新收费通知。`],sound:["庄严新闻配乐搭配荒诞小声响","快速木琴节奏","错误提示音连续升级","全场静默突出尴尬咳嗽","史诗音乐配合小题大做","音乐突然变得极度认真","系统崩溃声后接轻松口哨","收款提示音作为最后包袱"]},
};

const styleProfiles:Record<string,{direction:string;look:string;palette:string;lighting:string;material:string;cameraZh:string[];cameraEn:string[];composition:string;cadence:string}> = {
  "电影写实":{direction:"自然主义表演与真实空间调度，用克制镜头让异常发生在可信世界里",look:"cinematic photorealism, 35mm film texture, natural skin and fabric detail",palette:"restrained teal-amber neutrals with realistic production design",lighting:"motivated practical lighting, soft falloff, controlled highlight roll-off",material:"tactile real-world surfaces, atmospheric depth, subtle film grain",cameraZh:["35mm 手持轻推，利用真实遮挡寻找细节","50mm 稳定横移，焦点随人物视线转移","24mm 跟拍进入空间，保持真实步态晃动","85mm 克制特写，停留在微表情上"],cameraEn:["35mm subtle handheld push-in with natural occlusion","50mm lateral dolly with motivated rack focus","24mm grounded follow shot with restrained body movement","85mm locked close-up held on micro-expression"],composition:"naturalistic blocking, layered foreground, believable eyelines",cadence:"动作连贯、停顿真实，每镜只完成一个清晰行为"},
  "日系动漫":{direction:"用明确剪影、夸张情绪关键帧与富有空气感的绘景传达情绪",look:"premium Japanese animated feature, clean expressive linework, detailed painted background",palette:"emotion-led color scripting, luminous sky tones and controlled accent colors",lighting:"soft bloom, animated rim light, painterly shadow shapes",material:"hand-painted background texture, crisp cel shading, subtle atmospheric particles",cameraZh:["广角绘景建立空间，人物以清晰剪影进入","快速推近后定格情绪关键帧","低机位跟随配合前景速度层","侧脸特写，以发丝和光斑表现情绪"],cameraEn:["wide establishing anime layout with a readable character silhouette","fast animated push-in resolving into a strong emotion keyframe","low-angle tracking with layered parallax and restrained speed accents","profile close-up with hair motion and luminous bokeh"],composition:"graphic silhouette, strong foreground-midground-background separation, readable key poses",cadence:"静止构图与短促爆发交替，动作落在清晰关键帧"},
  "3D 动画":{direction:"强调体积、材质与富有弹性的角色动作，让世界精致但保持可亲近感",look:"high-end stylized 3D animation, expressive character design, physically coherent render",palette:"harmonious production-design palette with clear warm-cool separation",lighting:"global illumination, soft volumetric key light, polished rim highlights",material:"rich stylized materials, controlled subsurface skin, clean geometric detail",cameraZh:["广角弧形环绕，展示三维空间层次","中景缓慢推近，角色动作带清晰预备与缓冲","低位跟随，利用物件制造视差","近景环绕半圈，捕捉表情与材质光泽"],cameraEn:["wide curved orbit revealing dimensional environment layers","medium dolly-in with readable anticipation and follow-through","low tracking shot with strong object parallax","half-orbit close-up capturing expression and material response"],composition:"dimensional staging, clear silhouettes, strong depth cues and parallax",cadence:"动作具备预备、主动作与缓冲，重量和惯性清晰"},
  "赛博朋克":{direction:"用霓虹信息层、城市压迫感与高反差暗部制造技术异化",look:"restrained cyberpunk cinema, dense neon information layers, wet reflective city surfaces",palette:"electric cyan and warning orange against deep near-black shadows",lighting:"hard neon edge light, volumetric haze, animated screen spill and deep contrast",material:"wet asphalt, smoked glass, brushed metal, holographic interference",cameraZh:["超广角贴地滑行，霓虹反射划过镜头","长焦隔着玻璃窥视，信息层遮挡人物","手持穿越拥挤前景，故意保留压迫式遮挡","高位俯冲到面部特写，屏幕光快速变化"],cameraEn:["ultra-wide ground-level glide through neon reflections","telephoto surveillance view through layered glass and interface obstruction","urgent handheld passage through dense foreground traffic","high-angle dive resolving into a screen-lit facial close-up"],composition:"compressed urban layers, asymmetric negative space, information-dense foreground",cadence:"短促移动、电子停顿与突然加速，保持压迫节奏"},
  "水墨国风":{direction:"以留白、气韵与墨色浓淡组织空间，让动作像笔触一样发生",look:"Chinese ink-wash moving painting, poetic negative space, expressive brush energy",palette:"paper white, layered ink blacks and one restrained mineral-color accent",lighting:"diffuse poetic light, mist gradients, luminous negative space",material:"rice-paper fiber, bleeding ink edges, dry-brush texture, drifting wash",cameraZh:["远景留白中缓慢横移，人物如一笔入画","画面由淡墨向浓墨推近，焦点随墨迹显现","俯视构图旋转极慢，以水纹完成转场","静止特写，风与衣袖成为唯一运动"],cameraEn:["slow lateral move across vast ink-wash negative space","push from pale wash into dense ink as the subject resolves","near-static overhead rotation transitioning through expanding ink ripples","locked poetic close-up with only wind and fabric movement"],composition:"asymmetric poetic balance, expansive negative space, depth built with ink density",cadence:"慢、空、停顿充足，关键动作像落笔一样短而明确"},
  "复古胶片":{direction:"用年代感构图、柔和晕光与不完美的胶片质感制造记忆感",look:"vintage analog cinema, authentic period lens behavior, tactile film grain and halation",palette:"faded warm earth tones, muted greens, dusty reds and creamy highlights",lighting:"soft tungsten practicals, window light, gentle underexposure and highlight bloom",material:"aged paper, worn fabric, patinated metal, organic 16mm grain",cameraZh:["4:3 画幅固定机位，让人物自然走入构图","老式变焦缓慢推进，边缘轻微呼吸","肩扛跟拍带细小抖动与偶发漏光","柔焦特写，逆光晕开人物轮廓"],cameraEn:["locked 4:3 period composition with the subject entering naturally","slow vintage zoom with subtle lens breathing and edge softness","shoulder-mounted follow shot with organic micro-jitter and rare light leak","soft-focus backlit close-up with authentic halation"],composition:"period framing, slightly imperfect headroom, documentary-like blocking",cadence:"镜头停留更久，允许偶发抖动与胶片式不完美"},
};

type VideoPromptContext={shotNo:number;seconds:number;genre:string;style:string;subject:string;action:string;reference:string;camera:string;composition:string;look:string;color:string;lighting:string;material:string;cadence:string;audio:string;continuity:string;output:string;avoid:string};
function formatVideoPrompt(model:string,c:VideoPromptContext){
  if(model==="Seedance 2.0") return `【创作目标】生成一段 ${c.seconds} 秒的${c.genre}叙事镜头，视觉风格为${c.style}。\n【核心表演】${c.action}\n【故事语境】${c.subject}\n【多模态参考】${c.reference}\n【镜头设计】${c.camera}；${c.composition}。\n【视觉与材质】${c.look}；${c.color}；${c.lighting}；${c.material}。\n【叙事节奏】${c.cadence}，本镜只完成一个清晰动作。\n【声音设计】${c.audio}。\n【连续性】${c.continuity}\n【输出参数】${c.output}，24fps，动作和物理反馈自然。\n【限制】${c.avoid}`;
  if(model==="Sora 2") return `A ${c.seconds}-second continuous ${c.genre} scene in ${c.style} style. ${c.action} The world remains spatially coherent and the central subject—${c.subject}—keeps a persistent identity and physical presence. ${c.reference} The camera performs ${c.camera}, composed with ${c.composition}. The image has ${c.look}, ${c.color}, ${c.lighting}, and ${c.material}. Performance rhythm: ${c.cadence}. Objects obey believable weight, inertia, contact and environmental response. Synchronized sound: ${c.audio}. ${c.continuity} Output: ${c.output}.`;
  if(model==="Veo 3.1") return `CINEMATOGRAPHY: ${c.camera}; ${c.composition}.\nSUBJECT: ${c.subject}.\nACTION: ${c.action}\nCONTEXT: ${c.reference}\nSTYLE & AMBIANCE: ${c.look}; ${c.color}; ${c.lighting}; ${c.material}.\nTEMPORAL DIRECTION: ${c.seconds} seconds; ${c.cadence}.\nAMBIENT SOUND: ${c.audio}.\nSFX: physically synchronized with the visible action.\nCONTINUITY: ${c.continuity}\nOUTPUT: ${c.output}.`;
  if(model==="Kling 3.0") return `【自定义分镜 ${String(c.shotNo).padStart(2,"0")}｜${c.seconds}s】\n场景：${c.subject}，${c.genre}，${c.style}。\n角色动作轨迹：${c.action} 动作从明确起始姿态发展至稳定结束姿态，表情与身体重心连续。\n镜头轨迹：${c.camera}；${c.composition}。\n元素参考：${c.reference}\n画面控制：${c.look}；${c.color}；${c.lighting}；${c.material}。\n节奏：${c.cadence}。\n原生音频：${c.audio}，动作音效与画面逐帧同步。\n一致性：${c.continuity}\n输出：${c.output}。`;
  if(model==="Runway Gen-4.5") return `${c.action} ${c.camera}. The environment responds naturally to the subject's movement. ${c.look}. ${c.lighting}. ${c.color}. ${c.cadence}. ${c.output}.`;
  return `[UNIVERSAL VIDEO PROMPT · SHOT ${String(c.shotNo).padStart(2,"0")} · ${c.seconds} SECONDS]\nSUBJECT & ACTION: ${c.action}\nSTORY CONTEXT: ${c.subject}\nREFERENCE: ${c.reference}\nCAMERA: ${c.camera}; ${c.composition}.\nLOOK: ${c.look}; ${c.color}; ${c.lighting}; ${c.material}.\nPERFORMANCE: ${c.cadence}.\nAUDIO: ${c.audio}.\nCONTINUITY: ${c.continuity}\nOUTPUT: ${c.output}.\nAVOID: ${c.avoid}`;
}

function subjectOf(text:string){ return text.trim().replace(/[。！？!?]/g,"").slice(0,30)||"一个意外改变命运的人"; }
function titleOf(text:string,genre:string){ const clean=text.replace(/[，。！？、,.!?\s]/g,""); const clues=["时间","记忆","秘密","消失","重逢","梦","门","信","光","影子"]; const clue=clues.find(x=>clean.includes(x))||clean.slice(0,5)||"未命名"; const pattern:Record<string,(x:string)=>string>={"悬疑惊悚":x=>`消失的${x}`,"科幻未来":x=>`${x}协议`,"治愈情感":x=>`留给${x}的灯`,"古风奇幻":x=>`${x}引`,"都市反转":x=>`${x}背面`,"搞笑脑洞":x=>`今天禁止${x}`}; return `《${pattern[genre](clue)}》`; }
function referenceAnchor(idea:string,image:ImageInfo|null,imageNotes:string){return image?(imageNotes.trim()?`参考图中的“${imageNotes.trim()}”`:`参考图的${image.orientation}构图、${image.tone}明暗和${image.color}主色`):`“${subjectOf(idea).slice(0,14)}”的核心视觉物件`;}
function buildStory(idea:string,genre:string,style:string,image:ImageInfo|null,imageNotes:string):Story{const subject=subjectOf(idea),g=genreProfiles[genre],v=styleProfiles[style],anchor=referenceAnchor(idea,image,imageNotes);const base=g.structure(subject,anchor);return{title:titleOf(idea,genre),logline:g.logline(subject),hook:g.hook(subject),direction:`题材采用「${g.promise}」的叙事机制，节奏为「${g.pacing}」；视觉采用${style}，${v.direction}。${anchor}将作为贯穿全片的视觉母题。`,structure:base.map((x,i)=>[x[0],`${x[1]} ${i===0?`开场按${v.composition}构图。`:i===2?`高潮以${v.cadence}控制动作。`:""}`])};}

function buildShots(idea:string,genre:string,style:string,duration:number,model:string,image:ImageInfo|null,imageNotes:string,lock:boolean):Shot[]{
  const count=Math.max(4,Math.min(8,Math.round(duration/7))); const subject=subjectOf(idea); const each=duration/count; const g=genreProfiles[genre]; const v=styleProfiles[style]; const anchor=referenceAnchor(idea,image,imageNotes); const beats=g.beats(subject,anchor);
  const shotNames:Record<string,string[]>={"电影写实":["细节特写","人物中景","手持跟拍","对话双人景","空间大全景","情绪特写","环境远景","结尾极特写"],"日系动漫":["绘景特写","情绪中景","动态跟拍","关键帧双人景","绘景大全景","侧脸特写","天空远景","定格极特写"],"3D 动画":["材质特写","角色中景","视差跟拍","角色双人景","环境全景","表情特写","空间远景","物件微距"],"赛博朋克":["数据特写","窥视中景","街区跟拍","隔窗双人景","城市大全景","屏幕光特写","天际远景","信号微距"],"水墨国风":["墨迹特写","留白中景","游动画卷","对景双人景","山水远景","静观特写","天地大全景","落墨极近景"],"复古胶片":["胶片细节","4:3 中景","肩扛跟拍","年代双人景","街景全景","柔焦特写","定机远景","胶片定格"]};
  return Array.from({length:count},(_,i)=>{
    const start=Math.round(i*each),end=Math.round((i+1)*each),seconds=Math.max(2,end-start);
    const genreBeat=beats[i];
    const visual=`${genreBeat} ${i%2===0?`画面强调${v.material}。`:`色彩采用${v.palette}，光线采用${v.lighting}。`}`;
    const cameraZh=v.cameraZh[i%v.cameraZh.length],cameraEn=v.cameraEn[i%v.cameraEn.length];
    const reference=image?`Use the attached image as the primary visual source. Preserve ${anchor}, its ${image.orientation} framing, ${image.tone} exposure and ${image.color} dominant palette. Translate it through ${style} without replacing key subjects or spatial relationships.`:`Recur ${anchor} across shots with evolving narrative meaning.`;
    const continuity=lock?"Lock protagonist identity, face, hairstyle, wardrobe, hero props, body scale and palette across every shot.":"Preserve geography, screen direction and lighting progression across adjacent shots.";
    const output=duration<=60?"vertical 9:16, mobile-first focal placement, safe center framing":"cinematic 16:9, layered depth, deliberate negative space";
    const avoid="subtitles, captions, logos, watermarks, flicker, frame warping, duplicate limbs, face drift, random objects, abrupt exposure shifts, style drift, unmotivated camera movement";
    const prompt=formatVideoPrompt(model,{shotNo:i+1,seconds,genre,style,subject,action:genreBeat,reference,camera:cameraEn,composition:v.composition,look:v.look,color:v.palette,lighting:v.lighting,material:v.material,cadence:v.cadence,audio:g.sound[i],continuity,output,avoid});
    return{id:i+1,time:`00:${String(start).padStart(2,"0")}–00:${String(end).padStart(2,"0")}`,shot:shotNames[style][i],visual,camera:cameraZh,audio:g.sound[i],prompt};
  });
}

function BackdropVisual({mode}:{mode:Backdrop}){
  if(mode==="globe") return <div className="scene globe-scene" aria-hidden="true"><div className="globe"><i className="orbit o1"/><i className="orbit o2"/><i className="orbit o3"/><i className="axis"/><span className="gdot d1"/><span className="gdot d2"/><span className="gdot d3"/></div><div className="scene-label">ORBITAL STORY MAP · LIVE</div></div>;
  if(mode==="mind") return <div className="scene mind-scene" aria-hidden="true"><div className="mind-shell"><div className="hemi left"/><div className="hemi right"/>{Array.from({length:14},(_,i)=><i className={`node n${i+1}`} key={i}/>)}{Array.from({length:10},(_,i)=><span className={`synapse s${i+1}`} key={i}/>)}</div><div className="scene-label">NARRATIVE NEURAL FIELD · THINKING</div></div>;
  return null;
}

function IdeaField({locale}:{locale:Locale}){
  const branches=[
    {w:"24vw",r:"-52deg",d:"-.4s"},{w:"27vw",r:"-12deg",d:"-2.1s"},{w:"25vw",r:"27deg",d:"-3.8s"},
    {w:"23vw",r:"83deg",d:"-1.2s"},{w:"24vw",r:"137deg",d:"-4.5s"},{w:"31vw",r:"178deg",d:"-2.9s"},
    {w:"27vw",r:"-145deg",d:"-5.2s"},{w:"25vw",r:"-83deg",d:"-1.8s"},{w:"36vw",r:"39deg",d:"-4.1s"},
  ];
  const labels:Record<Locale,string[]>={"zh-CN":["角色","冲突","镜头","节奏","情绪","世界","意象","声音","转折"],"zh-TW":["角色","衝突","鏡頭","節奏","情緒","世界","意象","聲音","轉折"],ja:["人物","葛藤","ショット","リズム","感情","世界","イメージ","音","転換"],en:["CHARACTER","CONFLICT","SHOT","RHYTHM","EMOTION","WORLD","MOTIF","SOUND","TURN"]};
  const thoughts=[
    {x:"69%",y:"23%",d:"-.7s"},{x:"82%",y:"37%",d:"-2.8s"},{x:"78%",y:"62%",d:"-4.2s"},
    {x:"58%",y:"78%",d:"-1.5s"},{x:"37%",y:"70%",d:"-3.4s"},{x:"25%",y:"48%",d:"-5s"},
    {x:"33%",y:"25%",d:"-2.2s"},{x:"60%",y:"13%",d:"-4.7s"},{x:"88%",y:"77%",d:"-3.1s"},
  ];
  return <div className="idea-field" aria-hidden="true">
    <div className="idea-radar ring-one"/><div className="idea-radar ring-two"/><div className="idea-radar ring-three"/>
    <div className="idea-origin"><i/><span>IDEA</span></div>
    {branches.map((item,index)=><span className={`idea-branch branch-${index+1}`} key={`branch-${index}`} style={{"--branch-width":item.w,"--branch-angle":item.r,"--branch-delay":item.d} as CSSProperties}><i/><b/></span>)}
    {thoughts.map((item,index)=><span className="thought-node" key={labels[locale][index]} style={{"--node-x":item.x,"--node-y":item.y,"--node-delay":item.d} as CSSProperties}><i/><b>{labels[locale][index]}</b><em>{String(index+1).padStart(2,"0")}</em></span>)}
    {Array.from({length:18},(_,index)=><i className="idea-particle" key={`particle-${index}`} style={{"--particle-index":String(index),"--particle-delay":`${-index*.73}s`} as CSSProperties}/>) }
  </div>;
}

export default function Studio({user}:{user:User}){
  const [workspaceMode,setWorkspaceMode]=useState<WorkspaceMode>("home");
  const [locale,setLocaleState]=useState<Locale>("zh-CN"); const [languageOpen,setLanguageOpen]=useState(false); const [localeChanging,setLocaleChanging]=useState(false);
  const [activeTab,setActiveTab]=useState<"story"|"shots">("story"); const [idea,setIdea]=useState(sampleIdea); const [genre,setGenre]=useState(genres[0]); const [style,setStyle]=useState(styles[0]); const [platform,setPlatform]=useState(platforms[0]); const [duration,setDuration]=useState(30); const [model,setModel]=useState(models[0]); const [lock,setLock]=useState(true);
  const [story,setStory]=useState(()=>buildStory(sampleIdea,genres[0],styles[0],null,"")); const [shots,setShots]=useState(()=>buildShots(sampleIdea,genres[0],styles[0],30,models[0],null,"",true)); const [generating,setGenerating]=useState(false); const [copied,setCopied]=useState(""); const [notice,setNotice]=useState("示例内容"); const [version,setVersion]=useState(0);
  const [theme,setThemeState]=useState<Theme>("system"); const [themeOpen,setThemeOpen]=useState(false); const [backdrop,setBackdropState]=useState<Backdrop>("none"); const [brandOpen,setBrandOpen]=useState(false); const [profileOpen,setProfileOpen]=useState(false); const [settingsOpen,setSettingsOpen]=useState(false);
  const [image,setImage]=useState<ImageInfo|null>(null); const [imageNotes,setImageNotes]=useState(""); const [uploadError,setUploadError]=useState(""); const fileRef=useRef<HTMLInputElement>(null); const imageFileRef=useRef<HTMLInputElement>(null);
  const [imageConcept,setImageConcept]=useState(sampleImageConcepts["zh-CN"]); const [imagePurpose,setImagePurpose]=useState(imagePurposes[0]); const [imageStyle,setImageStyle]=useState(imageStyles[0]); const [imageModel,setImageModel]=useState(imageModels[0]); const [imageAspect,setImageAspect]=useState(imageAspects[0]); const [imagePrompt,setImagePrompt]=useState(""); const [imagePromptCore,setImagePromptCore]=useState(""); const [imageGenerating,setImageGenerating]=useState(false); const [imageRendering,setImageRendering]=useState(false); const [imageRenderStatus,setImageRenderStatus]=useState(""); const [generatedImage,setGeneratedImage]=useState<GeneratedImage|null>(null); const [imageWorkflow,setImageWorkflow]=useState<ImageWorkflow>("text-to-image"); const [promptReferences,setPromptReferences]=useState<PromptReference[]>([]); const [imageBriefNotes,setImageBriefNotes]=useState(""); const [referenceError,setReferenceError]=useState("");
  const [poseConcept,setPoseConcept]=useState("一名敏捷的未来城市信使，全身角色设计，服装结构清晰，严格匹配骨骼姿态。" ); const [poseStyle,setPoseStyle]=useState(imageStyles[0]); const [poseAspect,setPoseAspect]=useState(imageAspects[1]); const [poseReference,setPoseReference]=useState<PromptReference|null>(null); const [poseResult,setPoseResult]=useState<GeneratedImage|null>(null); const [posePrompt,setPosePrompt]=useState(""); const [poseGenerating,setPoseGenerating]=useState(false); const [poseStatus,setPoseStatus]=useState(""); const poseRigRef=useRef<PoseRigHandle>(null); const poseFileRef=useRef<HTMLInputElement>(null);
  const [providerId,setProviderId]=useState("openrouter"); const [apiBaseUrl,setApiBaseUrl]=useState(providerById("openrouter").baseUrl); const [apiKey,setApiKey]=useState(""); const [generationModel,setGenerationModel]=useState(""); const [availableModels,setAvailableModels]=useState<ModelOption[]>([]); const [modelSearch,setModelSearch]=useState(""); const [detectingModels,setDetectingModels]=useState(false); const [configStatus,setConfigStatus]=useState("正在读取账户配置…"); const [showApiKey,setShowApiKey]=useState(false); const [accountConfig,setAccountConfig]=useState<AccountModelConfig|null>(null);
  const [imageProviderId,setImageProviderId]=useState("runway"); const [imageApiBaseUrl,setImageApiBaseUrl]=useState(imageGenerationProviderById("runway").baseUrl); const [imageApiKey,setImageApiKey]=useState(""); const [imageGenerationModel,setImageGenerationModel]=useState(imageGenerationProviderById("runway").models[0].id); const [showImageApiKey,setShowImageApiKey]=useState(false); const [imageConfigStatus,setImageConfigStatus]=useState("正在读取图片引擎…"); const [accountImageConfig,setAccountImageConfig]=useState<AccountImageConfig|null>(null);
  const savedKeyMatches=Boolean(accountConfig?.hasApiKey&&accountConfig.providerId===providerId&&sameApiEndpoint(accountConfig.apiBaseUrl,apiBaseUrl));
  const savedImageKeyMatches=Boolean(accountImageConfig?.hasApiKey&&accountImageConfig.providerId===imageProviderId&&sameApiEndpoint(accountImageConfig.apiBaseUrl,imageApiBaseUrl));
  const t=(key:string,values:Record<string,string|number>={})=>translate(locale,key,values);

  useEffect(()=>{ const saved=(localStorage.getItem("frame-theme") as Theme|null)||"system"; setThemeState(saved); const media=window.matchMedia("(prefers-color-scheme: dark)"); const apply=()=>{document.documentElement.dataset.theme=saved==="system"?(media.matches?"dark":"light"):saved}; apply(); media.addEventListener("change",apply); return()=>media.removeEventListener("change",apply); },[]);
  useEffect(()=>{ const saved=(localStorage.getItem("frame-backdrop") as Backdrop|null)||"none"; setBackdropState(saved); },[]);
  useEffect(()=>{const saved=localStorage.getItem("frame-locale");const next=preferredLocale(saved||navigator.language);setLocaleState(next);setIdea(current=>Object.values(sampleIdeas).includes(current)?sampleIdeas[next]:current);setImageConcept(current=>Object.values(sampleImageConcepts).includes(current)?sampleImageConcepts[next]:current);document.documentElement.lang=next},[]);
  useEffect(()=>{let cancelled=false;const activeLocale=preferredLocale(localStorage.getItem("frame-locale")||navigator.language);async function restoreAccountConfig(){const savedProvider=localStorage.getItem("frame-provider")||"openrouter";const preset=providerById(savedProvider);const savedBase=localStorage.getItem("frame-api-base")||preset.baseUrl;const savedModel=localStorage.getItem("frame-generation-model")||"";setProviderId(savedProvider);setApiBaseUrl(savedBase);setGenerationModel(savedModel);if(!user){setConfigStatus(translate(activeLocale,"loginSync"));return}setConfigStatus(translate(activeLocale,"restoring"));try{const response=await fetch("/api/model-config",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(translate(activeLocale,"readFailed"));if(cancelled)return;if(data.config){applyAccountConfig(data.config);setConfigStatus(translate(activeLocale,"restored"));clearLegacyKeys();return}const legacyKey=sessionStorage.getItem(`frame-api-key:${savedProvider}`)||sessionStorage.getItem("frame-api-key");if(legacyKey&&savedModel){const migrated=await fetch("/api/model-config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerId:savedProvider,apiBaseUrl:savedBase,model:savedModel,apiKey:legacyKey})});const migratedData=await migrated.json();if(!migrated.ok)throw new Error(translate(activeLocale,"saveFailed"));if(cancelled)return;applyAccountConfig(migratedData.config);clearLegacyKeys();setConfigStatus(translate(activeLocale,"migrated"));return}setConfigStatus(translate(activeLocale,"noAccountConfig"))}catch(error){if(!cancelled)setConfigStatus(error instanceof Error?error.message:translate(activeLocale,"readFailed"))} }restoreAccountConfig();return()=>{cancelled=true}},[user]);
  useEffect(()=>{let cancelled=false;const activeLocale=preferredLocale(localStorage.getItem("frame-locale")||navigator.language);async function restoreImageConfig(){if(!user){setImageConfigStatus(translate(activeLocale,"imageEngineMissing"));return}try{const response=await fetch("/api/image-config",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(translate(activeLocale,"imageConfigFailed"));if(cancelled)return;if(data.config){applyAccountImageConfig(data.config);setImageConfigStatus(translate(activeLocale,"imageEngineSaved"))}else setImageConfigStatus(translate(activeLocale,"imageEngineMissing"))}catch(error){if(!cancelled)setImageConfigStatus(error instanceof Error?error.message:translate(activeLocale,"imageConfigFailed"))}}restoreImageConfig();return()=>{cancelled=true}},[user]);
  useEffect(()=>{const onKeyDown=(event:KeyboardEvent)=>{if(event.key==="Escape"){setThemeOpen(false);setLanguageOpen(false);setBrandOpen(false);setProfileOpen(false);setSettingsOpen(false);return}if(!event.altKey||event.ctrlKey||event.metaKey)return;const target=event.target as HTMLElement|null;if(target?.matches("input, textarea, select, [contenteditable='true']"))return;const next=({"1":"story","2":"image","3":"generate","4":"pose"} as const)[event.key as "1"|"2"|"3"|"4"];if(next){event.preventDefault();setWorkspaceMode(next)}};window.addEventListener("keydown",onKeyDown);return()=>window.removeEventListener("keydown",onKeyDown)},[]);
  function clearLegacyKeys(){sessionStorage.removeItem("frame-api-key");Object.keys(sessionStorage).filter(key=>key.startsWith("frame-api-key:")).forEach(key=>sessionStorage.removeItem(key))}
  function applyAccountConfig(config:AccountModelConfig){setAccountConfig(config);setProviderId(config.providerId);setApiBaseUrl(config.apiBaseUrl);setGenerationModel(config.model);setApiKey("");localStorage.setItem("frame-provider",config.providerId);localStorage.setItem("frame-api-base",config.apiBaseUrl);localStorage.setItem("frame-generation-model",config.model)}
  function applyAccountImageConfig(config:AccountImageConfig){setAccountImageConfig(config);setImageProviderId(config.providerId);setImageApiBaseUrl(config.apiBaseUrl);setImageGenerationModel(config.model);setImageApiKey("")}
  function setTheme(value:Theme){setThemeState(value);localStorage.setItem("frame-theme",value);const dark=value==="dark"||(value==="system"&&matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.dataset.theme=dark?"dark":"light";setThemeOpen(false)}
  function setBackdrop(value:Backdrop){setBackdropState(value);localStorage.setItem("frame-backdrop",value);setBrandOpen(false)}
  function setLocale(value:Locale){setLocaleChanging(true);setLocaleState(value);setIdea(current=>Object.values(sampleIdeas).includes(current)?sampleIdeas[value]:current);setImageConcept(current=>Object.values(sampleImageConcepts).includes(current)?sampleImageConcepts[value]:current);localStorage.setItem("frame-locale",value);document.documentElement.lang=value;setLanguageOpen(false);setConfigStatus(savedKeyMatches?translate(value,"restored"):translate(value,"noAccountConfig"));setNotice(translate(value,"sample"));window.setTimeout(()=>setLocaleChanging(false),520)}
  function trackLight(e:PointerEvent<HTMLElement>){if(e.pointerType!=="mouse"||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;e.currentTarget.style.setProperty("--mx",`${e.clientX}px`);e.currentTarget.style.setProperty("--my",`${e.clientY}px`);e.currentTarget.style.setProperty("--parallax-x",`${(e.clientX-window.innerWidth/2)*.018}px`);e.currentTarget.style.setProperty("--parallax-y",`${(e.clientY-window.innerHeight/2)*.014}px`)}
  function chooseProvider(id:string){const preset=providerById(id);const restored=accountConfig?.providerId===id;setProviderId(id);setApiBaseUrl(restored?accountConfig.apiBaseUrl:preset.baseUrl);setApiKey("");setAvailableModels([]);setGenerationModel(restored?accountConfig.model:"");setConfigStatus(restored?t("foundKey"):t("notVerified",{provider:preset.name}))}
  async function readProviderModels(){if(!apiKey.trim()&&!savedKeyMatches){setConfigStatus(t("needKey"));return}if(!apiBaseUrl.trim()){setConfigStatus(t("apiBaseRequired"));return}setDetectingModels(true);setConfigStatus(savedKeyMatches&&!apiKey.trim()?t("readingAccountKey"):t("validatingKey"));try{const response=await fetch("/api/models",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerId,baseUrl:apiBaseUrl,apiKey:apiKey.trim()})});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("readFailed"));setAvailableModels(data.models||[]);const preferred=(data.models||[]).find((x:ModelOption)=>x.vision)||(data.models||[])[0];if(preferred)setGenerationModel((current:string)=>(data.models||[]).some((x:ModelOption)=>x.id===current)?current:preferred.id);if(data.provider?.id&&providerId==="custom"&&apiKey.trim())setProviderId(data.provider.id);setConfigStatus(t("recognized",{provider:data.provider?.name||t("modelService"),count:(data.models||[]).length}))}catch(error){setAvailableModels([]);setConfigStatus(error instanceof Error?error.message:t("readFailed"))}finally{setDetectingModels(false)}}
  async function saveModelConfig(){if(!generationModel.trim()){setConfigStatus(t("needModel"));return}if(!apiKey.trim()&&!savedKeyMatches){setConfigStatus(t("firstSaveKey"));return}setConfigStatus(t("savingSecure"));try{const response=await fetch("/api/model-config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerId,apiBaseUrl:apiBaseUrl.trim(),model:generationModel.trim(),apiKey:apiKey.trim()||undefined})});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("saveFailed"));applyAccountConfig(data.config);clearLegacyKeys();setConfigStatus(t("savedCloud"));setSettingsOpen(false)}catch(error){setConfigStatus(error instanceof Error?error.message:t("saveFailed"))}}
  async function clearModelConfig(){setConfigStatus(t("deleting"));try{const response=await fetch("/api/model-config",{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("deleteFailed"));clearLegacyKeys();localStorage.removeItem("frame-provider");localStorage.removeItem("frame-api-base");localStorage.removeItem("frame-generation-model");setAccountConfig(null);setProviderId("openrouter");setApiBaseUrl(providerById("openrouter").baseUrl);setApiKey("");setAvailableModels([]);setGenerationModel("");setConfigStatus(t("deletedCloud"))}catch(error){setConfigStatus(error instanceof Error?error.message:t("deleteFailed"))}}
  function chooseImageProvider(id:string){const provider=imageGenerationProviderById(id);const restored=accountImageConfig?.providerId===id;setImageProviderId(id);setImageApiBaseUrl(restored?accountImageConfig.apiBaseUrl:provider.baseUrl);setImageGenerationModel(restored?accountImageConfig.model:provider.models[0]?.id||"");setImageApiKey("");setImageConfigStatus(restored?t("imageEngineSaved"):provider.hint)}
  async function saveImageConfig(){if(!imageGenerationModel.trim()){setImageConfigStatus(t("needModel"));return}if(!imageApiKey.trim()&&!savedImageKeyMatches){setImageConfigStatus(t("firstSaveKey"));return}setImageConfigStatus(t("savingSecure"));try{const response=await fetch("/api/image-config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({providerId:imageProviderId,apiBaseUrl:imageApiBaseUrl.trim(),model:imageGenerationModel.trim(),apiKey:imageApiKey.trim()||undefined})});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("imageConfigFailed"));applyAccountImageConfig(data.config);setImageConfigStatus(t("imageConfigSaved"))}catch(error){setImageConfigStatus(error instanceof Error?error.message:t("imageConfigFailed"))}}
  async function clearImageConfig(){setImageConfigStatus(t("deleting"));try{const response=await fetch("/api/image-config",{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data?.error||t("deleteFailed"));const provider=imageGenerationProviderById("runway");setAccountImageConfig(null);setImageProviderId(provider.id);setImageApiBaseUrl(provider.baseUrl);setImageGenerationModel(provider.models[0].id);setImageApiKey("");setImageConfigStatus(t("imageConfigDeleted"))}catch(error){setImageConfigStatus(error instanceof Error?error.message:t("deleteFailed"))}}
  function activeProviderConfig(){return{providerId,baseUrl:apiBaseUrl.trim(),apiKey:apiKey.trim(),model:generationModel.trim()}}
  async function generate(){
    if(!idea.trim())return;
    if((!apiKey.trim()&&!savedKeyMatches)||!generationModel.trim()){setNotice(t("configRequired"));setSettingsOpen(true);setProfileOpen(false);return}
    setGenerating(true);setNotice(t("generatingStory"));
    try{
      const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"story",locale,idea:idea.trim(),genre,style,duration,platform,videoModel:model,lockCharacters:lock,referenceNotes:imageNotes.trim(),referenceImage:image?.src||null,providerConfig:activeProviderConfig()})});
      const data=await response.json();
      if(!response.ok)throw new Error(data?.error||t("generationFailed"));
      setStory(data.story);setShots(data.shots);setVersion(v=>v+1);setNotice(t("creationComplete"));setActiveTab("story");
    }catch(error){setNotice(error instanceof Error?error.message:t("generationFailed"));}
    finally{setGenerating(false)}
  }
  async function copy(text:string,label:string){await navigator.clipboard.writeText(text);setCopied(label);setTimeout(()=>setCopied(""),1400)}
  function copyAll(){copy(shots.map(s=>`SHOT ${String(s.id).padStart(2,"0")}\n${s.prompt}`).join("\n\n──────────\n\n"),"all")}
  function exportText(){const content=`${story.title}\n\n${t("coreIdea")}: ${idea}\n${t("promptFormat")}: ${optionLabel(locale,model)}\n${t("visualReference")}: ${image?`${image.name} / ${image.orientation} / ${image.color}`:"—"}\n\n${shots.map(s=>`SHOT ${s.id}｜${s.time}｜${s.shot}\n${t("visualStyle")}: ${s.visual}\n${t("camera")}: ${s.camera}\n${t("sound")}: ${s.audio}\n${t("promptSuffix")}:\n${s.prompt}`).join("\n\n")}`;const blob=new Blob([content],{type:"text/plain;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${story.title.replace(/[《》]/g,"")}-${t("shotScript")}.txt`;a.click();URL.revokeObjectURL(a.href)}
  function inspire(){setIdea(ideas[Math.floor(Math.random()*ideas.length)]);setNotice(t("randomLoaded"))}
  async function generateImagePrompt(renderImage=false){
    const workflow:ImageWorkflow=renderImage?imageWorkflow:"text-to-image";
    const concept=workflow==="text-to-image"?imageConcept.trim():imageBriefNotes.trim()||(workflow==="image-to-image"?t("workflowImageDesc"):t("workflowMultiDesc"));
    if(!concept)return;
    if((!apiKey.trim()&&!savedKeyMatches)||!generationModel.trim()){setImagePrompt(t("configRequired"));setSettingsOpen(true);setProfileOpen(false);return}
    if(renderImage&&!accountImageConfig){setImageConfigStatus(t("imageEngineMissing"));setSettingsOpen(true);setProfileOpen(false);return}
    const references=renderImage?(workflow==="text-to-image"?[]:workflow==="image-to-image"?promptReferences.slice(0,1):promptReferences.slice(0,6)):[];
    if(workflow==="image-to-image"&&references.length!==1){setReferenceError(t("singleReferenceRequired"));return}
    if(workflow==="multi-reference"&&references.length<2){setReferenceError(t("multiReferenceRequired"));return}
    setImageGenerating(true);setImagePrompt("");setImagePromptCore("");setGeneratedImage(null);setImageRenderStatus("");
    try{
      const promptTarget=renderImage&&accountImageConfig?imagePromptFamily(accountImageConfig.model):imageModel;
      const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"image-prompt",locale,imageWorkflow:workflow,concept,purpose:imagePurpose,style:imageStyle,aspect:imageAspect,imageModel:promptTarget,referenceNotes:renderImage?imageBriefNotes.trim():"",referenceImages:references.map(item=>({data:item.src,name:item.name,role:item.role,note:item.note.trim()})),providerConfig:activeProviderConfig()})});
      const data=await response.json();
      if(!response.ok)throw new Error(data?.error||"图片提示词生成失败。");
      setImagePromptCore(data.prompt);
      setImagePrompt(`${data.prompt}${data.negativePrompt?`\n\nNEGATIVE / ${t("negative")}\n${data.negativePrompt}`:""}${data.visualAnalysis?`\n\nVISUAL REFERENCE ANALYSIS / ${t("analysis")}\n${data.visualAnalysis}`:""}`);
      if(renderImage)try{await renderGeneratedImage(data.prompt,references,workflow)}catch(error){setImageRenderStatus(error instanceof Error?error.message:t("imageGenerationFailed"))}
    }catch(error){setImagePrompt(error instanceof Error?error.message:t("generationFailed"))}
    finally{setImageGenerating(false)}
  }
  async function requestGeneratedImage(prompt:string,workflow:ImageWorkflow,aspect:string,references:PromptReference[],onStatus:(value:string)=>void){
    if(!accountImageConfig)throw new Error(t("imageEngineMissing"));
    const response=await fetch("/api/generate-image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,workflow,aspect,references:references.map(item=>({data:item.src,role:item.role,note:item.note.trim()}))})});
    let data=await response.json();if(!response.ok)throw new Error(data?.error||t("imageGenerationFailed"));
    if(data.status==="pending"){
      onStatus(t("imageTaskQueued"));
      const query=data.taskId?`taskId=${encodeURIComponent(data.taskId)}`:`pollToken=${encodeURIComponent(data.pollToken)}`;
      for(let attempt=0;attempt<90&&data.status==="pending";attempt++){
        await new Promise(resolve=>window.setTimeout(resolve,1600));
        const progress=await fetch(`/api/generate-image?${query}`,{cache:"no-store"});data=await progress.json();if(!progress.ok)throw new Error(data?.error||t("imageGenerationFailed"));
      }
    }
    if(data.status!=="succeeded"||!data.imageUrl)throw new Error(data?.error||t("imageGenerationFailed"));
    return{src:data.imageUrl,model:data.model||accountImageConfig.model,provider:data.provider||imageGenerationProviderById(accountImageConfig.providerId).name} as GeneratedImage;
  }
  async function renderGeneratedImage(prompt:string,references:PromptReference[],workflow:ImageWorkflow=imageWorkflow){
    setImageRendering(true);setGeneratedImage(null);setImageRenderStatus(t("renderingImage"));
    try{const result=await requestGeneratedImage(prompt,workflow,imageAspect,references,setImageRenderStatus);setGeneratedImage(result);setImageRenderStatus(t("imageReady"))}finally{setImageRendering(false)}
  }
  async function rerenderImage(){if(!imagePromptCore||imageRendering)return;const references=imageWorkflow==="text-to-image"?[]:imageWorkflow==="image-to-image"?promptReferences.slice(0,1):promptReferences.slice(0,6);try{await renderGeneratedImage(imagePromptCore,references)}catch(error){setImageRenderStatus(error instanceof Error?error.message:t("imageGenerationFailed"))}}
  async function downloadImageResult(result:GeneratedImage|null,prefix="FRAME"){if(!result)return;const response=await fetch(result.src);const blob=await response.blob();const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${prefix}-${result.model.replace(/[^a-zA-Z0-9_-]+/g,"-")}-${Date.now()}.png`;link.click();URL.revokeObjectURL(link.href)}
  async function downloadGeneratedImage(){await downloadImageResult(generatedImage)}
  async function readPoseReference(file:File){setPoseStatus("");try{const info=await inspectImageFile(file);setPoseReference({...info,id:crypto.randomUUID(),role:"character",note:t("poseReferenceHint")});setPoseStatus(t("poseReferenceLoaded"))}catch(error){setPoseStatus(error instanceof Error&&error.message==="IMAGE_SIZE"?t("imageTooLarge"):t("chooseImage"))}}
  async function generatePoseImage(){
    if(!accountImageConfig){setImageConfigStatus(t("imageEngineMissing"));setSettingsOpen(true);return}
    const capture=poseRigRef.current?.capture();if(!capture){setPoseStatus(t("poseCaptureFailed"));return}
    const poseGuide:PromptReference={src:capture,name:"FRAME-3D-POSE.png",width:0,height:0,orientation:"portrait",color:"pose guide",tone:"neutral",size:"generated",id:"pose-rig",role:"composition",note:t("poseGuideNote")};
    const references=poseReference?[poseGuide,poseReference]:[poseGuide];
    const workflow:ImageWorkflow=references.length>1?"multi-reference":"image-to-image";
    const concept=poseConcept.trim()||t("poseDefaultPrompt");
    let prompt=`${concept}. ${optionLabel(locale,poseStyle)}. ${t("poseGuideNote")} Full-body character, complete anatomy, hands and feet visible, coherent clothing, clean image.`;
    setPoseGenerating(true);setPoseResult(null);setPosePrompt("");setPoseStatus(t("generatingPose"));
    try{
      if(accountConfig&&generationModel.trim())try{const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"image-prompt",locale,imageWorkflow:workflow,concept,purpose:"角色设定图",style:poseStyle,aspect:poseAspect,imageModel:imagePromptFamily(accountImageConfig.model),referenceNotes:t("poseGuideNote"),referenceImages:references.map(item=>({data:item.src,name:item.name,role:item.role,note:item.note})),providerConfig:activeProviderConfig()})});const data=await response.json();if(response.ok&&data.prompt)prompt=data.prompt}catch{}
      setPosePrompt(prompt);const result=await requestGeneratedImage(prompt,workflow,poseAspect,references,setPoseStatus);setPoseResult(result);setPoseStatus(t("poseReady"));
    }catch(error){setPoseStatus(error instanceof Error?error.message:t("imageGenerationFailed"))}finally{setPoseGenerating(false)}
  }
  async function readImage(file:File){setUploadError("");try{setImage(await inspectImageFile(file));setNotice(t("imageRead"))}catch(error){setUploadError(error instanceof Error&&error.message==="IMAGE_SIZE"?t("imageTooLarge"):t("chooseImage"))}}
  function onDrop(e:DragEvent<HTMLDivElement>){e.preventDefault();const file=e.dataTransfer.files[0];if(file)readImage(file)}
  function changeImageWorkflow(value:ImageWorkflow){setImageWorkflow(value);setImagePrompt("");setImagePromptCore("");setGeneratedImage(null);setImageRenderStatus("");setReferenceError("")}
  async function addPromptReferenceFiles(files:File[]){setReferenceError("");const limit=imageWorkflow==="image-to-image"?1:6;const incoming=imageWorkflow==="image-to-image"?files.slice(0,1):files.slice(0,Math.max(0,limit-promptReferences.length));if(!incoming.length){setReferenceError(t("referenceLimit"));return}const next:PromptReference[]=[];for(const file of incoming){try{const info=await inspectImageFile(file);const index=(imageWorkflow==="image-to-image"?0:promptReferences.length+next.length);next.push({...info,id:crypto.randomUUID(),role:imageWorkflow==="image-to-image"?"source":referenceRoles[Math.min(index,referenceRoles.length-1)],note:""})}catch(error){setReferenceError(error instanceof Error&&error.message==="IMAGE_SIZE"?t("imageTooLarge"):t("chooseImage"))}}if(next.length)setPromptReferences(current=>imageWorkflow==="image-to-image"?next.slice(0,1):[...current,...next].slice(0,6))}
  function onPromptReferenceDrop(e:DragEvent<HTMLDivElement>){e.preventDefault();void addPromptReferenceFiles(Array.from(e.dataTransfer.files))}
  function updatePromptReference(id:string,field:"role"|"note",value:string){setPromptReferences(current=>current.map(item=>item.id===id?{...item,[field]:value}:item))}
  function removePromptReference(id:string){setPromptReferences(current=>current.filter(item=>item.id!==id));setImagePrompt("")}
  const imageWorkflowReady=imageWorkflow==="text-to-image"||(imageWorkflow==="image-to-image"&&promptReferences.length>=1)||(imageWorkflow==="multi-reference"&&promptReferences.length>=2);
  const activeReferenceCount=imageWorkflow==="image-to-image"?Math.min(1,promptReferences.length):promptReferences.length;
  const referenceCounter=imageWorkflow==="image-to-image"?`${activeReferenceCount} / 1`:t("referenceCount",{count:activeReferenceCount});
  const initials=(user?.displayName||user?.email||t("guest")).slice(0,1).toUpperCase(); const themeLabel={light:t("day"),dark:t("night"),system:t("followSystem")}[theme]; const activeLanguage=LANGUAGE_OPTIONS.find(item=>item.id===locale)||LANGUAGE_OPTIONS[0];
  const modelBrand=detectModelBrand(generationModel,providerId); const filteredModels=availableModels.filter(item=>`${item.name} ${item.id}`.toLowerCase().includes(modelSearch.toLowerCase())).slice(0,160);
  const selectedImageProvider=imageGenerationProviderById(imageProviderId); const renderImageModel=accountImageConfig?imagePromptFamily(accountImageConfig.model):imageModel;

  return <main id="studio-content" tabIndex={-1} onPointerMove={trackLight} className={`backdrop-${backdrop} locale-${locale} ${localeChanging?"locale-changing":""}`}>
    <a className="skip-link" href="#studio-content">{t("creationHome")}</a>
    <BackdropVisual mode={backdrop}/><div className="ambient ambient-one"/><div className="ambient ambient-two"/><div className="noise"/>
    <header className="topbar">
      <div className="brand-area"><button className="brand" onClick={()=>{setBrandOpen(v=>!v);setThemeOpen(false);setLanguageOpen(false);setProfileOpen(false)}} aria-expanded={brandOpen} aria-label={`FRAME ${t("background")}`}><span className="brand-symbol"><b>F</b><i/></span><span className="brand-word">FRAME</span><em>AI STORY STUDIO</em></button>{brandOpen&&<div className="brand-menu popover"><span className="popover-title">{t("background")}</span><button className={backdrop==="none"?"selected":""} onClick={()=>setBackdrop("none")}><i className="mini blank"/><span><b>{t("cleanCanvas")}</b><small>{t("focusCreate")}</small></span></button><button className={backdrop==="globe"?"selected":""} onClick={()=>setBackdrop("globe")}><i className="mini globe-mini"/><span><b>{t("orbital")}</b><small>{t("worldMode")}</small></span></button><button className={backdrop==="mind"?"selected":""} onClick={()=>setBackdrop("mind")}><i className="mini mind-mini"/><span><b>{t("neural")}</b><small>{t("ideaMode")}</small></span></button></div>}</div>
      <div className="top-actions">
        {workspaceMode!=="home"&&<nav className="studio-switcher" aria-label={t("creationHome")}><button className="module-home" onClick={()=>setWorkspaceMode("home")} title={t("creationHome")}>←</button>{([['story','01','STORY','enterStory'],['image','02','PROMPT','enterImage'],['generate','03','RENDER','enterRender'],['pose','04','POSE','enterPose']] as const).map(([mode,index,label,title])=><button key={mode} className={workspaceMode===mode?"active":""} aria-pressed={workspaceMode===mode} onClick={()=>setWorkspaceMode(mode)} title={`${t(title)} · Alt+${index.slice(-1)}`}><i>{index}</i><span>{label}</span></button>)}</nav>}
        {generationModel&&<button className="active-model-pill" onClick={()=>setSettingsOpen(true)}>{modelBrand.logo?<img src={modelBrand.logo} alt=""/>:<i>{modelBrand.short}</i>}<span>{generationModel}</span></button>}
        <div className="language-wrap"><button className="utility-button language-button" onClick={()=>{setLanguageOpen(v=>!v);setThemeOpen(false);setBrandOpen(false);setProfileOpen(false)}} aria-label={t("language")} aria-expanded={languageOpen}><span className="language-icon">文</span><small>{activeLanguage.short}</small></button>{languageOpen&&<div className="language-menu popover"><span className="popover-title">{t("language")} / LANGUAGE</span>{LANGUAGE_OPTIONS.map(item=><button key={item.id} className={locale===item.id?"selected":""} onClick={()=>setLocale(item.id)}><i>{item.id==="en"?"A":item.id==="ja"?"あ":"文"}</i><span><b>{item.native}</b><small>{item.id}</small></span><em>{locale===item.id?"✓":""}</em></button>)}</div>}</div>
        <div className="theme-wrap"><button className="utility-button" onClick={()=>{setThemeOpen(v=>!v);setLanguageOpen(false);setBrandOpen(false);setProfileOpen(false)}} aria-label={t("siteTone")}><span className="theme-icon">{theme==="dark"?"◐":theme==="light"?"☼":"◒"}</span><small>{themeLabel}</small></button>{themeOpen&&<div className="theme-menu popover"><span className="popover-title">{t("siteTone")}</span>{(["light","dark","system"] as Theme[]).map(x=><button key={x} className={theme===x?"selected":""} onClick={()=>setTheme(x)}><i>{x==="light"?"☼":x==="dark"?"◐":"◒"}</i><span>{x==="light"?t("day"):x==="dark"?t("night"):t("followSystem")}</span><b>✓</b></button>)}</div>}</div>
        <div className="profile-wrap"><button className="avatar" onClick={()=>{setProfileOpen(v=>!v);setThemeOpen(false);setLanguageOpen(false);setBrandOpen(false)}} aria-label={t("profile")}>{initials}</button>{profileOpen&&<div className="profile-card popover"><div className="profile-head"><span className="profile-avatar">{initials}</span><div><b>{user?.displayName||t("guest")}</b><small>{user?.email||t("noLogin")}</small></div></div>{user?<><dl><div><dt>{t("accountStatus")}</dt><dd><i/>{t("signedIn")}</dd></div><div><dt>{t("identity")}</dt><dd>{user.userId.slice(0,8)}••••</dd></div><div><dt>{t("generationModel")}</dt><dd className="profile-model">{generationModel||t("unconfigured")}</dd></div><div><dt>{t("imageEngine")}</dt><dd className="profile-model">{accountImageConfig?.model||t("unconfigured")}</dd></div></dl><button className="profile-config-button" onClick={()=>{setSettingsOpen(true);setProfileOpen(false)}}><span>{t("modelSettings")}</span><b>API KEY / MODEL →</b></button><a href="/signout-with-chatgpt?return_to=/">{t("logout")}</a></>:<a href="/signin-with-chatgpt?return_to=/">{t("login")}</a>}</div>}</div>
      </div>
    </header>
    {settingsOpen&&<div className="settings-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSettingsOpen(false)}}><section className="model-settings" role="dialog" aria-modal="true" aria-label={t("modelSettings")}>
      <div className="settings-head"><div><span>PROFILE / AI MODEL ROUTER</span><h2>{t("connectModel")}</h2><p>{t("connectModelDesc")}</p></div><button onClick={()=>setSettingsOpen(false)} aria-label={t("close")}>×</button></div>
      <div className="settings-body">
        <div className="settings-section-title"><span>01</span><div><b>{t("selectProvider")}</b><small>{t("openRouterTip")}</small></div></div>
        <div className="provider-grid">{MODEL_PROVIDERS.map(provider=><button key={provider.id} className={providerId===provider.id?"selected":""} onClick={()=>chooseProvider(provider.id)}>{provider.logo?<img src={provider.logo} alt=""/>:<i>{provider.short}</i>}<span><b>{provider.name}</b><small>{locale==="zh-CN"?provider.hint:provider.protocol.toUpperCase()}</small></span>{providerId===provider.id&&<em>✓</em>}</button>)}</div>

        <div className="settings-section-title"><span>02</span><div><b>{t("connectApi")}</b><small>{t("encryptionTip")}</small></div></div>
        <div className="api-fields"><label><span>API BASE URL</span><input value={apiBaseUrl} onChange={e=>setApiBaseUrl(e.target.value)} placeholder="https://api.example.com/v1"/></label><label><span>API KEY {savedKeyMatches&&<b className="saved-key-mark">{t("accountSaved")}</b>}</span><div className="secret-input"><input type={showApiKey?"text":"password"} value={apiKey} onChange={e=>setApiKey(e.target.value)} autoComplete="new-password" placeholder={savedKeyMatches?t("savedKeyPlaceholder"):t("keyPlaceholder")}/><button onClick={()=>setShowApiKey(v=>!v)}>{showApiKey?t("hide"):t("show")}</button></div></label></div>
        <div className="model-detect-row"><button className="detect-models" onClick={readProviderModels} disabled={detectingModels}>{detectingModels?t("detecting"):t("detectModels")}</button><span aria-live="polite" className={savedKeyMatches||configStatus.startsWith("已")?"ok":""}><i/>{configStatus}</span></div>

        <div className="settings-section-title"><span>03</span><div><b>{t("selectModel")}</b><small>{t("brandTip")}</small></div></div>
        {availableModels.length?<><div className="model-search"><input value={modelSearch} onChange={e=>setModelSearch(e.target.value)} placeholder={t("searchModels",{count:availableModels.length})}/><span>{filteredModels.length} RESULTS</span></div><div className="model-list">{filteredModels.map(item=>{const brand=detectModelBrand(item.id,providerId);return <button key={item.id} className={generationModel===item.id?"selected":""} onClick={()=>setGenerationModel(item.id)}>{brand.logo?<img src={brand.logo} alt=""/>:<i>{brand.short}</i>}<span><b>{item.name}</b><small>{item.id}</small></span>{item.vision&&<em>VISION</em>}{generationModel===item.id&&<strong>✓</strong>}</button>})}</div></>:<label className="manual-model"><span>{t("manualModel")}</span><input value={generationModel} onChange={e=>setGenerationModel(e.target.value)} placeholder="anthropic/claude-sonnet-latest"/><small>{t("manualTip")}</small></label>}

        <div className="image-engine-settings">
          <div className="settings-section-title"><span>04</span><div><b>{t("imageEngine")}</b><small>{t("imageEngineDesc")}</small></div></div>
          <div className="provider-grid image-provider-grid">{IMAGE_GENERATION_PROVIDERS.map(provider=><button key={provider.id} className={imageProviderId===provider.id?"selected":""} onClick={()=>chooseImageProvider(provider.id)}>{provider.logo?<img src={provider.logo} alt=""/>:<i>{provider.short}</i>}<span><b>{provider.name}</b><small>{provider.hint}</small></span>{imageProviderId===provider.id&&<em>✓</em>}</button>)}</div>
          <div className="api-fields"><label><span>IMAGE API BASE URL</span><input value={imageApiBaseUrl} onChange={e=>setImageApiBaseUrl(e.target.value)} placeholder={selectedImageProvider.baseUrl}/></label><label><span>IMAGE API KEY {savedImageKeyMatches&&<b className="saved-key-mark">{t("accountSaved")}</b>}</span><div className="secret-input"><input type={showImageApiKey?"text":"password"} value={imageApiKey} onChange={e=>setImageApiKey(e.target.value)} autoComplete="new-password" placeholder={savedImageKeyMatches?t("savedKeyPlaceholder"):t("engineKeyPlaceholder")}/><button onClick={()=>setShowImageApiKey(value=>!value)}>{showImageApiKey?t("hide"):t("show")}</button></div></label></div>
          <label className="manual-model image-engine-model"><span>{t("imageEngineModel")}</span><input list="image-engine-models" value={imageGenerationModel} onChange={e=>setImageGenerationModel(e.target.value)} placeholder={selectedImageProvider.models[0]?.id}/><datalist id="image-engine-models">{selectedImageProvider.models.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</datalist><small>{selectedImageProvider.models.map(item=>item.name).join(" · ")}</small></label>
          <div className="image-config-actions"><span aria-live="polite" className={savedImageKeyMatches?"ok":""}><i/>{imageConfigStatus}</span><div><button className="clear-config" onClick={clearImageConfig}>{t("deleteImageEngine")}</button><button className="save-config" onClick={saveImageConfig}>{t("saveImageEngine")} <b>↗</b></button></div></div>
        </div>
      </div>
      <div className="settings-footer"><div className="selected-engine">{modelBrand.logo?<img src={modelBrand.logo} alt=""/>:<i>{modelBrand.short}</i>}<span><small>{savedKeyMatches?t("accountConnected"):t("currentEngine")}</small><b>{generationModel||t("noModel")}</b></span></div><div><button className="clear-config" onClick={clearModelConfig}>{t("deleteConfig")}</button><button className="save-config" onClick={saveModelConfig}>{t("saveAccount")} <b>↗</b></button></div></div>
    </section></div>}
    {workspaceMode==="home"?<section className="welcome-screen">
      <IdeaField locale={locale}/>
      <div className="welcome-copy"><span className="eyebrow"><span/> FRAME CREATIVE OS</span><h1>{t("welcomeBack")}<br/><em>{(user?.displayName||t("creator")).split("@")[0]}</em><b className="welcome-period">。</b></h1><p>{t("welcomeDesc")}</p><div className="welcome-status"><i/><span>{t("ready")}</span><b>{t("formatCount",{video:models.length,image:imageModels.length})}</b></div></div>
      <div className="module-grid">
        <button className="module-card story-module" onClick={()=>setWorkspaceMode("story")}><span className="module-index">01</span><div className="module-visual storyboard-visual"><i/><i/><i/><b>▶</b></div><div className="module-meta"><span>VIDEO NARRATIVE</span><h2>AI STORY<br/>STUDIO</h2><p>{t("storyModuleDesc")}</p><em>{t("enterStory")} <b>↗</b></em></div></button>
        <button className="module-card image-module" onClick={()=>setWorkspaceMode("image")}><span className="module-index">02</span><div className="module-visual image-visual"><i/><i/><span/><b>✦</b></div><div className="module-meta"><span>IMAGE DIRECTION</span><h2>IMAGE PROMPT<br/>STUDIO</h2><p>{t("imageModuleDesc")}</p><em>{t("enterImage")} <b>↗</b></em></div></button>
        <button className="module-card render-module" onClick={()=>setWorkspaceMode("generate")}><span className="module-index">03</span><div className="module-visual render-visual"><i/><i/><span/><b>◈</b></div><div className="module-meta"><span>IMAGE GENERATION</span><h2>IMAGE RENDER<br/>STUDIO</h2><p>{t("renderModuleDesc")}</p><em>{t("enterRender")} <b>↗</b></em></div></button>
        <button className="module-card pose-module" onClick={()=>setWorkspaceMode("pose")}><span className="module-index">04</span><div className="module-visual pose-visual"><span className="pose-head"/><span className="pose-body"/><i className="pose-arm left"/><i className="pose-arm right"/><i className="pose-leg left"/><i className="pose-leg right"/><b>3D</b></div><div className="module-meta"><span>CHARACTER POSE</span><h2>POSE RIG<br/>STUDIO</h2><p>{t("poseModuleDesc")}</p><em>{t("enterPose")} <b>↗</b></em></div></button>
      </div>
    </section>:workspaceMode==="image"?<section className="image-studio">
      <aside className="image-control">
        <span className="eyebrow"><span/> IMAGE PROMPT STUDIO</span><h1>{t("describeFrame")}</h1><p className="intro">{t("imageIntro")}</p>
        <label className="field-label">01 / {t("imageIdea")}</label><div className="textarea-wrap image-textarea"><textarea value={imageConcept} onChange={e=>setImageConcept(e.target.value)} maxLength={500}/><span>{imageConcept.length}/500</span></div>
        <div className="split-fields"><div><label className="field-label">02 / {t("imagePurpose")}</label><select value={imagePurpose} onChange={e=>setImagePurpose(e.target.value)}>{imagePurposes.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div><div><label className="field-label">03 / {t("visualStyle")}</label><select value={imageStyle} onChange={e=>setImageStyle(e.target.value)}>{imageStyles.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div></div>
        <div className="split-fields"><div><label className="field-label">04 / {t("imageModel")}</label><select value={imageModel} onChange={e=>setImageModel(e.target.value)}>{imageModels.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div><div><label className="field-label">05 / {t("aspect")}</label><select value={imageAspect} onChange={e=>setImageAspect(e.target.value)}>{imageAspects.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div></div>
        <div className="prompt-only-note"><i>Aa</i><span><b>{t("promptOnly")}</b><small>{t("promptStudioOnlyDesc")}</small></span></div>
        <button className="generate" onClick={()=>generateImagePrompt(false)} disabled={imageGenerating||!imageConcept.trim()}><span>{imageGenerating?t("generatingImage"):t("generateImage")}</span><b>{imageGenerating?"···":"↗"}</b></button><p className="hint">{t("multimodalHint")}</p>
      </aside>
      <section className="image-output"><div className="image-output-head"><div><span>OUTPUT / {imageModel.toUpperCase()}</span><h2>{t("promptSuffix")}</h2></div><div className="image-output-actions">{imagePrompt&&<button className="export" onClick={()=>copy(imagePrompt,"imagePrompt")}>{copied==="imagePrompt"?t("copied"):t("copyPrompt")}</button>}</div></div>
        <div className={`image-canvas ${imagePrompt?"has-prompt":""}`}><div className="canvas-grid"/><div className="canvas-center"><i>✦</i><b>{imagePrompt?"PROMPT READY":"WAITING FOR A FRAME"}</b><small>{imagePrompt?`${imageModel} · ${optionLabel(locale,imageAspect)}`:t("waitingFrame")}</small></div><span className="canvas-corner c1"/><span className="canvas-corner c2"/><span className="canvas-corner c3"/><span className="canvas-corner c4"/></div>{imagePrompt?<div className="image-prompt-card"><span>MODEL-READY IMAGE PROMPT</span><pre>{imagePrompt}</pre><div><b>{imageModel}</b><b>{optionLabel(locale,imageStyle)}</b><b>{optionLabel(locale,imageAspect)}</b></div></div>:<div className="image-empty-notes"><p><b>01</b> {t("imageStep1")}</p><p><b>02</b> {t("imageStep2")}</p><p><b>03</b> {t("imageStep3")}</p></div>}
      </section>
    </section>:workspaceMode==="generate"?<section className="image-studio render-studio">
      <aside className="image-control">
        <span className="eyebrow"><span/> IMAGE RENDER STUDIO</span><h1>{t("imageRenderStudio")}</h1><p className="intro">{t("renderIntro")}</p>
        <label className="field-label">01 / {t("imageWorkflow")}</label><div className="image-workflow-switch">{imageWorkflows.map((value,index)=>{const label=value==="text-to-image"?t("workflowText"):value==="image-to-image"?t("workflowImage"):t("workflowMulti");const description=value==="text-to-image"?t("workflowTextDesc"):value==="image-to-image"?t("workflowImageDesc"):t("workflowMultiDesc");return <button key={value} className={imageWorkflow===value?"selected":""} onClick={()=>changeImageWorkflow(value)}><i>{index===0?"Aa":index===1?"01":"∞"}</i><span><b>{label}</b><small>{description}</small></span><em>0{index+1}</em></button>})}</div>
        {imageWorkflow==="text-to-image"&&<><label className="field-label">02 / {t("imageIdea")}</label><div className="textarea-wrap image-textarea"><textarea value={imageConcept} onChange={e=>setImageConcept(e.target.value)} maxLength={500}/><span>{imageConcept.length}/500</span></div></>}
        <div className="split-fields"><div><label className="field-label">03 / {t("visualStyle")}</label><select value={imageStyle} onChange={e=>setImageStyle(e.target.value)}>{imageStyles.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div><div><label className="field-label">04 / {t("aspect")}</label><select value={imageAspect} onChange={e=>setImageAspect(e.target.value)}>{imageAspects.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div></div>
        <label className="field-label"><span>05 / {imageWorkflow==="text-to-image"?t("workflowText"):imageWorkflow==="image-to-image"?t("sourceImage"):t("multiReferences")}</span>{imageWorkflow!=="text-to-image"&&<b>{referenceCounter}</b>}</label>
        {imageWorkflow==="text-to-image"?<div className="workflow-context-card"><i>Aa</i><span><b>{t("workflowText")}</b><small>{t("workflowTextDesc")}</small></span></div>:<div className="reference-manager"><div className="upload-zone compact-upload reference-upload" role="button" tabIndex={0} onClick={()=>imageFileRef.current?.click()} onKeyDown={e=>{if(e.key==="Enter")imageFileRef.current?.click()}} onDragOver={e=>e.preventDefault()} onDrop={onPromptReferenceDrop}><input ref={imageFileRef} type="file" multiple={imageWorkflow==="multi-reference"} accept="image/jpeg,image/png,image/webp" onChange={e=>{void addPromptReferenceFiles(Array.from(e.target.files||[]));e.currentTarget.value=""}}/><span className="upload-icon">＋</span><b>{imageWorkflow==="image-to-image"?t("addSource"):t("addMultiple")}</b><small>JPG / PNG / WebP · 10MB</small></div>{promptReferences.length>0&&<div className={`reference-grid ${imageWorkflow==="image-to-image"?"single":""}`}>{promptReferences.slice(0,imageWorkflow==="image-to-image"?1:6).map((item,index)=><article className="reference-card" key={item.id}><div className="reference-thumb"><img src={item.src} alt={`${t("referenceImage")} ${index+1}`}/><b>{String(index+1).padStart(2,"0")}</b><button onClick={()=>removePromptReference(item.id)} aria-label={t("close")}>×</button></div><div className="reference-card-body"><span>{item.name}</span>{imageWorkflow==="multi-reference"?<label><small>{t("referenceRole")}</small><select value={item.role} onChange={e=>updatePromptReference(item.id,"role",e.target.value)}>{referenceRoles.map(role=><option key={role} value={role}>{referenceRoleLabel(locale,role)}</option>)}</select></label>:<em>{referenceRoleLabel(locale,"source")}</em>}<input value={item.note} onChange={e=>updatePromptReference(item.id,"note",e.target.value)} placeholder={t("referenceNote")}/></div></article>)}</div>}<label className="reference-direction"><span>{t("globalDirection")}</span><textarea value={imageBriefNotes} onChange={e=>setImageBriefNotes(e.target.value)} placeholder={t("globalDirectionPlaceholder")} maxLength={400}/></label></div>}
        {referenceError&&<p className="upload-error">{referenceError}</p>}<div className="engine-connection"><span className={accountImageConfig?"connected":""}><i/>{accountImageConfig?`${imageGenerationProviderById(accountImageConfig.providerId).name} · ${accountImageConfig.model}`:t("imageEngineMissing")}</span><button onClick={()=>setSettingsOpen(true)}>{accountImageConfig?t("imageEngineSaved"):t("openImageSettings")}</button></div>
        <button className="generate" onClick={()=>generateImagePrompt(true)} disabled={imageGenerating||imageRendering||!imageWorkflowReady||(imageWorkflow==="text-to-image"&&!imageConcept.trim())}><span>{imageGenerating||imageRendering?t("renderingImage"):t("actualImageGeneration")}</span><b>{imageGenerating||imageRendering?"···":"↗"}</b></button><p className="hint">{imageRenderStatus||t("renderDirectHint")}</p>
      </aside>
      <section className="image-output"><div className="image-output-head"><div><span>OUTPUT / {renderImageModel.toUpperCase()}</span><h2>{imageWorkflow==="text-to-image"?t("workflowText"):imageWorkflow==="image-to-image"?t("workflowImage"):t("workflowMulti")} · {generatedImage?t("imageReady"):t("actualImageGeneration")}</h2></div><div className="image-output-actions">{imagePrompt&&<button className="export" onClick={()=>copy(imagePrompt,"renderPrompt")}>{copied==="renderPrompt"?t("copied"):t("copyPrompt")}</button>}{generatedImage&&<button className="export image-download" onClick={downloadGeneratedImage}>↓ {t("downloadImage")}</button>}</div></div>
        {imageWorkflow!=="text-to-image"&&promptReferences.length>0&&<div className="canvas-reference-strip"><span>{referenceCounter}</span>{promptReferences.slice(0,imageWorkflow==="image-to-image"?1:6).map((item,index)=><div key={item.id}><img src={item.src} alt=""/><b>{index+1}</b><small>{referenceRoleLabel(locale,item.role)}</small></div>)}</div>}<div className={`image-canvas ${imagePrompt&&!generatedImage?"has-prompt":""} ${generatedImage?"has-generated-image":""}`}>{generatedImage?<img className="generated-artwork" src={generatedImage.src} alt={imageConcept||t("actualImageGeneration")}/>:<><div className="canvas-grid"/><div className="canvas-center"><i>◈</i><b>{imagePrompt?"RENDER PROMPT READY":"WAITING FOR A FRAME"}</b><small>{imagePrompt?`${renderImageModel} · ${optionLabel(locale,imageAspect)}`:t("waitingFrame")}</small></div></>}<span className="canvas-corner c1"/><span className="canvas-corner c2"/><span className="canvas-corner c3"/><span className="canvas-corner c4"/>{imageRendering&&<div className="image-render-mask"><i/><b>{t("renderingImage")}</b><span>{imageRenderStatus}</span></div>}</div>{generatedImage&&<div className="generated-image-meta"><span><i/> {t("imageReady")}</span><b>{generatedImage.provider} · {generatedImage.model}</b><button onClick={rerenderImage} disabled={imageRendering}>↻ {t("directGenerate")}</button></div>}{imageRenderStatus&&!imageRendering&&!generatedImage&&<div className="image-render-error"><i>!</i><span>{imageRenderStatus}</span>{imagePromptCore&&<button onClick={rerenderImage}>↻</button>}</div>}{imagePrompt&&<div className="image-prompt-card"><span>MODEL-READY RENDER PROMPT</span><pre>{imagePrompt}</pre><div><b>{renderImageModel}</b><b>{optionLabel(locale,imageStyle)}</b><b>{optionLabel(locale,imageAspect)}</b></div></div>}
      </section>
    </section>:workspaceMode==="pose"?<section className="pose-studio">
      <aside className="pose-control"><span className="eyebrow"><span/> POSE RIG STUDIO</span><h1>{t("poseStudio")}</h1><p className="intro">{t("poseIntro")}</p><label className="field-label">01 / {t("posePrompt")}</label><div className="textarea-wrap image-textarea"><textarea value={poseConcept} onChange={e=>setPoseConcept(e.target.value)} placeholder={t("posePromptPlaceholder")} maxLength={500}/><span>{poseConcept.length}/500</span></div><div className="split-fields"><div><label className="field-label">02 / {t("visualStyle")}</label><select value={poseStyle} onChange={e=>setPoseStyle(e.target.value)}>{imageStyles.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div><div><label className="field-label">03 / {t("aspect")}</label><select value={poseAspect} onChange={e=>setPoseAspect(e.target.value)}>{imageAspects.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div></div><label className="field-label">04 / {t("poseReference")}</label>{poseReference?<div className="image-preview pose-reference-preview"><img src={poseReference.src} alt={t("poseReference")}/><div className="image-info"><b>{poseReference.name}</b><span>{t("poseReferenceLoaded")}</span></div><button onClick={()=>setPoseReference(null)} aria-label={t("close")}>×</button></div>:<div className="upload-zone compact-upload" role="button" tabIndex={0} onClick={()=>poseFileRef.current?.click()} onKeyDown={e=>{if(e.key==="Enter")poseFileRef.current?.click()}}><input ref={poseFileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void readPoseReference(file);e.currentTarget.value=""}}/><span className="upload-icon">＋</span><b>{t("addReference")}</b><small>{t("poseReferenceHint")}</small></div>}<div className="engine-connection"><span className={accountImageConfig?"connected":""}><i/>{accountImageConfig?`${imageGenerationProviderById(accountImageConfig.providerId).name} · ${accountImageConfig.model}`:t("imageEngineMissing")}</span><button onClick={()=>setSettingsOpen(true)}>{t("openImageSettings")}</button></div><button className="generate" onClick={generatePoseImage} disabled={poseGenerating}><span>{poseGenerating?t("generatingPose"):t("usePoseAndRender")}</span><b>{poseGenerating?"···":"↗"}</b></button><p className="hint">{poseStatus||t("poseGenerateHint")}</p></aside>
      <section className="pose-editor"><div className="pose-editor-head"><div><span>3D JOINT MANIPULATOR</span><h2>{t("poseEditor")}</h2></div><small>{t("orbitHint")}</small></div><div className="pose-presets">{(["neutral","action","seated","reach"] as PosePreset[]).map((preset,index)=><button key={preset} onClick={()=>poseRigRef.current?.applyPreset(preset)}><i>0{index+1}</i>{t(`posePreset${preset[0].toUpperCase()}${preset.slice(1)}`)}</button>)}<button onClick={()=>poseRigRef.current?.mirror()}><i>↔</i>{t("mirrorPose")}</button><button onClick={()=>poseRigRef.current?.reset()}><i>↺</i>{t("resetPose")}</button></div><div className="pose-stage"><PoseErrorBoundary fallback={<div className="pose-loading pose-failed"><b>!</b><span>{t("poseCaptureFailed")}</span></div>}><Suspense fallback={<div className="pose-loading"><i/><span>{t("poseEditor")}</span></div>}><PoseRig ref={poseRigRef} ariaLabel={t("poseEditor")}/></Suspense></PoseErrorBoundary><div className="pose-stage-label"><i/><span>LIVE 3D POSE</span></div><div className="pose-axis"><b>Y</b><span>X</span><em>Z</em></div></div></section>
      <section className="pose-output"><div className="pose-output-head"><div><span>POSE-GUIDED OUTPUT</span><h2>{poseResult?t("poseReady"):t("poseResult")}</h2></div>{poseResult&&<button className="export" onClick={()=>downloadImageResult(poseResult,"FRAME-POSE")}>↓ {t("downloadImage")}</button>}</div><div className={`pose-result-frame ${poseResult?"ready":""}`}>{poseResult?<img src={poseResult.src} alt={poseConcept}/>:<div><i>◇</i><b>{t("poseWaiting")}</b><span>{t("poseWaitingDesc")}</span></div>}{poseGenerating&&<div className="image-render-mask"><i/><b>{t("generatingPose")}</b><span>{poseStatus}</span></div>}</div>{poseResult&&<div className="generated-image-meta"><span><i/> {t("poseReady")}</span><b>{poseResult.provider} · {poseResult.model}</b></div>}{posePrompt&&<div className="pose-prompt-card"><span>POSE-AWARE IMAGE PROMPT</span><p>{posePrompt}</p><button onClick={()=>copy(posePrompt,"posePrompt")}>{copied==="posePrompt"?t("copied"):t("copyPrompt")}</button></div>}</section>
    </section>:<section className="workspace">
      <aside className="control-panel"><div className="eyebrow"><span/> NEW PROJECT</div><h1>{t("turnIdea")}</h1><p className="intro">{t("storyIntro")}</p>
        <label className="field-label"><span>01 / {t("coreIdea")}</span><button className="text-action" onClick={inspire}>✦ {t("randomIdea")}</button></label><div className="textarea-wrap"><textarea value={idea} onChange={e=>setIdea(e.target.value)} maxLength={300} aria-label={t("coreIdea")}/><span>{idea.length}/300</span></div>
        <label className="field-label"><span>02 / {t("visualReference")}</span><b>{t("aiUnderstands")}</b></label>{image?<div className="image-preview"><img src={image.src} alt={t("visualReference")}/><div className="image-info"><b>{image.name}</b><span>{image.width}×{image.height} · {image.orientation} · {image.size}</span><span>{image.tone} · {image.color}</span></div><button onClick={()=>{setImage(null);setImageNotes("")}} aria-label={t("close")}>×</button></div>:<div className="upload-zone" role="button" tabIndex={0} onClick={()=>fileRef.current?.click()} onKeyDown={e=>{if(e.key==="Enter")fileRef.current?.click()}} onDragOver={e=>e.preventDefault()} onDrop={onDrop}><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)readImage(f)}}/><span className="upload-icon">＋</span><b>{t("dropImage")}</b><small>{t("maxImage")}</small></div>}{uploadError&&<p className="upload-error">{uploadError}</p>}{image&&<input className="reference-note" value={imageNotes} onChange={e=>setImageNotes(e.target.value)} placeholder={t("referenceNote")}/>}
        <div className="split-fields"><div><label className="field-label">03 / {t("genre")}</label><select value={genre} onChange={e=>setGenre(e.target.value)}>{genres.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div><div><label className="field-label">04 / {t("visualStyle")}</label><select value={style} onChange={e=>setStyle(e.target.value)}>{styles.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div></div>
        <label className="field-label">05 / {t("duration")} <b>{duration} {t("seconds")}</b></label><input className="range" type="range" min="15" max="60" step="15" value={duration} onChange={e=>setDuration(Number(e.target.value))}/><div className="ticks"><span>15s</span><span>30s</span><span>45s</span><span>60s</span></div>
        <div className="split-fields"><div><label className="field-label">06 / {t("platform")}</label><select value={platform} onChange={e=>setPlatform(e.target.value)}>{platforms.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div><div><label className="field-label">07 / {t("promptFormat")}</label><select value={model} onChange={e=>setModel(e.target.value)}>{models.map(x=><option key={x} value={x}>{optionLabel(locale,x)}</option>)}</select></div></div>
        <label className="lock-option"><span><b>{t("consistency")}</b><small>{t("consistencyHint")}</small></span><input type="checkbox" checked={lock} onChange={e=>setLock(e.target.checked)}/><i/></label>
        <button className="generate" onClick={generate} disabled={generating||!idea.trim()}><span>{generating?t("generatingStory"):image?t("generateWithImage"):t("generateStory")}</span><b>{generating?"···":"↗"}</b></button><p className="hint">{t("realGeneration")}</p>
      </aside>
      <section className={`result-panel ${generating?"is-generating":""}`} key={version} aria-busy={generating}><div className="result-head"><div className="tabs"><button className={activeTab==="story"?"active":""} onClick={()=>setActiveTab("story")}>{t("outline")}</button><button className={activeTab==="shots"?"active":""} onClick={()=>setActiveTab("shots")}>{t("shotScript")} <small>{shots.length}</small></button></div><div className="result-actions"><span className="result-notice" aria-live="polite">{notice}</span><button className="export" onClick={copyAll}>{copied==="all"?t("copied"):t("copyAll")}</button><button className="export" onClick={exportText}>↓ {t("export")}</button></div></div>
        {generating&&<div className="generating-mask"><i/><b>{notice}</b><span>{t("organizing")}</span></div>}
        {version===0&&!generating&&<div className="result-empty-state"><div className="empty-orbit"><i/><i/><i/><b>F</b></div><span>FRAME / ORIGINAL GENERATION</span><h2>{t("awaitingTitle")}</h2><p>{t("awaitingDesc")}</p><em>{t("awaitingAction")} <b>↗</b></em></div>}
        <div className={version===0?"pre-generation-hidden":""}>
        {activeTab==="story"?<div className="story-view">{image&&<div className="reference-ribbon"><img src={image.src} alt={t("visualReference")}/><div><span>VISUAL REFERENCE CONNECTED</span><b>{image.name}</b></div><em>{image.orientation} · {image.tone} · {image.color}</em></div>}<div className="story-hero"><div><span className="tag">{optionLabel(locale,genre)}</span><span className="tag">{optionLabel(locale,style)}</span><span className="tag">{duration} {t("seconds")}</span><span className="tag">{optionLabel(locale,platform)}</span><span className="tag accent-tag">{optionLabel(locale,model)}</span></div><h2>{story.title}</h2><p>{story.logline}</p><div className="direction-card"><span>CREATIVE DIRECTION</span><p>{story.direction}</p></div>{story.visualAnalysis&&<div className="visual-analysis-card"><span>AI VISUAL REFERENCE ANALYSIS</span><p>{story.visualAnalysis}</p></div>}</div><div className="hook-card"><span>{t("hook")} / HOOK</span><blockquote>“{story.hook}”</blockquote><button onClick={()=>copy(story.hook,"hook")}>{copied==="hook"?t("copied"):t("copy")}</button></div><div className="structure"><h3>{t("narrative")}</h3>{story.structure.map((item,i)=><article key={item[0]}><b>0{i+1}</b><div><h4>{item[0]}</h4><p>{item[1]}</p></div><span>{story.structureTimes?.[i]||`${Math.round(i*duration/story.structure.length)}–${Math.round((i+1)*duration/story.structure.length)}s`}</span></article>)}</div><button className="to-shots" onClick={()=>setActiveTab("shots")}>{t("viewShots")} <span>→</span></button></div>:<div className="shots-view"><div className="shot-title"><div><span className="eyebrow">SHOT LIST · {optionLabel(locale,genre).toUpperCase()} · {optionLabel(locale,style).toUpperCase()}</span><h2>{story.title} · {t("shotScript")}</h2></div><span>{t("totalShots",{count:shots.length,seconds:duration})}</span></div>{shots.map(shot=><article className="shot-card" key={shot.id}><div className="shot-no"><span>SHOT</span><b>{String(shot.id).padStart(2,"0")}</b><em>{shot.time}</em></div><div className="shot-content"><span className="shot-type">{shot.shot}</span><h3>{shot.visual}</h3><div className="shot-meta"><p><b>{t("camera")}</b>{shot.camera}</p><p><b>{t("sound")}</b>{shot.audio}</p></div><div className="prompt"><span>MODEL-READY VIDEO PROMPT · {model.toUpperCase()}</span><pre>{shot.prompt}</pre><button onClick={()=>copy(shot.prompt,`shot${shot.id}`)}>{copied===`shot${shot.id}`?t("copied"):t("copy")}</button></div></div></article>)}</div>}
        </div>
      </section>
    </section>}
  </main>;
}
