"use client";
/* eslint-disable @next/next/no-img-element -- provider favicons and user data URLs are dynamic */
/* eslint-disable react-hooks/purity -- wall-clock timestamps are created only by task callbacks */

import { useEffect, useMemo, useRef, useState } from "react";
import type { RefObject } from "react";
import type { Locale } from "./i18n";
import { videoGenerationProviderById, videoProviderSupportsWorkflow } from "./video-generation-providers";
import ProviderLogo from "./ProviderLogo";
import { reportFrameError } from "./error-codes";

type Workflow="text-to-video"|"image-to-video"|"first-last-frame";
type VideoConfig={providerId:string;apiBaseUrl:string;model:string;hasApiKey:boolean;hasApiSecret?:boolean;updatedAt:string}|null;
type SourceShot={id:number;time:string;visual:string;camera:string;prompt:string};
type Props={locale:Locale;config:VideoConfig;seedTitle:string;seedPrompt:string;sourceShots:SourceShot[];onOpenSettings:()=>void};
type Frame={src:string;name:string};
type StoredVideoTask={token:string;createdAt:number;model?:string};

const VIDEO_TASK_STORAGE="frame:video-task";

const copy={
  "zh-CN":{title:"把镜头真正变成视频。",intro:"从文字、首帧或首尾帧出发，整理模型专属运动指令并直接提交给独立视频引擎。",text:"文生视频",image:"图生视频",frames:"首尾帧视频",source:"生成方式",prompt:"视频内容与动作",placeholder:"描述主体、动作、环境变化、镜头运动、节奏和声音…",model:"视频引擎",director:"导演参数",camera:"镜头运动",motion:"运动强度",duration:"时长",aspect:"画幅",start:"首帧",end:"尾帧",upload:"上传图片",connected:"视频引擎已连接",missing:"尚未配置视频引擎",configure:"配置视频 API",generate:"创建视频任务",generating:"视频正在生成…",queued:"任务已提交，正在等待视频模型渲染。",ready:"视频生成完成",failed:"视频生成失败",unsupported:"当前模型不支持这种生成方式，请切换模型。",story:"来自 01 STORY",timeline:"镜头时间线",empty:"生成后将在这里预览成片",download:"下载 / 打开视频",draft:"制作草案",copy:"复制模型提示词",copied:"已复制",needsFrame:"请先上传首帧图片。",needsEnd:"首尾帧模式还需要尾帧图片。",next:"下一阶段将继续加入多镜头拼接、声音轨道与生成历史。"},
  "zh-TW":{title:"把鏡頭真正變成影片。",intro:"從文字、首幀或首尾幀出發，整理模型專屬運動指令並直接提交給獨立影片引擎。",text:"文字生成影片",image:"圖片生成影片",frames:"首尾幀影片",source:"生成方式",prompt:"影片內容與動作",placeholder:"描述主體、動作、環境變化、鏡頭運動、節奏和聲音…",model:"影片引擎",director:"導演參數",camera:"鏡頭運動",motion:"運動強度",duration:"時長",aspect:"畫幅",start:"首幀",end:"尾幀",upload:"上傳圖片",connected:"影片引擎已連接",missing:"尚未設定影片引擎",configure:"設定影片 API",generate:"建立影片任務",generating:"影片正在生成…",queued:"任務已提交，正在等待影片模型渲染。",ready:"影片生成完成",failed:"影片生成失敗",unsupported:"目前模型不支援此生成方式，請切換模型。",story:"來自 01 STORY",timeline:"鏡頭時間線",empty:"生成後將在這裡預覽成片",download:"下載 / 開啟影片",draft:"製作草案",copy:"複製模型提示詞",copied:"已複製",needsFrame:"請先上傳首幀圖片。",needsEnd:"首尾幀模式還需要尾幀圖片。",next:"下一階段將加入多鏡頭拼接、聲音軌道與生成歷史。"},
  ja:{title:"ショットを本物の映像へ。",intro:"テキスト、開始フレーム、または開始・終了フレームから、モデル固有の動きの指示を組み立て、専用動画エンジンへ送信します。",text:"テキストから動画",image:"画像から動画",frames:"開始・終了フレーム",source:"生成方法",prompt:"映像内容と動き",placeholder:"被写体、動作、環境変化、カメラ、テンポ、音を記述…",model:"動画エンジン",director:"演出設定",camera:"カメラワーク",motion:"動きの強さ",duration:"長さ",aspect:"比率",start:"開始フレーム",end:"終了フレーム",upload:"画像を追加",connected:"動画エンジン接続済み",missing:"動画エンジン未設定",configure:"動画 API 設定",generate:"動画タスクを作成",generating:"動画を生成中…",queued:"タスクを送信し、モデルのレンダリングを待っています。",ready:"動画生成完了",failed:"動画生成失敗",unsupported:"このモデルは選択中の生成方法に対応していません。",story:"01 STORY から",timeline:"ショットタイムライン",empty:"生成後にここでプレビューできます",download:"動画を開く / 保存",draft:"制作ドラフト",copy:"モデルプロンプトをコピー",copied:"コピー済み",needsFrame:"開始フレームを追加してください。",needsEnd:"終了フレームも追加してください。",next:"次の段階でマルチショット結合、音声トラック、生成履歴を追加します。"},
  en:{title:"Turn the shot into motion.",intro:"Start from text, a first frame, or first-and-last frames, build model-specific motion direction, and submit it to a dedicated video engine.",text:"Text to video",image:"Image to video",frames:"First / last frame",source:"Generation mode",prompt:"Video content and action",placeholder:"Describe subject, action, environmental change, camera movement, pacing, and sound…",model:"Video engine",director:"Direction",camera:"Camera move",motion:"Motion strength",duration:"Duration",aspect:"Aspect",start:"First frame",end:"Last frame",upload:"Upload image",connected:"Video engine connected",missing:"No video engine configured",configure:"Configure video API",generate:"Create video task",generating:"Generating video…",queued:"Task submitted and waiting for the video model to render.",ready:"Video generation complete",failed:"Video generation failed",unsupported:"This model does not support the selected generation mode.",story:"From 01 STORY",timeline:"Shot timeline",empty:"Your generated video will preview here",download:"Open / download video",draft:"Production draft",copy:"Copy model prompt",copied:"Copied",needsFrame:"Upload a first frame first.",needsEnd:"First-and-last mode also needs a last frame.",next:"Next: multi-shot assembly, audio tracks, and generation history."},
} as const;

const cameras=["Static lock-off","Slow dolly in","Tracking shot","Orbit move","Handheld follow","Crane reveal"];
const aspects=["16:9","9:16","1:1","21:9"];
const durations=[4,5,8,10,12,15];

function readFrame(file:File){return new Promise<Frame>((resolve,reject)=>{if(!file.type.match(/^image\/(jpeg|png|webp)$/)||file.size>8*1024*1024){reject(new Error("IMAGE"));return}const reader=new FileReader();reader.onerror=()=>reject(new Error("IMAGE"));reader.onload=()=>resolve({src:String(reader.result),name:file.name});reader.readAsDataURL(file)})}

export default function VideoStudio({locale,config,seedTitle,seedPrompt,sourceShots,onOpenSettings}:Props){
  const c=copy[locale];const [workflow,setWorkflow]=useState<Workflow>("text-to-video");const [prompt,setPrompt]=useState(seedPrompt);const [negative,setNegative]=useState("flicker, warped anatomy, unstable identity, abrupt cuts, unreadable text");const [aspect,setAspect]=useState("16:9");const [duration,setDuration]=useState(5);const [camera,setCamera]=useState(cameras[1]);const [motion,setMotion]=useState(55);const [startFrame,setStartFrame]=useState<Frame|null>(null);const [endFrame,setEndFrame]=useState<Frame|null>(null);const [status,setStatus]=useState(seedTitle?`${c.story} · ${seedTitle}`:"");const [statusError,setStatusError]=useState(false);const [generating,setGenerating]=useState(false);const [videoUrl,setVideoUrl]=useState("");const [progress,setProgress]=useState<number|null>(null);const [pendingTaskToken,setPendingTaskToken]=useState("");const [copied,setCopied]=useState(false);const startRef=useRef<HTMLInputElement>(null);const endRef=useRef<HTMLInputElement>(null);const pollRun=useRef(0);
  const provider=config?videoGenerationProviderById(config.providerId):null;
  const supportsWorkflow=(item:Workflow)=>!provider||!config||videoProviderSupportsWorkflow(provider,config.model,item);
  const modelPrompt=useMemo(()=>{const core=prompt.trim();if(!core)return"";const model=config?.model||"VIDEO MODEL";return`${core}\n\nCamera: ${camera}. Duration: ${duration}s. Aspect ratio: ${aspect}. Motion strength: ${motion}/100. Preserve subject identity, wardrobe, lighting logic, spatial continuity and temporal coherence across every frame. Natural acceleration and deceleration; intentional composition; no accidental cuts.${negative.trim()?` Avoid: ${negative.trim()}.`:""}\nTarget model: ${model}.`},[prompt,camera,duration,aspect,motion,negative,config?.model]);
  const timeline=sourceShots.length?sourceShots.slice(0,8):[{id:1,time:`00:00–00:${String(duration).padStart(2,"0")}`,visual:prompt||c.empty,camera,prompt:modelPrompt}];
  function fail(message:string,code?:string){setStatus(message);setStatusError(true);reportFrameError(message,code)}
  async function chooseFrame(file:File|undefined,target:"start"|"end"){if(!file)return;try{const frame=await readFrame(file);if(target==="start")setStartFrame(frame);else setEndFrame(frame);setStatusError(false)}catch{fail("JPG / PNG / WebP · 8MB max","REQ-3002")}}
  async function copyPrompt(){if(!modelPrompt)return;await navigator.clipboard.writeText(modelPrompt);setCopied(true);window.setTimeout(()=>setCopied(false),1400)}
  async function pollVideoTask(token:string,createdAt=Date.now()){
    const run=++pollRun.current;const interval=provider?.protocol==="gemini-veo"?10_000:5_000;const attempts=Math.ceil(1_800_000/interval);let terminal=false;setPendingTaskToken("");setGenerating(true);setStatusError(false);setStatus(c.queued);
    try{for(let attempt=0;attempt<attempts;attempt++){if(run!==pollRun.current)return;if(attempt)await new Promise(resolve=>window.setTimeout(resolve,interval));if(run!==pollRun.current)return;const response=await fetch(`/api/generate-video?taskToken=${encodeURIComponent(token)}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data?.error||c.failed);if(Number.isFinite(data.progress))setProgress(Number(data.progress));const elapsed=Math.max(0,Math.round((Date.now()-createdAt)/1000));setStatus(`${c.queued} · ${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,"0")}`);if(data.status==="failed"){terminal=true;localStorage.removeItem(VIDEO_TASK_STORAGE);throw new Error(data.error||c.failed)}if(data.status==="succeeded"&&data.videoUrl){localStorage.setItem(VIDEO_TASK_STORAGE,JSON.stringify({token,createdAt,model:config?.model} satisfies StoredVideoTask));setVideoUrl(data.videoUrl);setStatusError(false);setStatus(c.ready);return}}
      setPendingTaskToken(token);setStatus("视频仍在服务商队列中，任务已保存；可以稍后继续查询。");
    }catch(error){setPendingTaskToken(terminal?"":token);const message=error instanceof Error?error.message:c.failed;fail(message,/视频文件|video result/i.test(message)?"VID-4203":"VID-4202")}finally{if(run===pollRun.current)setGenerating(false)}
  }
  useEffect(()=>{const timer=window.setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem(VIDEO_TASK_STORAGE)||"null") as StoredVideoTask|null;if(saved?.token&&Date.now()-saved.createdAt<2_700_000)void pollVideoTask(saved.token,saved.createdAt);else localStorage.removeItem(VIDEO_TASK_STORAGE)}catch{localStorage.removeItem(VIDEO_TASK_STORAGE)}},0);return()=>{window.clearTimeout(timer);pollRun.current++}},[]); // eslint-disable-line react-hooks/exhaustive-deps
  async function generate(){
    if(!config){onOpenSettings();fail(c.missing,"CFG-2001");return}if(!supportsWorkflow(workflow)){fail(c.unsupported,"CFG-2003");return}if(!modelPrompt)return;if(workflow!=="text-to-video"&&!startFrame){fail(c.needsFrame,"IMG-4101");return}if(workflow==="first-last-frame"&&!endFrame){fail(c.needsEnd,"IMG-4101");return}
    pollRun.current++;localStorage.removeItem(VIDEO_TASK_STORAGE);setPendingTaskToken("");setGenerating(true);setVideoUrl("");setProgress(null);setStatusError(false);setStatus(c.queued);
    try{const response=await fetch("/api/generate-video",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:modelPrompt,negativePrompt:negative,workflow,aspect,duration,startFrame:startFrame?.src,endFrame:endFrame?.src})});const data=await response.json();if(!response.ok)throw new Error(data?.error||c.failed);if(data.videoUrl){setVideoUrl(data.videoUrl);setStatusError(false);setStatus(c.ready);return}const token=data.taskToken;if(!token)throw new Error(c.failed);const createdAt=Date.now();localStorage.setItem(VIDEO_TASK_STORAGE,JSON.stringify({token,createdAt,model:config.model} satisfies StoredVideoTask));await pollVideoTask(token,createdAt);
    }catch(error){const message=error instanceof Error?error.message:c.failed;fail(message,"VID-4201")}finally{setGenerating(false)}
  }
  return <section className="video-studio">
    <header className="video-studio-head"><div><span><i/> 04 / VIDEO PRODUCTION</span><h1>{c.title}</h1><p>{c.intro}</p></div><div className={`video-engine-badge ${config?"connected":""}`}><ProviderLogo src={provider?.logo} short={provider?.short||"V"} name={provider?.name||c.model}/><span><small>{c.model}</small><strong>{config?`${provider?.name} · ${config.model}`:c.missing}</strong></span><button onClick={onOpenSettings}>{c.configure} ↗</button></div></header>
    <div className="video-studio-grid">
      <aside className="video-compose-panel">
        <label className="video-label">01 / {c.source}</label><div className="video-mode-switch">{(["text-to-video","image-to-video","first-last-frame"] as Workflow[]).map((item,index)=>{const supported=supportsWorkflow(item);return <button key={item} className={workflow===item?"active":""} disabled={!supported} title={supported?"":c.unsupported} onClick={()=>{setWorkflow(item);setVideoUrl("")}}><i>{index===0?"Aa":index===1?"01":"01—02"}</i><span>{item==="text-to-video"?c.text:item==="image-to-video"?c.image:c.frames}</span></button>})}</div>
        <label className="video-label">02 / {c.prompt}</label><div className="video-prompt-field"><textarea value={prompt} onChange={event=>setPrompt(event.target.value)} placeholder={c.placeholder} maxLength={4000}/><span>{prompt.length}/4000</span></div>
        {workflow!=="text-to-video"&&<div className="video-frame-inputs"><FrameInput label={c.start} frame={startFrame} inputRef={startRef} onFile={file=>void chooseFrame(file,"start")} onClear={()=>setStartFrame(null)} upload={c.upload}/>{workflow==="first-last-frame"&&<FrameInput label={c.end} frame={endFrame} inputRef={endRef} onFile={file=>void chooseFrame(file,"end")} onClear={()=>setEndFrame(null)} upload={c.upload}/>}</div>}
        <label className="video-label">03 / {c.director}</label><div className="video-director-grid"><label><span>{c.camera}</span><select value={camera} onChange={event=>setCamera(event.target.value)}>{cameras.map(item=><option key={item}>{item}</option>)}</select></label><label><span>{c.duration}</span><select value={duration} onChange={event=>setDuration(Number(event.target.value))}>{durations.map(item=><option key={item} value={item}>{item}s</option>)}</select></label><label><span>{c.aspect}</span><select value={aspect} onChange={event=>setAspect(event.target.value)}>{aspects.map(item=><option key={item}>{item}</option>)}</select></label></div>
        <label className="video-motion"><span>{c.motion}<b>{motion}%</b></span><input type="range" min="0" max="100" value={motion} onChange={event=>setMotion(Number(event.target.value))}/></label>
        <label className="video-negative"><span>NEGATIVE / AVOID</span><textarea value={negative} onChange={event=>setNegative(event.target.value)} maxLength={1000}/></label>
        <div className="video-engine-line"><span className={config?"connected":""}><i/>{config?c.connected:c.missing}</span><button onClick={onOpenSettings}>{c.configure}</button></div><button className="video-generate" disabled={generating||!prompt.trim()} onClick={generate}><span>{generating?c.generating:c.generate}</span><b>{generating?"···":"↗"}</b></button><div className={`video-status ${statusError?"error":generating?"loading":videoUrl?"success":""}`} aria-live="polite"><span>{status||c.next}{progress!==null?` · ${Math.round(progress)}%`:""}</span>{pendingTaskToken&&!generating?<button onClick={()=>void pollVideoTask(pendingTaskToken)}>继续查询 ↗</button>:statusError?<button onClick={onOpenSettings}>{c.configure} ↗</button>:null}</div>
      </aside>
      <main className="video-production-canvas">
        <div className={`video-preview ${videoUrl?"ready":""}`}>{videoUrl?<video src={videoUrl} controls playsInline/>:<><div className="video-preview-scene"><i className="video-sun"/><i className="video-horizon"/><i className="video-subject"/><span className="video-motion-path"/></div><div className="video-preview-empty"><i>▶</i><b>{generating?c.generating:statusError?c.failed:c.empty}</b><span>{statusError?status:config?.model||"VIDEO ENGINE OFFLINE"}</span></div></>}<div className="video-preview-hud"><span><i/> {videoUrl?"OUTPUT READY":generating?"RENDERING":"COMPOSITOR READY"}</span><b>{aspect} · {duration}s</b></div></div>
        <section className="video-timeline"><div className="video-section-head"><div><span>SEQUENCE / {c.story}</span><h2>{c.timeline}</h2></div><b>{timeline.length} CLIP{timeline.length===1?"":"S"}</b></div><div className="video-track"><span className="video-track-line"/>{timeline.map((shot,index)=><article key={`${shot.id}-${index}`}><div><i>{String(index+1).padStart(2,"0")}</i><span>{shot.visual}</span></div><small>{shot.time} · {shot.camera}</small></article>)}</div></section>
      </main>
      <aside className="video-output-panel"><div className="video-section-head"><div><span>MODEL PACKAGE</span><h2>{videoUrl?c.ready:c.draft}</h2></div><b>{config?.model||"NO ENGINE"}</b></div>{videoUrl?<div className="video-result-card"><video src={videoUrl} controls playsInline/><a href={videoUrl} target="_blank" rel="noreferrer">{c.download} ↗</a></div>:<div className="video-package"><span>MODEL-READY VIDEO PROMPT</span><pre>{modelPrompt||c.placeholder}</pre><div><b>{aspect}</b><b>{duration}s</b><b>MOTION {motion}</b></div></div>}<button className="video-copy" onClick={copyPrompt} disabled={!modelPrompt}>{copied?c.copied:c.copy}</button><div className="video-roadmap"><i/> <span><b>FOUNDATION / 01</b><small>{c.next}</small></span></div></aside>
    </div>
  </section>
}

function FrameInput({label,frame,inputRef,onFile,onClear,upload}:{label:string;frame:Frame|null;inputRef:RefObject<HTMLInputElement|null>;onFile:(file:File|undefined)=>void;onClear:()=>void;upload:string}){
  return <div className={`video-frame-input ${frame?"loaded":""}`}><span>{label}</span><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>{onFile(event.target.files?.[0]);event.currentTarget.value=""}}/>{frame?<><img src={frame.src} alt=""/><b>{frame.name}</b><button onClick={onClear}>×</button></>:<button onClick={()=>inputRef.current?.click()}><i>＋</i>{upload}</button>}</div>
}
